### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

I would like to separate minor fixes of the codebase from https://github.com/optuna/optuna/pull/1201 as commented by @himkt.

## Description of the changes

Fix typos and style fixes.

### CODE REVIEW

**Comment by nzw0301** [comment]
@himkt fd96523 is not related to `suggest_int`.  So this PR includes it. Should I separate it as another PR?

Thank you for reporting the missing commit. The commit is in this PR now.

**Comment by himkt** [comment]
Thank you for the clarifying, it makes sense.
IMO, it would be better for me to separate fd96523 as another PR since `suggest_float` with `step` hasn't been tested yet.

For a test, I think it's enough to add `p6 = trial.suggest_float("p0", -10, 10, step=1)`.
(just my opinion)
https://github.com/optuna/optuna/blob/master/tests/multi_objective/test_trial.py#L22

@nzw0301 What do you think?

**Comment by nzw0301** [comment]
@himkt Ok. I have reverted it.

**Comment by nzw0301** [comment]
I have created another PR for https://github.com/optuna/optuna/commit/fd9652386c97ba00a07b97eac1f180483dd6d614

**Comment by nzw0301** [comment]
Thank you for reviewing my PR!

**Pull request merged**
