### PR TITLE
Fix #3129: TPE not working with a categorical variable with different choice types

### LINKED ISSUE #3129: TPE not working with a categorical variable with different choice types
Hi. Thanks for this amazing library!

When I try to optimize a model with a categorical variable with different choice types, it gives me `IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (9,) (4,)`. This error always happens after 10 trials.

I would be very grateful for an explanation on why is that the case - I guess it has to do with how TPE makes categorical variables continuous, but I wasn't able to find how it's done.

Also, I think that it might be very useful for people relatively new to Optuna if the error was more self-explanatory. In my case, it took over 10h to find out why my optimization failed.

## Environment

- Optuna version: 2.10.0
- Python version: 3.6.10
- OS: Linux-4.18.0-305.10.2.el8_4.ppc64le-ppc64le-with-redhat-8.4-Ootpa

## Error messages, stack traces, or logs

```
/home/chledj01/.local/lib/python3.6/site-packages/optuna/samplers/_tpe/sampler.py:266: ExperimentalWarning: ``multivariate`` option is an experimental feature. The interface can change in the future.
  ExperimentalWarning,
/home/chledj01/.local/lib/python3.6/site-packages/optuna/samplers/_tpe/sampler.py:285: ExperimentalWarning: ``constant_liar`` option is an experimental feature. The interface can change in the future.
  ExperimentalWarning,
[I 2021-11-28 07:31:46,317] Trial 0 finished with value: 51.25318418441549 and parameters: {'x1': 7.159132921270249, 'x2': None}. Best is trial 0 with value: 51.25318418441549.
[I 2021-11-28 07:31:46,661] Trial 1 finished with value: 0.0 and parameters: {'x1': -6.523347451025641, 'x2': 1}. Best is trial 0 with value: 51.25318418441549.
[I 2021-11-28 07:31:46,857] Trial 2 finished with value: 77.13131244750303 and parameters: {'x1': 8.782443421252598, 'x2': None}. Best is trial 2 with value: 77.13131244750303.
[I 2021-11-28 07:31:47,067] Trial 3 finished with value: 71.35511499232025 and parameters: {'x1': -8.447195688056496, 'x2': None}. Best is trial 2 with value: 77.13131244750303.
[I 2021-11-28 07:31:47,283] Trial 4 finished with value: 0.0 and parameters: {'x1': 7.448216057409198, 'x2': 1}. Best is trial 2 with value: 77.13131244750303.
[I 2021-11-28 07:31:47,537] Trial 5 finished with value: 42.52100156846517 and parameters: {'x1': 6.520812953034703, 'x2': None}. Best is trial 2 with value: 77.13131244750303.
[I 2021-11-28 07:31:47,757] Trial 6 finished with value: 0.0 and parameters: {'x1': 3.2600618681215856, 'x2': 1}. Best is trial 2 with value: 77.13131244750303.
[I 2021-11-28 07:31:47,905] Trial 7 finished with value: 88.15753251520141 and parameters: {'x1': 9.389224276541775, 'x2': None}. Best is trial 7 with value: 88.15753251520141.
[I 2021-11-28 07:31:48,029] Trial 8 finished with value: 39.329878182295595 and parameters: {'x1': 6.271353775884087, 'x2': None}. Best is trial 7 with value: 88.15753251520141.
[I 2021-11-28 07:31:48,144] Trial 9 finished with value: 0.0 and parameters: {'x1': -7.077110913961812, 'x2': 1}. Best is trial 7 with value: 88.15753251520141.
Traceback (most recent call last):
  File "optuna_test.py", line 23, in <module>
    study.optimize(train, n_trials=300)
  File "/home/chledj01/.local/lib/python3.6/site-packages/optuna/study/study.py", line 409, in optimize
    show_progress_bar=show_progress_bar,
  File "/home/chledj01/.local/lib/python3.6/site-packages/optuna/study/_optimize.py", line 76, in _optimize
    progress_bar=progress_bar,
  File "/home/chledj01/.local/lib/python3.6/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/home/chledj01/.local/lib/python3.6/site-packages/optuna/study/_optimize.py", line 194, in _run_trial
    trial = study.ask()
  File "/home/chledj01/.local/lib/python3.6/site-packages/optuna/study/study.py", line 486, in ask
    trial = trial_module.Trial(self, trial_id)
  File "/home/chledj01/.local/lib/python3.6/site-packages/optuna/trial/_trial.py", line 56, in __init__
    self._init_relative_params()
  File "/home/chledj01/.local/lib/python3.6/site-packages/optuna/trial/_trial.py", line 66, in _init_relative_params
    study, trial, self.relative_search_space
  File "/home/chledj01/.local/lib/python3.6/site-packages/optuna/samplers/_tpe/sampler.py", line 349, in sample_relative
    return self._sample_relative(study, trial, search_space)
  File "/home/chledj01/.local/lib/python3.6/site-packages/optuna/samplers/_tpe/sampler.py", line 386, in _sample_relative
    mpe_above = _ParzenEstimator(above, search_space, self._parzen_estimator_parameters)
  File "/home/chledj01/.local/lib/python3.6/site-packages/optuna/samplers/_tpe/parzen_estimator.py", line 87, in __init__
    param_observations, param_name
  File "/home/chledj01/.local/lib/python3.6/site-packages/optuna/samplers/_tpe/parzen_estimator.py", line 366, in _calculate_categorical_params
    weights[np.arange(n_observations), observations] += 1
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (9,) (4,)
```

## Steps to reproduce

1. Create an optuna study with `optuna create-study --study-name '1234' --storage 'sqlite:///test.db' --direction 'maximize'`
2. Run `optuna_test.py` defined below.

## Reproducible examples (optional)

`optuna_test.py`:
```python
import optuna


def train(trial):
    x1 = trial.suggest_uniform('x1', -10, 10)
    x2 = trial.suggest_categorical('x2', [None, 1])
    if x2:
        score = 0
    else:
        score = x1 ** 2
    return score


if __name__ == "__main__":

    sampler = optuna.samplers.TPESampler(multivariate=True,
                                         group=False,
                                         constant_liar=True)
    study = optuna.load_study(study_name='1234',
                              sampler=sampler,
                              storage="sqlite:///test.db")

    study.optimize(train, n_trials=300)
```

### PR DESCRIPTION
**Pull request by keisukefukuda**
## Motivation

Bugfix of #3129 

## Description of the changes

This bug is caused by[ `_get_observation_pairs()`](https://github.com/optuna/optuna/blob/f0b2071333ecd20fc3a18f4695b67225c26eb933/optuna/samplers/_tpe/sampler.py#L633) function in `_tpe/sample.py`. The function uses `None` as the "fallback default" value for searching params in `trial.params`.

```
raw_param_value = trial.params.get(param_name, None)
param_value: Optional[float]
if raw_param_value is not None:
```

However,  when `raw_param_value` is `None`, this does not work. The code is fixed to use `if param_name in trial.params` and avoid using a particular value as the default value.

After the bugfix, the reproduce script `optuna_test.py` that is created by the original reporter of the issue works fine.

```
$ optuna create-study --study-name '1234' --storage 'sqlite:///test.db' --direction 'maximize' && python3 optuna_test.py
[I 2021-12-19 17:15:16,275] A new study created in RDB with name: 1234
1234
/Users/keisukefukuda/work/optuna/optuna/samplers/_tpe/sampler.py:266: ExperimentalWarning: ``multivariate`` option is an experimental feature. The interface can change in the future.
  ExperimentalWarning,
/Users/keisukefukuda/work/optuna/optuna/samplers/_tpe/sampler.py:285: ExperimentalWarning: ``constant_liar`` option is an experimental feature. The interface can change in the future.
  ExperimentalWarning,
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:23,402] Trial 0 finished with value: 20.23027610219457 and parameters: {'x1': -4.497807921887569, 'x2': None}. Best is trial 0 with value: 20.23027610219457.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:23,661] Trial 1 finished with value: 0.0 and parameters: {'x1': -6.830249984050218, 'x2': 100}. Best is trial 0 with value: 20.23027610219457.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:23,884] Trial 2 finished with value: 94.9583753816821 and parameters: {'x1': -9.74465881299505, 'x2': None}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:24,196] Trial 3 finished with value: 19.311182262077164 and parameters: {'x1': 4.394449028271595, 'x2': None}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:24,463] Trial 4 finished with value: 0.0 and parameters: {'x1': -4.861678154418259, 'x2': 100}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:24,589] Trial 5 finished with value: 0.0 and parameters: {'x1': 8.091630635228949, 'x2': 100}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:24,697] Trial 6 finished with value: 22.43454883422271 and parameters: {'x1': 4.736512306985247, 'x2': None}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:24,830] Trial 7 finished with value: 8.56039415731601 and parameters: {'x1': -2.9258151269887183, 'x2': None}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:24,975] Trial 8 finished with value: 47.24752561887984 and parameters: {'x1': -6.873683555334784, 'x2': None}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:25,119] Trial 9 finished with value: 0.0 and parameters: {'x1': -0.7344751334333814, 'x2': 100}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:25,238] Trial 10 finished with value: 74.63123120750546 and parameters: {'x1': -8.638936925774228, 'x2': None}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:25,344] Trial 11 finished with value: 87.77309746399034 and parameters: {'x1': -9.368729767902922, 'x2': None}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:25,468] Trial 12 finished with value: 88.38159368713423 and parameters: {'x1': -9.401148530213435, 'x2': None}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:25,611] Trial 13 finished with value: 0.0 and parameters: {'x1': -9.73597876503898, 'x2': 100}. Best is trial 2 with value: 94.9583753816821.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:25,811] Trial 14 finished with value: 97.57899506041372 and parameters: {'x1': -9.87820808954811, 'x2': None}. Best is trial 14 with value: 97.57899506041372.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:25,995] Trial 15 finished with value: 97.42559374186968 and parameters: {'x1': -9.87044040262995, 'x2': None}. Best is trial 14 with value: 97.57899506041372.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:26,388] Trial 16 finished with value: 0.6909139571730675 and parameters: {'x1': -0.8312123418074755, 'x2': None}. Best is trial 14 with value: 97.57899506041372.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:26,629] Trial 17 finished with value: 25.43548256342697 and parameters: {'x1': -5.043360245255832, 'x2': None}. Best is trial 14 with value: 97.57899506041372.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:27,231] Trial 18 finished with value: 99.11895326426185 and parameters: {'x1': 9.955850202984266, 'x2': None}. Best is trial 18 with value: 99.11895326426185.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:27,829] Trial 19 finished with value: 67.39676602219951 and parameters: {'x1': 8.209553338775473, 'x2': None}. Best is trial 18 with value: 99.11895326426185.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:28,508] Trial 20 finished with value: 71.96823410644555 and parameters: {'x1': 8.483409344505636, 'x2': None}. Best is trial 18 with value: 99.11895326426185.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:29,211] Trial 21 finished with value: 79.19397590016085 and parameters: {'x1': 8.89909972413844, 'x2': None}. Best is trial 18 with value: 99.11895326426185.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:29,708] Trial 22 finished with value: 95.56493864534751 and parameters: {'x1': 9.775732128354761, 'x2': None}. Best is trial 18 with value: 99.11895326426185.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:30,013] Trial 23 finished with value: 97.55860858513729 and parameters: {'x1': -9.87717614428017, 'x2': None}. Best is trial 18 with value: 99.11895326426185.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:30,511] Trial 24 finished with value: 99.18178000327762 and parameters: {'x1': -9.959004970541868, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:30,886] Trial 25 finished with value: 0.0 and parameters: {'x1': 4.4393163713188235, 'x2': 100}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:31,507] Trial 26 finished with value: 35.03470468458785 and parameters: {'x1': -5.919012137560443, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:31,858] Trial 27 finished with value: 93.91825948206618 and parameters: {'x1': -9.691143352673418, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:32,090] Trial 28 finished with value: 77.18243604348694 and parameters: {'x1': 8.785353495647568, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:32,546] Trial 29 finished with value: 23.904534918966615 and parameters: {'x1': -4.889226413142126, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:32,875] Trial 30 finished with value: 29.689655282608044 and parameters: {'x1': -5.4488214581327625, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:33,133] Trial 31 finished with value: 92.9196089499113 and parameters: {'x1': -9.6394817780787, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:33,445] Trial 32 finished with value: 97.97594132645159 and parameters: {'x1': -9.89827971550873, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:33,705] Trial 33 finished with value: 0.0 and parameters: {'x1': -9.109364019645351, 'x2': 100}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:33,893] Trial 34 finished with value: 97.98863117180308 and parameters: {'x1': -9.898920707420737, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:34,155] Trial 35 finished with value: 96.3450346153301 and parameters: {'x1': -9.81555065268017, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:34,295] Trial 36 finished with value: 85.65082597994967 and parameters: {'x1': -9.25477314578535, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:34,507] Trial 37 finished with value: 0.0 and parameters: {'x1': -5.465556788267465, 'x2': 100}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:34,659] Trial 38 finished with value: 96.82759942985447 and parameters: {'x1': -9.840101596520967, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:34,862] Trial 39 finished with value: 0.0 and parameters: {'x1': 7.086505180697853, 'x2': 100}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:35,056] Trial 40 finished with value: 0.0 and parameters: {'x1': 9.701757828680893, 'x2': 100}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:35,273] Trial 41 finished with value: 94.71545700466312 and parameters: {'x1': -9.732186650730817, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:35,514] Trial 42 finished with value: 91.7458394388747 and parameters: {'x1': -9.578404848348951, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:35,677] Trial 43 finished with value: 91.46618858314017 and parameters: {'x1': -9.563795720483586, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:35,846] Trial 44 finished with value: 46.29485628296195 and parameters: {'x1': -6.80403235463809, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:35,995] Trial 45 finished with value: 95.10143557734003 and parameters: {'x1': -9.75199649186463, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:36,446] Trial 46 finished with value: 18.77415673981897 and parameters: {'x1': 4.332915501116883, 'x2': None}. Best is trial 24 with value: 99.18178000327762.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:36,985] Trial 47 finished with value: 99.8660064099571 and parameters: {'x1': -9.993298074707724, 'x2': None}. Best is trial 47 with value: 99.8660064099571.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:37,278] Trial 48 finished with value: 41.09839537034104 and parameters: {'x1': -6.410803020709733, 'x2': None}. Best is trial 47 with value: 99.8660064099571.
test.py:5: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  x1 = trial.suggest_uniform("x1", -10, 10)
[I 2021-12-19 17:15:37,701] Trial 49 finished with value: 0.0 and parameters: {'x1': -9.772832759492589, 'x2': 100}. Best is trial 47 with value: 99.8660064099571.
```

### CODE REVIEW

**Comment by g-votte** [comment]
Thanks for your PR!

Would you mind adding to `optuna/tests/samplers_tests/test_samplers.py` new test cases that fail the original logic?
I think we can use the same scenario as https://github.com/optuna/optuna/issues/3129#issue-1065321674.

**Comment by HideakiImamura** [comment]
@not522 Could you review this PR if you have time? If you are busy, please unassign by yourself.

**Review by HideakiImamura — COMMENTED** [review]
Thanks for the PR! The code looks good me. As @g-votte said, could you add a test case to validate this change?

**Comment by HideakiImamura** [comment]
@keisukefukuda Let me kindly ping :)

**Review by HideakiImamura — APPROVED** [review]
LGTM. I think that we can add a test as a follow-up task.

**Review by not522 — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
