### PR TITLE
Convert type comments in `optuna/study.py` into type annotations.

### PR DESCRIPTION
**Pull request by harupy**
## Motivation

#711

## Description of the changes

Convert type comments in `optuna/study.py` into type annotations.

### CODE REVIEW

**Review by HideakiImamura — COMMENTED** [review]
Thanks for the PR! The changes LGTM. Currently, the new version of the format checker `black` is released. Could you merge master and apply new black?

**Comment by harupy** [comment]
@HideakiImamura Done!

**Review by HideakiImamura — APPROVED** [review]
Thanks for your swift action! LGTM!

**Review by toshihikoyanase — APPROVED** [review]
LGTM. Thank you for your contribution as always.

**Pull request merged**
