### PR TITLE
Do not run the GC after every trial by default.

### PR DESCRIPTION
**Pull request by hvy**
## Motivation

Fixes https://github.com/optuna/optuna/issues/1307. See this issue for discussions.

## Description of the changes

Changes the default GC collection behavior of `Study.optimize` to not run a collection.

### CODE REVIEW

**Comment by hvy** [comment]
Is it not addressed by https://github.com/optuna/optuna/blob/master/optuna/integration/chainermn.py#L146? I was also wondering whether this line should be kept or controllable similar to the standard `Study`.

**Comment by toshihikoyanase** [comment]
The line is executed by non-rank-0 nodes, but I think we need to call GC for rank-0 node. The rank-0 node calls `Study.optimize` without `gc_after_trial` option at https://github.com/optuna/optuna/blob/master/optuna/integration/chainermn.py#L122. And I think it may cause similar issues to #325.

> this line should be kept or controllable similar to the standard Study.

Depending on the user code and environments, GC calls can be omitted. I support the latter approach, but I think we can work on it in a new PR.

**Comment by hvy** [comment]
Thanks for your explanation. I now see what you meant, that the behavior of `ChainerMNStudy` will be different for different workers, that only the first worker will not run the GC collection. However, as the underlying motivation behind this change is to leave the memory handling to the users, I suggest we stop running the GC in the `ChainerMNStudy` as well. Let me change it that way (discussed with @toshihikoyanase).

**Comment by hvy** [comment]
PTAL.

**Pull request merged**
