### PR TITLE
Fix future annotations in `percentile.py`

### PR DESCRIPTION
**Pull request by aaravm**
## Motivation

Related to #4508 

## Description of the changes

Simplify future annotations of the file optuna/pruners/_percentile.py as described in the issue 4508

### CODE REVIEW

**Comment by eukaryo** [comment]
@contramundum53 Could you review this PR?

**Review by eukaryo — APPROVED** [review]
LGTM!

**Comment by eukaryo** [comment]
Thank you so much for your contribution!

I wanted to let you know that I've made a slight adjustment to the PR description by editing the "Fixed #IssueNumber" text. This change doesn't reflect on the quality of your PR, which is excellent; it's simply to moderate GitHub's automatic behavior.

The term "fixed" in the PR's description or in a commit message triggers GitHub to automatically close the associated issue when the PR is merged. In this case, we prefer not to close issue https://github.com/optuna/optuna/issues/4508 just yet. For more information on how these keywords work, you can check out [GitHub's documentation on linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Review by contramundum53 — APPROVED** [review]
LGTM!

**Pull request merged**
