### PR TITLE
Remove deprecated warning of lightgbm in lightgbm_tuner_tests

### PR DESCRIPTION
**Pull request by knshnb**
## Motivation

Use callback interface instead of the deprecated argument in lightgbm v3.3.0.
#3036 

## Description of the changes

I replaced `early_stopping_rounds=n` by `callbacks=[early_stopping(n)]` in `tests/integration_tests/lightgbm_tuner_tests/test_optimize.py`.

### CODE REVIEW

**Comment by nzw0301** [comment]
[To reviewer] Maybe https://github.com/optuna/optuna/issues/3145 causes the error...

**Comment by nzw0301** [comment]
LightGBM 3.3.2 has been released. Let me re-run the CIs...

**Comment by knshnb** [comment]
I merged master to reflect #3201.

**Comment by knshnb** [comment]
The test still fails. #3145 does not seem to be fixed by LightGBM 3.3.2 (https://github.com/microsoft/LightGBM/releases/tag/v3.3.2).
Shall we just wait for the next release...?

**Comment by nzw0301** [comment]
I think so. Yes, I agree with you 🙇🏻

**Comment by nzw0301** [comment]
We might need to fix the other part for the next release of lightgbm as described on https://github.com/optuna/optuna/issues/3646.

**Pull request closed without merging**
