### PR TITLE
Remove shap

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Progress https://github.com/optuna/optuna/issues/4484 and https://github.com/optuna/optuna/issues/4789. 

## Description of the changes
Move `ShapleyImportanceEvaluator`, related test and docs.

### CODE REVIEW

**Comment by c-bata** [comment]
@eukaryo @contramundum53 Could you review this PR?

**Comment by contramundum53** [comment]
I'll review this PR after https://github.com/optuna/optuna-integration/pull/32 is merged.

**Comment by Alnusjaponica** [comment]
@contramundum53
This is a kind reminder that I am waiting for your review.

**Comment by c-bata** [comment]
Let me reassign reviewers. @HideakiImamura Could you review this PR if you have time?

**Review by c-bata — APPROVED** [review]
LGTM!

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
