### PR TITLE
Simplify type annontaitions to  _imports.py

### PR DESCRIPTION
**Pull request by Prabhat-Thapa45**
## Motivation

Related to #4508
I saw `_imports.py` was yet to be simplified and wanted to start contributing.

## Description of the changes

I have added simplifications in type annotations for the file `_imports.py`

### CODE REVIEW

**Review by nzw0301 — CHANGES_REQUESTED** [review]
Could you replace `Tuple`?

**Comment by nzw0301** [comment]
By the way, the author account of your commit: https://github.com/optuna/optuna/pull/5692/commits/15cdf7d58f379a96ce909f89abef1711186ce5ed, looks another account. Is it yours too?

**Comment by Prabhat-Thapa45** [comment]
@nzw0301 oh I have that account logged in my local machine.

**Review by nzw0301 — APPROVED** [review]

**Review by toshihikoyanase — APPROVED** [review]
Looks great to me. Thank you for your contribution.

**Pull request merged**
