### PR TITLE
Fix `visualization.matplotlib.plot_optimization_history` for multi-objective

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

See #2531 

## Description of the changes

Unify the logic to Plotly's one.

## Results 
---

```python
import optuna


def objective(trial):
    # Binh and Korn function.
    x = trial.suggest_float("x", 0, 5)
    y = trial.suggest_float("y", 0, 3)

    v0 = 4 * x ** 2 + 4 * y ** 2
    v1 = (x - 5) ** 2 + (y - 5) ** 2
    return v0, v1


study = optuna.study.create_study(directions=["minimize", "minimize"])
study.optimize(objective, n_trials=10)

optuna.visualization.plot_optimization_history(study, target=lambda t: t.values[0])
optuna.visualization.matplotlib.plot_optimization_history(study, target=lambda t: t.values[0])
```

## Matplotlib
download (1)

### Plotly as reference
newplot (1)

### CODE REVIEW

**Comment by nzw0301** [comment]
By the way, it might be great to add a multi objective example or more description for the target argument  because specifying target was unclear for me.

**Comment by nzw0301** [comment]
Any update? :)

**Comment by HideakiImamura** [comment]
Sorry for the late reply. I've just started to review this PR.

**Review by HideakiImamura — COMMENTED** [review]
Thanks for the PR. In the `else` case, I think we will not get the legend, is this what we expect?

**Comment by nzw0301** [comment]
@HideakiImamura Thank you for your feedback! Yes, since Plotly's function also doesn't show the legend.

**Review by HideakiImamura — APPROVED** [review]
Sure! I confirmed the behavior by seeing `visualization/plot_optimimzation_history`. LGTM!

**Review by toshihikoyanase — APPROVED** [review]
Thank you for your PR. I confirmed that the change resolved #2531. I also confirmed that it does not affect plots for single objective optimization. LGTM!

image

@keisuke-umezawa Let me review this PR since we'll freeze the code for v2.7 today.

**Pull request merged**
