### PR TITLE
Add test cases in `optuna/visualization/matplotlib/edf.py`

### PR DESCRIPTION
**Pull request by keisuke-umezawa**
## Motivation

Add more test cases similar to `optuna/visualization/matplotlib/edf.py`

## Description of the changes

- Check numbers of lines
- Check titles of figures

### CODE REVIEW

**Review by hvy — APPROVED** [review]
Thanks a lot, LGTM!

The x-axis label could actually be checked in all cases since it's always present but this seems consistent with the plotly unit tests. Again, thanks!

**Comment by hvy** [comment]
@nzw0301 would you like to jump in as a second reviewer?

**Comment by hvy** [comment]
The unrelated CI failures should be fixed in the `master` branch. Could you rebase/merge with the `master` to rerun the tests?

**Review by nzw0301 — APPROVED** [review]
LGTM!

**Pull request merged**
