### PR TITLE
[WIP] Support latest pytorch lightning

### PR DESCRIPTION
**Pull request by higucheese**
## Motivation

- Resolve https://github.com/optuna/optuna/issues/3418, enable tests on the latest pytorch lightning
- Resolve https://github.com/optuna/optuna/issues/4116

## Description of the changes

- Replace some deprecated/removed functions/attributes with the latest ones
- Migrate to the latest specification of pl.Trainer

## TODO

- [x] Fix a port conflict in `tests/integration_tests/test_pytorch_lightning.py::test_pytorch_lightning_pruning_callback_ddp_unsupported_storage[redis]`
- [ ] Make all callback functions to be called in pl.Trainer
- [ ] (optional) Add tests for both `ddp` and `ddp_spawn`

## Additional context

- https://github.com/optuna/optuna/pull/3431

### CODE REVIEW

**Comment by higucheese** [comment]
```
Passing training strategies (e.g., "ddp") to accelerator has been deprecated in v1.5.0 and will be removed in v1.7.0. Please use the strategy argument instead.
```
https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#trainer-flags

**Comment by higucheese** [comment]
```
num_processes=x has been deprecated in v1.7 and will be removed in v2.0. Please use accelerator='cpu' and devices=x instead.
```
We can replace `num_processes` in this PR.
https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#num-processes

**Comment by HideakiImamura** [comment]
@gen740 Could you review this PR after WIP is removed?

**Comment by kenniy** [comment]
Any hope for this PR? Will be great to be able to update pl 😄 🙏🏽

**Pull request closed without merging**
