### PR TITLE
Reduce warning messages by `tests/study_tests/`

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

A part of https://github.com/optuna/optuna/issues/3815.

## Description of the changes

- Add `@pytest.mark.filterwarnings` to reduce the warning messages by deprecated modules of Optuna.
- Minor fixes of docstring

### CODE REVIEW

**Comment by nzw0301** [comment]
I'm not sure how to remove the last warning message from the TPE sampler. The warning message is as follows:

```bash
Users/nzw/Documents/optuna> pytest tests/study_tests/test_study.py::test_optimize_parallel_timeout

===================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/nzw/Documents/optuna, configfile: pyproject.toml
plugins: anyio-3.5.0
collected 60 items

tests/study_tests/test_study.py ............................................................                                                                                            [100%]

====================================================================================== warnings summary =======================================================================================
tests/study_tests/test_study.py::test_optimize_parallel_timeout[20--1-redis]
tests/study_tests/test_study.py::test_optimize_parallel_timeout[20--1-cached_redis]
tests/study_tests/test_study.py::test_optimize_parallel_timeout[None-2-cached_redis]
tests/study_tests/test_study.py::test_optimize_parallel_timeout[None--1-inmemory]
tests/study_tests/test_study.py::test_optimize_parallel_timeout[None--1-sqlite]
tests/study_tests/test_study.py::test_optimize_parallel_timeout[None--1-cached_sqlite]
tests/study_tests/test_study.py::test_optimize_parallel_timeout[None--1-redis]
tests/study_tests/test_study.py::test_optimize_parallel_timeout[None--1-cached_redis]
  /opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/optuna/samplers/_tpe/parzen_estimator.py:193: RuntimeWarning: divide by zero encountered in divide
    coefficient = 1 / z / p_accept

tests/study_tests/test_study.py::test_optimize_parallel_timeout[None--1-inmemory]
tests/study_tests/test_study.py::test_optimize_parallel_timeout[None--1-redis]
tests/study_tests/test_study.py::test_optimize_parallel_timeout[None--1-cached_redis]
  /opt/homebrew/Caskroom/miniconda/base/envs/optuna/lib/python3.8/site-packages/optuna/samplers/_tpe/sampler.py:494: RuntimeWarning: invalid value encountered in subtract
    score = log_l - log_g

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

One hotfix is to increase `sleep_sec` at https://github.com/optuna/optuna/blob/3a646e86fb8a2ca93a5937ac6b667296bf10ee47/tests/study_tests/test_study.py#L185.

**Comment by toshihikoyanase** [comment]
@HideakiImamura Could you review this PR when you have time?

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Review by toshihikoyanase — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
