### PR TITLE
Update pytorch_lightning_distributed.py to remove MNIST and PyTorch Lightning errors

### PR DESCRIPTION
**Pull request by 0x41head**
## Motivation

#2513

## Description of the changes

- Changed from `MNIST` to `FashionMNIST` in `examples/kubernetes/mlflow/pytorch_lightning_distributed.py`
- Changed from `val_percent_check` to  `limit_val_batches` in `examples/kubernetes/mlflow/pytorch_lightning_distributed.py`

### CODE REVIEW

**Review by HideakiImamura — COMMENTED** [review]
Thanks for the fix!

Could you also update the argument `val_percent_check` with `limit_val_batches`?

**Comment by 0x41head** [comment]
The latest commit removes all errors caused by `examples/kubernetes/mlflow/pytorch_lightning_distributed.py`, in the master optuna branch.
Logs :
```
kali@kali:~/Desktop/optuna/examples/kubernetes/mlflow$ kubectl get pod
NAME                  READY   STATUS      RESTARTS   AGE
mlflow-0              1/1     Running     0          14m
postgres-0            1/1     Running     0          14m
study-creator-ltwts   0/1     Completed   0          14m
worker-8rm5v          0/1     Completed   0          14m
worker-hnzpq          0/1     Completed   0          14m


```

**Review by HideakiImamura — APPROVED** [review]
Thanks for your swift actions! LGTM!

**Comment by toshihikoyanase** [comment]
@not522 Could you review this PR if you have time?

**Review by not522 — APPROVED** [review]
Thank you! LGTM!

**Pull request merged**
