### PR TITLE
Add upper version constraint of PyTorchLightning

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Pytorch-Lightning 1.5.0 has been released, but this release contains backwards-incompatible changes as in https://github.com/PyTorchLightning/pytorch-lightning/releases/tag/1.5.0#bc-changes. Due to this change, integration CI is falling now.

## Description of the changes

Add the version constraint of PyTorchLightning not to use `1.5.0` or higher version.

### CODE REVIEW

**Review by himkt — APPROVED** [review]
Thank you for the patch. Looks good as the first aid.

I confirmed `AttributeError: 'Trainer' object has no attribute 'accelerator_connector'` is raised in integration tests.

https://github.com/optuna/optuna/blob/d7e09dc9eb5bb6cc9e7ad83804d47254d7f586ac/optuna/integration/pytorch_lightning.py#L59

> backwards-incompatible changes as in https://github.com/PyTorchLightning/pytorch-lightning/releases/tag/1.5.0#bc-changes

It looks `Trainer.accelerator_connector` is renamed to `Trainer._accelerator_connector`. Is it possible to support the latest pytorch-lightning by switching reference to the connector attribute based on the version of lightning?

https://github.com/PyTorchLightning/pytorch-lightning/compare/1.4.9...1.5.0#diff-667a2513c158c2b01d73b479e4dea75587d8531f9cd286891d34570a2fd145dcR431

**Comment by nzw0301** [comment]
Thank you for your comment and for sharing your investigation! 

> It looks `Trainer.accelerator_connector` is renamed to `Trainer._accelerator_connector`.

It sounds much simpler than expected change! Brilliant!

> Is it possible to support the latest PyTorch-lightning by switching reference to the connector attribute based on the version of lightning?

I suppose so. But I believe that we do not have enough resources to support multiple pytorch-lightning versions and follow frequent drastically break-backwards compatibility by this library. So I propose

- pin pytorch-lightning version in `setup.py` by default 
- pinned version is ideally the latest PyTorch-lightning

**Review by toshihikoyanase — APPROVED** [review]
LGTM. Thank you for your quick fix!

> It looks `Trainer.accelerator_connector` is renamed to `Trainer._accelerator_connector`. Is it possible to support the latest pytorch-lightning by switching reference to the connector attribute based on the version of lightning?

To support the multiple-version of `pytorch-lightning`, I think we need further discussion on the maintenance cost, testability, and etc. Also, we have another choice to pin the pytorch-lightning version by default as @nzw0301 mentioned. 

How about merging this PR and discussing it in a new PR? @himkt

**Comment by toshihikoyanase** [comment]
Talked with @himkt offline. Let me merge this PR.

**Pull request merged**
