### PR TITLE
Apply blackdoc.

### PR DESCRIPTION
**Pull request by keisuke-umezawa**
## Motivation

To format python code in doctest.

## Description of the changes

Applied `blackdoc` of this [PR](https://github.com/optuna/optuna/pull/1817/files) to the files in `optuna`.

## TODO in another PR.
- [ ] Check `blackdoc` in CI after the  [PR](https://github.com/optuna/optuna/pull/1817/files) is merged.
- [ ] Apply `blackdoc` to other files after the [PR](https://github.com/optuna/optuna/pull/1817/files) is merged.

### CODE REVIEW

**Review by HideakiImamura — APPROVED** [review]
Thank you for introducing `blackdoc`! The changes look great to me. Could you merge `master` to resolve the conflict?

**Comment by keisuke-umezawa** [comment]
@HideakiImamura I rebased it against the current master branch.

**Comment by crcrpar** [comment]
could you update branch again, please?

**Review by hvy — APPROVED** [review]
LGTM, thanks a lot!

**Pull request merged**
