### PR TITLE
Remove performance benchmarks

### PR DESCRIPTION
**Pull request by not522**
## Motivation
The performance benchmark scripts are no longer used and are outdated, so this PR removes them.

## Description of the changes
- Remove workflow files of GitHub actions
- Remove benchmark scripts
- Remove benchmarks/README.md
  - This file does not contain the information of the speed benchmark.

### CODE REVIEW

**Comment by eukaryo** [comment]
@HideakiImamura Could you review this PR?

**Review by HideakiImamura — COMMENTED** [review]
Basically LGTM. I think we can remove several dependencies from pyproject.toml. For example, we can remove `botorch` from the `benchmark` optional dependencies.

**Comment by not522** [comment]
Thank you. I've updated this PR according to your comment.

**Review by HideakiImamura — APPROVED** [review]

**Review by eukaryo — APPROVED** [review]
LGTM.

**Pull request merged**
