### PR TITLE
Use `--study-name` instead of `--study` in CLI commands.

### LINKED ISSUE #1059: Use the option`--study-name` instead of ` --study` in all cli commands.
## Motivation

We want to align the option name as `--study-name`, so that we can easily remember the option name.

## Description

Almost all cli commands use the option name `--study-name`, but only the following commands uses `--study`.

- `optuna study set-user-attr`
- `optuna study optimize`
- `optuna study set-user-attr`

We want to align the option name as `--study-name`.

### PR DESCRIPTION
**Pull request by seungjaeryanlee**
**Status: In Progress**

- [x] The parser now accepts `--study-name` instead of `--study` for the following commands:
  - `optuna study set-user-attr`
  - `optuna dashboard`
  - `optuna study optimize`
- [x] Update other parser options
  - In parsers that use `--study-name`, the help says `A human-readable name of a study to distinguish it from others.`, but for parsers that used `--study`, it just says `Study name`.
- [x] Allow `--study` flag with deprecation warning
- [x] Update Sphinx documentation
- [x] Pass coding styles and unit tests (flake8, mypy, black, pytest)

This issue resolves #1059

### CODE REVIEW

**Comment by hvy** [comment]
Thanks for tackling #1059 and being clear about the roadmap in the description. Let us know if you are stuck, it otherwise SGTM.

**Comment by seungjaeryanlee** [comment]
CI is failing because it cannot find `torch==1.4.0+cpu` package. The issue is tracked in #1133 .

**Comment by himkt** [comment]
@seungjaeryanlee Could you please try rebasing this branch?

**Comment by seungjaeryanlee** [comment]
@himkt I have rebased the branch.

**Comment by himkt** [comment]
@seungjaeryanlee Thank you for updating!
CI failing on the wrong dependency configurations has fixed!
(Now, some fails occur in `test_cli.py`)

**Comment by seungjaeryanlee** [comment]
@himkt Oops. I did not notice that the error messages have changed! Thank you. It has been fixed and the PR is ready for review now :)

**Comment by hvy** [comment]
Thanks for the PR. The changes themselves LGTM but I'm a bit worried that just removing the previous arguments will confuse existing users. Is it possible to raise deprecation warnings instead of aborting with an error?

**Comment by seungjaeryanlee** [comment]
@hvy Good idea! I will look into it. Updated the PR description accordingly.

**Comment by hvy** [comment]
Sorry I don't mean to stress but do you have any updates on the deprecation? It'd be great if you'd want to continue. However, let me know if you're busy and maybe I could take over.

**Comment by seungjaeryanlee** [comment]
I have finals this week but I should be able to get back on it this Friday!

**Comment by seungjaeryanlee** [comment]
I have added the deprecation warnings! The PR is ready for review again.

**Pull request merged**
