### PR TITLE
Translate type comments into type annotations using `com2ann`.

### LINKED ISSUE #711: Use function annotation syntax for Type Hints.
After dropping Python 2.7 support at #710, we can define type hints with function annotation syntax. 
~~Do you have a plan to update the coding style guideline?~~
https://github.com/optuna/optuna/wiki/Coding-Style-Conventions

## Progress

- [x] `optuna/integration/sklearn.py` (#1735)
- [x] `optuna/study.py` - assigned to harpy

## Note to the questioner

We still cannot use variable annotation syntax introduced by [PEP 526](https://www.python.org/dev/peps/pep-0526/) because we supports Python 3.5.

### LINKED ISSUE #1445: Use `com2ann` to translate type comments into type annotations
Related to https://github.com/optuna/optuna/issues/711.

I found this python package named `com2ann` which translates type comments into type annotations:

https://github.com/ilevkivskyi/com2ann

I'm testing this package on my local and it seems to be working fine so far. One adjustment that I had to make was prevent `com2ann` from translating type comments on variables into  [variable annotaions](https://www.python.org/dev/peps/pep-0526/) (introduced in Python 3.6) because Optuna still supports Pyhton 3.5. Here's the fixed version which preserves type comments on variables.

https://github.com/harupy/com2ann/tree/disable-variable-annotation

Can I give this a try?

### PR DESCRIPTION
**Pull request by harupy**
## Motivation

Resolves #711
Resolves #1445 

## Description of the changes

- Applied `com2ann` to all the files
- ~Added `from __future__ import annotations` to some files to avoid lint errors~

### CODE REVIEW

**Comment by harupy** [comment]
The conditional imports from the `typing` module cause an error.

```python
if type_checking.TYPE_CHECKING:
    from typing import Any  # NOQA
    ...
```

**Comment by bigbird555** [comment]
I don't know if this will help, but when I was doing it myself, I would either delete `if type_checking.TYPE_CHECKING:` or rewrite `if type_checking.TYPE_CHECKING:` to `with try_import() as _imports:`.

**Comment by harupy** [comment]
@bigbird555 Thanks for the comment! It looks like there are a few imports that should be moved under `with try_import()` (e.g. `from _pytest.recwarn import WarningsRecorder` in `tests/test_study.py`)

**Comment by harupy** [comment]
It seems like we still need to use `TYPE_CHECKING` to prevent circular import...

**Comment by bigbird555** [comment]
Okay.... I'm sorry I couldn't point out that problem.

**Comment by harupy** [comment]
Here are the issues that I found.

1. `TYPE_CHECKING` is still required in some modules to prevent circular import ([ref](https://mypy.readthedocs.io/en/stable/common_issues.html#import-cycles)).
1. The return type of a method that returns a class itself must be a string ([ref](https://stackoverflow.com/questions/33533148/how-do-i-specify-that-the-return-type-of-a-method-is-the-same-as-the-class-itsel)).

```python
class Position:
    ...
    def __add__(self, other: 'Position') -> Position:  # raises an error
    def __add__(self, other: 'Position') -> 'Position':  # works
       ...
```

3. Just removing `if type_checking.TYPE_CHECKING` causes the import-order error. A package like [`isort`](https://github.com/timothycrosley/isort) can fix this issue.

**Comment by HideakiImamura** [comment]
Thanks for your contributions as always! I would appreciate your great efforts and careful considerations. I have several comments.

> 1. TYPE_CHECKING is still required in some modules to prevent circular import.

In my experience, we should make it "string" to prevent circular imports. For example, 
```python
# optuna/pruners/_base.py
...
@abc.abstractmethod
def infer_relative_search_space(
        self, study: "Study", trial: "FrozenTrial"
) -> Dict[str, BaseDistribution]:
...
```

> 3. Just removing if type_checking.TYPE_CHECKING causes the import-order error. A package like isort can fix this issue.

 Thanks for your survey! It sounds great. Could you apply `isort` to order imports?

Additionally, I saw CI results and have noticed that some modules are not used (e.g. `optuna.type_checking` and `typing`). Don't we have to fix them by hand? :(

**Comment by harupy** [comment]
@HideakiImamura Thanks for the comment!

> Thanks for your survey! It sounds great. Could you apply isort to order imports?

I have tried `isort`, but its sorting rules differ from `hacking` we currently use.

> Additionally, I saw CI results and have noticed that some modules are not used (e.g. optuna.type_checking and typing). Don't we have to fix them by hand?

We could do this programmatically using `flake8` output log that tells us which files and lines cause unused-import-error.

**Comment by harupy** [comment]
@HideakiImamura I think we should split this PR into smaller ones (otherwise it could take forever).

**Comment by HideakiImamura** [comment]
@harupy Thanks for your proposal! I agree with your idea, but how do we proceed? I think we have several items, but we need to do them simultaneously to avoid inconsistency.

**Comment by harupy** [comment]
@HideakiImamura 

Does the one-by-one approach @bigbird555 has been doing still make sense?

Because:

- This doesn't seem to be an urgent task
- It's easier to review and debug
- We can minimize conflictions

**Comment by HideakiImamura** [comment]
Hmm... IMO, the one-by-one approach is safe to avoid the inconsistency and any conflict with other PRs. But, using `com2ann` looks a good approach to fix type hinting. I think it is helpful for committers to introduce `com2ann` in PR #711.

**Comment by harupy** [comment]
Yes, I'll write how to install `com2ann` and how to  use it on #711.

**Comment by HideakiImamura** [comment]
Thanks for the comment. I totally agree with you! Could you write to them and close this PR?

**Comment by harupy** [comment]
I briefly described how to install and use `com2ann` in https://github.com/optuna/optuna/issues/711#issuecomment-652414062

**Pull request closed without merging**
