### PR TITLE
Remove SkoptSampler

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Progress https://github.com/optuna/optuna/issues/4484

## Description of the changes
This PR removed all SkoptSampler related files. Note that it is not tested here since deprecated.

### CODE REVIEW

**Review by nabenabe0928 — COMMENTED** [review]
I checked `git grep skopt`, but scikit-optimize is not used in documentation, so scikit-optimize should be able to be removed from the document dependencies as well.

**Review by nabenabe0928 — APPROVED** [review]
LGTM!

**Comment by nabenabe0928** [comment]
@y0z Could you review this PR?

**Review by y0z — APPROVED** [review]
LGTM

**Pull request merged**
