### PR TITLE
Add Coverage for  ChainerMN in codecov

### PR DESCRIPTION
**Pull request by jeromepatel**
## Motivation

With reference to issue #2038 
## Description of the changes

As discussed in the issue,  `--cov-append` should work for the appending coverage to the codecov report. Let me know it needs any modifications. Discussion and suggestions are most welcome.

### CODE REVIEW

**Review by toshihikoyanase — COMMENTED** [review]
Thank you for your PR.

Your change (with my suggestion) improved the coverage of ChainerMN tests as follows:

-|Filename | Stmts | Miss | Cover | Missing
 -- | -- | -- | -- | -- | --
before | integration/chainermn.py | 169 | 26 | 84.62% | 83-84, 91, 116-133, 141, 182-187, 261-266, 324-327
after | integration/chainermn.py | 169 | 11 | 93.49% | 83-84, 141, 182-187, 261-266

**Comment by jeromepatel** [comment]
@toshihikoyanase Sorry, I hadn't checked the coverage previously. Thank you for your review and suggestion. PTAL.

**Review by toshihikoyanase — APPROVED** [review]
Thank you for your update. LGTM!

**Comment by toshihikoyanase** [comment]
@hvy Could you review this PR since this resolves your issue (#2038)?

**Review by hvy — APPROVED** [review]
Looks great. Thanks for all the investigations, LGTM!

**Pull request merged**
