### PR TITLE
Trial suggest for same variable with different parameters should give error or raise exceptoion

### PR DESCRIPTION
**Pull request by PhilipMay**
PR for  #797 

PR is not completed yet.

### CODE REVIEW

**Comment by PhilipMay** [comment]
@sile Could you please review and help me to fix the type problem that still fails the checks?
Thanks
Philip

**Comment by sile** [comment]
Thanks @PhilipMay! I'll take a look.
BTW, [a CI check](https://circleci.com/gh/optuna/optuna/26639?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) seems failed due to a minor formatting issue (PEP 8).

**Comment by PhilipMay** [comment]
> [The CI check](https://circleci.com/gh/optuna/optuna/26639?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) seems failed due to a minor formatting issue (PEP 8). I think you could fix the problem by executing `$ autopep8 . -r -i` at the root directory of optuna.

Fixed.

**Comment by PhilipMay** [comment]
Now we have a static type checking issue I need help with: https://circleci.com/gh/optuna/optuna/26710?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by sile** [comment]
Sorry, I'm busy today. I'll check the new CI problem and review your code later.

**Comment by hvy** [comment]
The CI fails because the type checker needs to, but cannot, know the concrete types of the distributions to verify that the `high` and `low` attributes are available. You can fix it by e.g. introducing assertions `hasattr(dist, 'high')`, etc. or `assert isinstance(dist, SomeHighLowDistribution)`, etc. before the attributes are accessed.

I believe you could do something along the following (given the fact that we already have a `DISTRIBUTION_CLASSES`)?

```python
...
_RANGED_DISTRIBUTION_CLASSES = (
    UniformDistribution,
    LogUniformDistribution,
    DiscreteUniformDistribution,
    IntUniformDistribution,
)


DISTRIBUTION_CLASSES = _RANGED_DISTRIBUTION_CLASSES + (CategoricalDistribution,)
...
    if ((param_name is not None) and
            isinstance(dist_old, _RANGED_DISTRIBUTION_CLASSES) and
            isinstance(dist_new, _RANGED_DISTRIBUTION_CLASSES) and
            ((dist_old.high != dist_new.high) or (dist_old.low != dist_new.low))):
        ...
```

**Comment by PhilipMay** [comment]
> The CI fails because the type checker needs to, but cannot, know the concrete types of the distributions to verify that the `high` and `low` attributes are available. You can fix it by e.g. introducing assertions `hasattr(dist, 'high')`, etc. or `assert isinstance(dist, SomeHighLowDistribution)`, etc. before the attributes are accessed.

Well, `hasattr(dist, 'high')` does not seem to work.

**Comment by hvy** [comment]
Oh, sorry then you could check the type.

**Comment by sile** [comment]
Hi @PhilipMay 

To confirm the behavior of this PR, I wrote the following simple example code:
```python
import optuna

def objective(trial):
    return trial.suggest_uniform('x', 0, trial.number)

study = optuna.create_study()
study.optimize(objective, n_trials=3)
```

When I run the example, it emits the warning message introduced by this PR on each trial:

```console
[I 2020-02-04 14:14:04,065] Finished trial#0 resulted in value: 0.0. Current best value is 0.0 with parameters: {'x': 0}.
/d/dev/pfn/optuna/optuna/distributions.py:398: RuntimeWarning:

Inconsistent min and max values for parameter x! This might be a configuration mistake. current min: 0 old min: 0 current max: 1 old max: 0

[I 2020-02-04 14:14:04,109] Finished trial#1 resulted in value: 0.40984342476481395. Current best value is 0.0 with parameters:{'x': 0}.
/d/dev/pfn/optuna/optuna/distributions.py:398: RuntimeWarning:

Inconsistent min and max values for parameter x! This might be a configuration mistake. current min: 0 old min: 0 current max: 2 old max: 1

[I 2020-02-04 14:14:04,153] Finished trial#2 resulted in value: 1.140151559318335. Current best value is 0.0 with parameters: {'x': 0}.
```

I think that it's not expected behavior because Optuna allows using different distribution ranges of a parameter for each trial (except for categorical distribution).

I'm not sure but I guess the above warnings are emitted by `InMemoryStorage` ([in_memory.py#R209](https://github.com/optuna/optuna/pull/867/files#diff-46168c0a83ae53f417c054ba49358ec2R209)).
The storage layer has to check the **study-level** compatibility of a parameter distribution, but the aim of this PR is modifying **trial-level** compatibility check. The requirements of both checks are similar but slightly different, so how about split the `check_distribution_compatibility` function for study-level and trial-level?

**Comment by PhilipMay** [comment]
I see what you mean.

**Comment by PhilipMay** [comment]
Closing this because improvement (trial level check) is here with a new PR: #908

**Pull request closed without merging**
