### PR TITLE
Support infeasible coloring for plot_timeline

### PR DESCRIPTION
**Pull request by nabenabe0928**
## Motivation

This PR is to address [issue#4834](https://github.com/optuna/optuna/issues/4834).
Currently, we cannot see the difference between feasible and infeasible trials in `plot_timeline`, but we add functionality to differentiate the color for them.

## Description of the changes

I made the following changes:
1. Differentiate the color for infeasible trials in the timeline plot, and
2. Make the color of infeasible trial `#CCCCCC`.

### CODE REVIEW

**Comment by c-bata** [comment]
@eukaryo @gen740 Could you review this PR?

**Review by gen740 — COMMENTED** [review]
Almost LGTM! I left a minor comment.
スクリーンショット 2023-10-11 18 33 14
(c.f. https://optuna.readthedocs.io/en/stable/faq.html#how-can-i-optimize-a-model-with-some-constraints)

**Review by gen740 — APPROVED** [review]
LGTM!

**Review by eukaryo — APPROVED** [review]
LGTM!
figure
```
import time

import matplotlib.pyplot as plt

import optuna


def objective(trial):
    time.sleep(0.1)

    x = trial.suggest_float("x", -5, 5)
    y = trial.suggest_float("y", -5, 5)

    c0 = 3 - (x**2 + y**2)
    trial.set_user_attr("constraint", (c0,))

    if int(x * 10000) % 2 == 0:
        raise optuna.TrialPruned()

    v0 = x**2 + y**2
    return v0


def constraints(trial):
    return trial.user_attrs["constraint"]


sampler = optuna.samplers.TPESampler(constraints_func=constraints, seed=12345)
study = optuna.create_study(
    direction="minimize",
    sampler=sampler,
)
study.optimize(objective, n_trials=50)
a = optuna.visualization.matplotlib.plot_timeline(study)
plt.savefig("figure.png")

```

**Pull request merged**
