### PR TITLE
Fixing annotations for `distributions.py`

### PR DESCRIPTION
**Pull request by KannanShilen**
## Motivation
Hi! I am a new software developer trying to get started on working with open source projects, mainly to understand larger projects and to improve my knowledge of git and coding in general. This is my first attempt working with an open source project, and I am hoping it could be a great learning experience. 

## Description of the changes
Looking at some of the previous pull requests on how to fix the annotations, I tried to implement the fixes similarly. Although, I am not sure if I did implement these correctly. I would greatly appreciate it if you could help me if I did make any mistakes. Thanks!

### CODE REVIEW

**Comment by nzw0301** [comment]
Thanks. Could you remove `Union`?

**Comment by KannanShilen** [comment]
On the original issue, there was this - "Now(2024/07/17), Optuna supports Python 3.8. In Python 3.8, you cannot use '|' when defining types, you need to use typing.Union. Therefore, as long as we continue to support Python 3.8, we cannot completely eliminate typing.Union. Please note that type annotations, not type definitions, can be rewritten without any problem." 
So I thought I should keep Union for line 18 on the file. Is it okay to remove it?

**Comment by nzw0301** [comment]
Thank you for the clarification. You're mentioning https://github.com/optuna/optuna/issues/4508#issue-1618867973.

**Review by not522 — APPROVED** [review]
LGTM!

**Pull request merged**
