### PR TITLE
 Allow display names to be changed in benchmark scripts (Issue #4017)

### PR DESCRIPTION
**Pull request by eukaryo**
## Motivation

cf. [issues/4017](https://github.com/optuna/optuna/issues/4017)

## Description of the changes

- support custom display names by argparse in the benchmark scripts
- reflect that argument to GitHub Action's config files

This PR does not add both `--sampler-name-list` and `--pruner-name-list` options yet, which is suggested in (https://github.com/optuna/optuna/issues/4017#issuecomment-1269576109)

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
@knshnb @HideakiImamura This is related to https://github.com/optuna/optuna/issues/4017. Could you review this PR, please.

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by eukaryo** [comment]
I made changes to reflect the recent comment in Issue ( https://github.com/optuna/optuna/issues/4017#issuecomment-1306679821 ).
Additionally, I added validation for argument length that was missing only for `run_bayesmark.py`.
https://github.com/eukaryo/optuna/blob/5d72be043421109756521afab39815c31d242ce1/benchmarks/run_bayesmark.py#L28-L38

**Comment by eukaryo** [comment]
I made changes to assign an unique id number as a suffix to each sampler and pruner that appears multiple times.
Example input:
samplers: `["TPESampler", "TPESampler", "RandomSampler"]` , pruners: `["NopPruner", "NopPruner"]`
Example output:
`["TPESampler-0-NopPruner-0", "TPESampler-0-NopPruner-1", "TPESampler-1-NopPruner-0", "TPESampler-1-NopPruner-1", "RandomSampler-NopPruner-0", "RandomSampler-NopPruner-1"]`

**Review by knshnb — APPROVED** [review]
Thanks for the PR. The code looks great! Let me merge this PR.

**Pull request merged**
