### PR TITLE
Embed `plot_edf` figure in documentation by using matplotlib plot directive

### PR DESCRIPTION
**Pull request by harupy**
## Motivation

Embed the EDF plot figure in the documentation by using [the plot directive](https://matplotlib.org/3.1.3/devel/plot_directive.html).

## Description of the changes

- Edit `docs/source/conf.py` to enable the plot directive
- Add example code to `optuna.visualization.matplotlib.plot_edf`

### CODE REVIEW

**Comment by harupy** [comment]
## Result:

Screen Shot 2020-10-06 at 18 45 36

https://60191-122299416-gh.circle-artifacts.com/0/docs/build/html/reference/visualization/generated/optuna.visualization.matplotlib.plot_edf.html#optuna.visualization.matplotlib.plot_edf

**Comment by harupy** [comment]
cc @ytknzw

**Review by crcrpar — COMMENTED** [review]
The change itself looks awesome.

One thing in my mind is when to merge this pull request as there are running pull requests that implement matplotlib counterparts of the visualization module which is mainly implemented with plotly.

Let me know what you and other reviewers think 🙂

**Review by crcrpar — APPROVED** [review]
That makes sense 👍

**Review by HideakiImamura — COMMENTED** [review]
Thanks for the PR! The added change looks good to me.

A nit:
In this PR, the order of "Example" is "Args -> Returns -> Example". But, that of `optuna.visualization.plot_edf` is "Example -> Args -> Returns". Could you get this PR aligned with `optuna.visualization.plot_edf`?

**Comment by harupy** [comment]
@HideakiImamura done!

**Review by HideakiImamura — APPROVED** [review]
Thanks for your swift action! LGTM!

As a follow-up task, should we add examples to other functions of `optuna.visualization.matpolotlib`? @harupy Are you interested in this task?

**Pull request merged**
