### PR TITLE
Remove `tensorflow` integration

### PR DESCRIPTION
**Pull request by gen740**
- ## Motivation
Progress optuna/optuna#4484

## Description of the changes
- Move `integration/tensorflow.py` and its test from `optuna/optuna`.

### CODE REVIEW

**Review by Alnusjaponica — COMMENTED** [review]
It seems dependency on `tensorflow-datasets` can be removed too.

**Comment by HideakiImamura** [comment]
LGTM except @Alnusjaponica's comment.

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by HideakiImamura** [comment]
@Alnusjaponica Could you review this PR?

**Review by Alnusjaponica — CHANGES_REQUESTED** [review]
You will remove the following two lines:
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/.github/workflows/tests-integration.yml#L89
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/.github/workflows/tests-integration.yml#L112

**Comment by Alnusjaponica** [comment]
Other than the changes mentioned above, LGTM.

**Review by Alnusjaponica — APPROVED** [review]
LGTM. 
@HideakiImamura Could you merge this PR?

**Comment by toshihikoyanase** [comment]
This PR got two approvals. Let me merge it.

**Pull request merged**
