### PR TITLE
Add some tests for visualization functions.

### PR DESCRIPTION
**Pull request by c-bata**
## Motivation

I added some test cases that were discovered by `optuna-visualization-regression-tests`.
https://optuna.github.io/optuna-visualization-regression-tests/

## Description of the changes

This PR adds a test case for visualization functions. Without `pytest.xfail`, this test case is broken as shown below:

```
$ pytest tests/visualization_tests/test_visualizations.py 
...
=================================================================================================== short test summary info ===================================================================================================
FAILED tests/visualization_tests/test_visualizations.py::test_visualization_with_dynamic_search_space[objective_single_dynamic_with_categorical-plot_contour0] - IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
FAILED tests/visualization_tests/test_visualizations.py::test_visualization_with_dynamic_search_space[objective_single_none_categorical-plot_rank1] - TypeError: 'value' must be an instance of str or bytes, not a None
```

### CODE REVIEW

**Comment by not522** [comment]
@eukaryo Could you review this PR?

**Comment by not522** [comment]
Thank you. It's almost LGTM.
The test outputs the following warning. How about adding `plt.close()` at the end of the test?

```
More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
```

**Comment by c-bata** [comment]
@not522 That sounds good. I addressed it in e716be7.

**Review by not522 — APPROVED** [review]
LGTM!

**Review by eukaryo — APPROVED** [review]
LGTM

**Pull request merged**
