### PR TITLE
Add Python 3.11 to integration CI

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Resolve the subtask https://github.com/optuna/optuna/issues/3964.

## Description of the changes

- Run pytest for 
    - `cma`
    -  `chainer/chainermn`
    -  `sklearn`
    - `dask`
    - `wandb`
    - `xgboost`
, which work with Python 3.11 https://github.com/optuna/optuna/issues/3964#issuecomment-1366092629 
- Skip the others' pytests

### CODE REVIEW

**Comment by nzw0301** [comment]
Could someone re-run CI jobs later? Supposedly, github CI has been unstable for a few according to its log https://github.com/optuna/optuna/actions/workflows/tests-integration.yml.

**Comment by nzw0301** [comment]
The failed ci job was an unrelated docker's task. So at least integration CI jobs were happy with the changes in this PR.

**Review by not522 — APPROVED** [review]
Thank you! CI passed after re-running. LGTM!

**Comment by c-bata** [comment]
@HideakiImamura Could you review this PR if you have time?

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
