### PR TITLE
Fix mypy error abut `AllenNLP` in Checks (integration)

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Solve scheduled Checks (Integration) failure

## Description of the changes
Currently, scheduled Checks (Integration) fails die to mypy check with `--warn-unused-ignores` option. This PR removes a part of the cause related to `AllenNLP`.
Although test for  Checks (Integration) does't run when PR in opened, I confirmed this PR together with other "Fix mypy error" series reduces mypy error at [CI on my fork](https://github.com/Alnusjaponica/optuna/pull/3).

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@eukaryo @contramundum53  Could you review this PR?

**Comment by contramundum53** [comment]
@Alnusjaponica Seems that the CI is failing in your repo 😥

**Comment by Alnusjaponica** [comment]
The failure in the CI is only due to Pytorch Lightning version, which not aimed to solve in this PR. Other errors are fixed. The problem is discussed in #3418 and #4116 and I am currently working on it as another task. @contramundum53

**Comment by contramundum53** [comment]
Adding this many specific `type:ignore`s is, in my opinion, too fragile to maintain. How about simply ignoring this file in Checks (Integration)?

**Comment by Alnusjaponica** [comment]
Thank you for the comments. I see your point.
To be specific, the mypy error about `AllenNLP` is caused by `__init__.py` in `AllenNLP`. Since `AllenNLP` is already archived, there is no way to re-activate mypy test for these files. 
I am not sure which of adding `type: ignore`s or skipping mypy check (permanently) is better. What do you think about that? @contramundum53 @HideakiImamura

**Comment by contramundum53** [comment]
I think we could alternatively use file-level `# type:ignore`.
https://github.com/python/mypy/issues/964

**Comment by Alnusjaponica** [comment]
As discussed offline, we decided to solve mypy error by adding `type:ignore`s. This is because excluding `optuna/integration/allennlp/_pruner.py` and `tests/integration_tests/allennlp_tests/test_allennlp.py` ends up adding `type:ignore` in `integration/__init__.py` which imports classes from `integration/allennlp/`.

**Comment by Alnusjaponica** [comment]
Adding changes in #4322, I confirmed that all mypy test in `Checks (integration)` passes. See following [CI on my fork](https://github.com/Alnusjaponica/optuna/pull/3). 
Although `Tests (MPI)` failed in the fork, this test has already failed on the master branch. Therefore, the cause should lie somewhere independent of this change.

**Comment by Alnusjaponica** [comment]
`Tests (MPI)` failure is fixed in #4344 and now that all tests pass in [CI on my fork](https://github.com/Alnusjaponica/optuna/pull/3). Could you review this PR again?
@codecov-commenter @eukaryo

**Comment by contramundum53** [comment]
Still not clear :cry:
image

**Comment by Alnusjaponica** [comment]
Could you provide the link to the result?

**Comment by contramundum53** [comment]
https://github.com/Alnusjaponica/optuna/actions/runs/3956056821/jobs/6774893552
Here it is.

**Comment by Alnusjaponica** [comment]
I afraid that the test result doesn't seem to be related to this PR. Please refer to the latest test results on branch `confirm-checks-integration` not `master`. For more detail see [this PR](https://github.com/Alnusjaponica/optuna/pull/3)

**Comment by contramundum53** [comment]
I see, https://github.com/Alnusjaponica/optuna/actions/runs/3955099642/jobs/6773082452 is your results.

**Review by contramundum53 — APPROVED** [review]
LGTM.

**Comment by Alnusjaponica** [comment]
@contramundum53 Thank you for your approval.
@eukaryo Could you take another look?

**Comment by eukaryo** [comment]
LGTM !

**Pull request merged**
