### PR TITLE
Use inline code rather than italic for `step`

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Docsting improvement.

## Description of the changes

As written in the PR title.

### CODE REVIEW

**Comment by y0z** [comment]
Could you please merge the latest master into this branch to resolve the CI errors?

**Review by y0z — APPROVED** [review]
LGTM

**Comment by y0z** [comment]
@kAIto47802 Could you review this PR?

**Review by kAIto47802 — APPROVED** [review]
LGTM!

**Pull request merged**
