### PR TITLE
Simplify annotations in `optuna/pruners/_hyperband.py`

### PR DESCRIPTION
**Pull request by keita-sa**
## Motivation
I've updated the notation of `Optional`, also added `collections.abc.Container`. Applied `black`, `isort`.

To resolve #4508.

## Description of the changes
Added:
`__future__.annotations`
`collections.abc.Container`

Deleted:
`typing.List`
`typing.Union`
`typing.Optional`
`typing.Container`

### CODE REVIEW

**Comment by keita-sa** [comment]
Finally, **Checks / checks** have passed, phew. If the commit in the changed files looks OK, could you please merge it? I appreciate your guidance so far. @nzw0301

**Review by nzw0301 — APPROVED** [review]
LGTM. Could you add a link to https://github.com/optuna/optuna/issues/4508 in the pull request description? Please do not close this pull request as you did repeatedly.

**Comment by keita-sa** [comment]
Do you mean I need to edit to add the link (#4508) in the Motivation section of the pull request above? ↑

**Comment by eukaryo** [comment]
Thank you for your contribution and for updating the PR description! This makes it easier for us to track the progress related to [#4508](https://github.com/optuna/optuna/issues/4508).

@nabenabe0928 Could you review this PR?

**Review by eukaryo — APPROVED** [review]
LGTM

**Pull request merged**
