### PR TITLE
Refactor pruners_test

### PR DESCRIPTION
**Pull request by tsumli**
## Motivation
refactor test files in in https://github.com/optuna/optuna/issues/2645
## Description of the changes
Use should_prune and the ask-and-tell interface.

### CODE REVIEW

**Comment by hvy** [comment]
Thanks @tsumli for tackling the issue!

@Crissman , @keisuke-umezawa could you have a look at this PR?

**Comment by hvy** [comment]
Seems like there are some CI failures. I think those can be addressed without a review.

**Review by Crissman — APPROVED** [review]
Much cleaner. Thanks for the refactor!

**Review by keisuke-umezawa — APPROVED** [review]
LGTM! Thank you for all of your contributions!

**Pull request merged**
