### PR TITLE
Add share_optimizer option on CmaEsSampler

### LINKED ISSUE #1775: Cannot store CMA object on PostgreSQL and MySQL.
## Problem details

This bug is reported by @maartenpants on gitter. Original report is here:

> Hi there, has anyone else experienced this issue with CmaEsSampler and the PostgreSQL storage backend:
> ```
> (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(2048)
> [SQL: INSERT INTO trial_system_attributes (trial_id, key, value_json) VALUES (%(trial_id)s, %(key)s, %(value_json)s) RETURNING trial_system_attributes.trial_system_attribute_id]
> ```
> It seems the serialized version of the CMA class is too large to fit in the 2048 character column. This code is the culprit:
> ```
> optimizer_str = pickle.dumps(optimizer).hex()
> study._storage.set_trial_system_attr(trial._trial_id, "cma:optimizer", optimizer_str)
> ```

https://gitter.im/optuna/optuna?at=5f484dea36e6f709fd08a5fa

I checked the length of serialized CMA object.

```python
import pickle

import numpy as np
from cmaes import CMA


def get_cma_object_size(dim: int) -> int:
    optimizer = CMA(mean=np.zeros(dim), sigma=1.3)
    optimizer_str = pickle.dumps(optimizer).hex()
    return len(optimizer_str)


if __name__ == '__main__':
    for i in range(2, 32, 2):
        print(f"dim={i} size={get_cma_object_size(i)}")
```

```
$ python examples/cma_size.py 
dim=2 size=2516
dim=4 size=2916
dim=6 size=3364
dim=8 size=3850
dim=10 size=4442
dim=12 size=5018
dim=14 size=5738
dim=16 size=6378
dim=18 size=7194
dim=20 size=8074
dim=22 size=8906
dim=24 size=9916
dim=26 size=10956
dim=28 size=12092
dim=30 size=13148
```

This result means that the bug is raised even on low-dimensional search space.

## Additional context (optional)

I've ever tested on SQLite3 but never bumped into this bug. The reason why is:

> (9) What is the maximum size of a VARCHAR in SQLite?
> SQLite does not enforce the length of a VARCHAR. You can declare a VARCHAR(10) and SQLite will be happy to store a 500-million character string there. And it will keep all 500-million characters intact. Your content is never truncated. SQLite understands the column type of "VARCHAR(N)" to be the same as "TEXT", regardless of the value of N.
> https://www.sqlite.org/faq.html#:~:text=(9)%20What%20is%20the%20maximum,all%20500%2Dmillion%20characters%20intact.

### PR DESCRIPTION
**Pull request by c-bata**
## Motivation

fix #1775 

## Description of the changes

* Add `share_optimizer` option which enables to store CMA object in system_attrs (default: False).
* Add `randomize_x0` option to sample initial starting points randomly.

###  Which ones should be set as a default argument, `share_optimizer=False` or `share_optimizer=True`?

* Set `share_optimizer=False` from the next release: Existing users may be confused by this breaking change. From the next release, CmaEsSampler cannot resume optimizations.
* Set `share_optimizer=True` until v3.0.0 release: It keeps current behavior. New users may be confused because this option does not work with PostgreSQL and MySQL.

### CODE REVIEW

**Comment by maartenpants** [comment]
@HideakiImamura Thanks for this! Is there an easy way for me to install this version locally to verify that it fixes the issue?

**Comment by HideakiImamura** [comment]
@maartenpants You can install this version from the @c-bata's specific branch by `pip install git+ssh://git@github.com/c-bata/optuna.git@cmaes-non-sharing-optimizer`

**Comment by maartenpants** [comment]
@c-bata We just encountered the same error again while running with this branch.

```
[I 2020-09-11 10:35:12,599] Trial 12 pruned. Trial was pruned at epoch 145.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(2048)

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 1104, in _commit
    session.commit()
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2577, in _flush
    flush_context.execute()
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1137, in _emit_insert_statements
    statement, params
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError
: 
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(2048)
[SQL: INSERT INTO trial_system_attributes (trial_id, key, value_json) VALUES (%(trial_id)s, %(key)s, %(value_json)s) RETURNING trial_system_attributes.trial_system_attribute_id]
[parameters: {'trial_id': 192, 'key': 'cma:optimizer', 'value_json': '"800363636d6165732e5f636d610a434d410a7100298171017d71022858060000005f6e5f64696d71034b0458080000005f706f7073697a6571044b0858030000005f6d7571054b045807 ... (3224 characters truncated) ... 002e000000000000002f0000000000000030000000000000003100000000000000320000000000000071667471676258080000005f657073696c6f6e7168473e45798ee2308c3a75622e"'}]
```

**Comment by maartenpants** [comment]
It only seems to occur after many epochs. CC @HideakiImamura

**Comment by c-bata** [comment]
Hi @maartenpants! Thank you for checking this branch.
You need to pass a `share_optimizer=False` argument to CmaEsSampler like:

```python
study = optuna.create_study(
    storage=...,
    sampler=optuna.samplers.CmaEsSampler(share_optimizer=False),
)
```

**Comment by maartenpants** [comment]
@c-bata Ah! Thanks

**Comment by maartenpants** [comment]
Will this have any effect on the sampling process?

**Comment by c-bata** [comment]
> Will this have any effect on the sampling process? We're running with 4 "workers" to speed up the optimization.

Yes.
Each workers cannot share a CMA optimizer object and solutions if passing `share_optimizer=False`.
So it may lead to the performance degradation on unimodal functions and may lead to the performance improvement on multimodal functions.

**Comment by c-bata** [comment]
I opened https://github.com/optuna/optuna/pull/1833 for alternative approach. It has no effects on the sampling process.

**Pull request closed without merging**
