### PR TITLE
Remove skopt

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Progress https://github.com/optuna/optuna/issues/4484 and https://github.com/optuna/optuna/issues/4789. 

## Description of the changes
Remove `SkoptSampler` related test.
Note that `SkoptSampler` is highly not recommended and will remove in the next major version. Therefore, removing test and stopping supporting `SkoptSampler` to bump up numpy version will be reasonable.

### CODE REVIEW

**Review by c-bata — COMMENTED** [review]
Looks almost good to me. I left one suggestion though.

> wrap other optimization libraries to integrate them into Optuna pipelines (e.g., [SkoptSampler](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.SkoptSampler.html#optuna.integration.SkoptSampler)).
> https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/005_user_defined_sampler.html

How about replacing `SkoptSampler` with `BoTorchSampler`?

**Comment by c-bata** [comment]
@eukaryo Could you review this PR?

**Comment by Alnusjaponica** [comment]
> Looks almost good to me. I left one suggestion though.
> 
> > wrap other optimization libraries to integrate them into Optuna pipelines (e.g., [SkoptSampler](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.SkoptSampler.html#optuna.integration.SkoptSampler)).
> > https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/005_user_defined_sampler.html
> 
> How about replacing `SkoptSampler` with `BoTorchSampler`?

Thank you for the suggestion. I updated applied it.

**Review by c-bata — APPROVED** [review]
LGTM!

**Comment by Alnusjaponica** [comment]
@c-bata Thanks for your approval. 
@eukaryo Could you take another look?

**Review by eukaryo — APPROVED** [review]
LGTM too!

**Pull request merged**
