### PR TITLE
Updated-github-actions

### PR DESCRIPTION
**Pull request by HarshitNagpal29**
## Description of the changes
I have updated actions/checkout to v4 and actions/setup-python to v5 as mentioned in (https://github.com/optuna/optuna/issues/5242)

### CODE REVIEW

**Comment by HarshitNagpal29** [comment]
@Alnusjaponica @HideakiImamura Sir, please review it once and please suggest any changes needed.

**Comment by Alnusjaponica** [comment]
Thanks for your PR. Could you please explain if there are any side effects on the current CI from the actions' changes?

**Comment by Alnusjaponica** [comment]
Thanks for your PR. 
Could you please explain how these changes affect the current CI (i.e., if there are any side effects to be concerned about), based on the actions' change logs?

**Comment by HarshitNagpal29** [comment]
Hi @Alnusjaponica Sir,

Thank you for your feedback. Here's a breakdown of potential side effects for the updates to actions/checkout and actions/setup-python:

### actions/checkout@v3 to actions/checkout@v4:

#### Potential Side Effects:

1. **Default Branch Checkout Behavior:**
   - In v4, checkout defaults to the entire repository rather than just the main branch. Specify the branch using ref if needed.
  
2. **Path to Repository Content:**
   - The path to the repository content changed from $GITHUB_WORKSPACE to $GITHUB_REPOSITORY. Update scripts that rely on absolute paths.
  
3. **Environment Variables:**
   - Some environment variables are no longer set by default, including GITHUB_REF and GITHUB_SHA. Access them explicitly if needed.

### actions/setup-python@v4 to actions/setup-python@v5:

#### Potential Side Effects:

1. **Python Version Specification:**
   - v5 requires explicit Python version specification either through python-version input or a .python-version file. Failing to do so may lead to unexpected results.

2. **Caching Behavior:**
   - Caching behavior has changed slightly. Refer to the changelog for details and adjust caching configurations if necessary.
  
3. **Removed Features:**
   - Some deprecated features like build-cache have been removed. Update workflows using them.

Please let me know if you have any specific concerns or if further clarification is needed.

Best regards,
Harshit Nagpal

**Comment by HarshitNagpal29** [comment]
@HideakiImamura Sir, i am really very sorry for not providing the details properly in my previous response, I am new to open source community, I provided those details by reading some information on reddit and bunch of other websites which I am not sure how much information is actually true, that's why you might feel my response is kind of incomplete. 

Here is the link to official changelogs regarding actions/checkout: https://github.com/actions/checkout/compare/v3...v4.0.0

Summary:

Node12 was deleted from the runner, and Node20 was added to Actions Runner on v2.308.0.The default runtime for actions/checkout was updated to node20.

It also introduces a new option show-progress that, when set to false in the workflow step, causes git fetch to run without the --progress flag.The default value of this new option is true, aligning with the current behavior. Therefore, this introduces no behavior change unless the new option is explicitly set to false.

Here is the link to official changelogs regarding actions/setup-python: https://github.com/actions/setup-python/releases

Summary:

 This doesn't have lot of changes its just that The update brings improvements and enhancements to the setup process, providing a more streamlined and efficient experience for users.

Again I really sorry for any inconvenience caused. Please review it once and please tell if anything further i can provide.

**Comment by HarshitNagpal29** [comment]
> @HideakiImamura Sir, i am really very sorry for not providing the details properly in my previous response, I am new to open source community, I provided those details by reading some information on reddit and bunch of other websites which I am not sure how much information is actually true, that's why you might feel my response is kind of incomplete.
> 
> Here is the link to official changelogs regarding actions/checkout: [actions/checkout@v3...v4.0.0](https://github.com/actions/checkout/compare/v3...v4.0.0)
> 
> Summary:
> 
> Node12 was deleted from the runner, and Node20 was added to Actions Runner on v2.308.0.The default runtime for actions/checkout was updated to node20.
> 
> It also introduces a new option show-progress that, when set to false in the workflow step, causes git fetch to run without the --progress flag.The default value of this new option is true, aligning with the current behavior. Therefore, this introduces no behavior change unless the new option is explicitly set to false.
> 
> Here is the link to official changelogs regarding actions/setup-python: https://github.com/actions/setup-python/releases
> 
> Summary:
> 
> This doesn't have lot of changes its just that The update brings improvements and enhancements to the setup process, providing a more streamlined and efficient experience for users.
> 
> Again I really apologise for any inconvenience caused. Please review it once and please tell if anything further i can provide.

@HideakiImamura Sir can you please review it once, and tell if anything else is required. Thank you.

**Comment by HideakiImamura** [comment]
Could you try to the followings described in the original issue https://github.com/optuna/optuna/issues/5242?
- List up all the files in optuna/ repositories which need updating,
- Carefully examine the change logs of GitHub Actions and describe how updates effects on current CI,

**Pull request closed without merging**
