### PR TITLE
TST: Added unit tests for optimization history of matplotlib tests

### PR DESCRIPTION
**Pull request by 01-vyom**
## Motivation

Added more test cases to `optuna/visualization/matplotlib/test_optimization_history.py`
xref #2643 
## Description of the changes

- Checked number of lines
- Checked title of figure
- Checked data values

### CODE REVIEW

**Comment by nzw0301** [comment]
Could you merge the master branch into your branch to fix the error of `Checks`?

**Comment by hvy** [comment]
@nzw0301, @Crissman could you have a look at this PR?

**Review by nzw0301 — APPROVED** [review]
LGTM! Thank you for your pull request.

**Review by Crissman — APPROVED** [review]
LGTM. Merging!

**Pull request merged**
