### PR TITLE
Make file names in testing consistent with optuna module

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

As a followup of https://github.com/optuna/optuna/pull/3638 commented by https://github.com/optuna/optuna/pull/3638#discussion_r890159623, this PR replaces singular forms of test file names in `optuna.testing` with plural forms for consistency with Optuna's code base.

### CODE REVIEW

**Comment by nzw0301** [comment]
The CI error might come from the third-party package as described in https://github.com/Lyken17/pytorch-OpCounter/pull/175. Hotfix will be adding `onnx` to `document` section of `setup.py`.

**Comment by c-bata** [comment]
@keisuke-umezawa @HideakiImamura Could you review this PR?

**Comment by c-bata** [comment]
@nzw0301 I've just merged #3658. Could you rebase or merge master branch?

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
