### PR TITLE
Add a new section explaing how to customize figures

### LINKED ISSUE #5178: Add documentation for customizing visualization function output
### What is an issue?

Optuna's visualisation functions return editable objects. But it's not well documented. It would be good to have a description in [the visualization tutorial](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/005_visualization.html). (ref #4613)

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Resolve #5178

## Description of the changes

Add a new section to clarify the methods that return editable objects and a simple example to replace titles of `plot_intermediate_values`.

### CODE REVIEW

**Comment by nzw0301** [comment]
The link to the corresponding page section is 
https://optuna--5194.org.readthedocs.build/en/5194/tutorial/10_key_features/005_visualization.html#customize-generated-figures.

**Comment by HideakiImamura** [comment]
How about adding the link to the document of Plotly?

https://plotly.com/python-api-reference/generated/plotly.graph_objects.Figure.html

In addition, I think it would be great to add an example for Matplotlib. Could you add that?

**Comment by nzw0301** [comment]
Thank you for your feedback. Sure I'll update this PR in a few days.

**Comment by HideakiImamura** [comment]
Hi @nzw0301. Is this PR ready for review?

**Comment by nzw0301** [comment]
@HideakiImamura Yes! https://github.com/optuna/optuna/pull/5194/commits/19121aa80da6ecccd3f0dd6a63f57bcea4be10c9 includes your suggestion.

**Comment by nzw0301** [comment]
Sorry, I realised that plotly's link is broken, concretely, the generated link is https://plotly.com/python-api-reference/generated/plotly.graph_objs.Figure.html#id0 which is not found. Note that this broken link problem also happens in pages of `optuna.visualization`. I'll fix the link for this tutorial.

**Comment by nzw0301** [comment]
`plotly.graph_objs.Figure` has been a legacy package since Jul. 2019 or Plotly v4 release. Note that the current 
 major version is 5. According to [Version 4 Migration Guide from Version 3](https://plotly.com/python/v4-migration/), 
`graph_objects` seems right module. 

> ## import from `graph_objects` instead of `graph_objs`
> The legacy `plotly.graph_objs` package has been aliased as `plotly.graph_objects` because the latter is much easier to communicate verbally. The `plotly.graph_objs` package is still available for backward compatibility.

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
