### PR TITLE
Update URLs to `optuna-examples`

### PR DESCRIPTION
**Pull request by hvy**
## Motivation

Addresses https://github.com/optuna/optuna/pull/2675#pullrequestreview-660688413.

## Description of the changes

See above.

### CODE REVIEW

**Comment by hvy** [comment]
@nzw0301 could you review this PR? I by the way think that one reviewer is sufficient for this change.

**Comment by nzw0301** [comment]
Thank you for your swift follow-up PR! Sure. 

Could you replace the following lines as well? Sorry, I checked files in only `optuna` directory.

- [`tutorial/10_key_features/004_distributed.py`](https://github.com/optuna/optuna/blob/2fd68d0102a22e76b5a4a142cc87722d92dcf667/tutorial/10_key_features/004_distributed.py#L15)
- [`tutorial/20_recipes/005_user_defined_sampler.py`](https://github.com/optuna/optuna/blob/2fd68d0102a22e76b5a4a142cc87722d92dcf667/tutorial/20_recipes/005_user_defined_sampler.py#L102)
- [`docs/source/index.rst`](https://github.com/optuna/optuna/blame/master/docs/source/index.rst#L131)
- [`README.md`](https://github.com/optuna/optuna/blame/master/README.md#L52)

**Comment by hvy** [comment]
Of course, I just pushed another commit addressing those 4 URLs. Thanks for the careful search and PTAL.

**Comment by nzw0301** [comment]
Thanks!

**Review by nzw0301 — APPROVED** [review]

**Pull request merged**
