### PR TITLE
Tune build time of #2076

### PR DESCRIPTION
**Pull request by toshihikoyanase**
## Motivation
Currently, the build of documents executes optimization code. In #2076 , the execution time of LightGBM took about ten minutes for only four trials ([log](https://circleci.com/api/v1.1/project/github/optuna/optuna/64524/output/104/0?file=true&allocation-id=5fcf45d6dabe8b01b85d5353-0-build%2F69E17DC0)). This PR investigates the cause and tune the build time.

## Description of the changes

Add an environmental variable `OMP_NUM_THREADS=1` like the execution of the unit tests.

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
The execution time of LightGBM code was about 0.2 sec according to the [log](https://circleci.com/api/v1.1/project/github/optuna/optuna/64578/output/104/0?file=true&allocation-id=5fd2c9c8e3759752a1330f5c-0-build%2F5EBDA122). The total build time on CircleCI was 5m 38s, which seems to be acceptable.
I'd like to apply the same change to RTD configuration.

```console
generating gallery for tutorial/10_key_features... [100%] 005_visualization.py
[I 2020-12-11 01:26:57,128] A new study created in memory with name: no-name-4ea1618a-0c9a-46b1-b4d7-79179e2c7a42
[I 2020-12-11 01:26:57,167] Trial 0 finished with value: 0.972027972027972 and parameters: {'lambda_l1': 2.348881295853308e-05, 'lambda_l2': 3.6010467344475403, 'num_leaves': 108, 'feature_fraction': 0.8678146001636615, 'bagging_fraction': 0.7581100947678923, 'bagging_freq': 2, 'min_child_samples': 87}. Best is trial 0 with value: 0.972027972027972.
[I 2020-12-11 01:26:57,212] Trial 1 finished with value: 0.972027972027972 and parameters: {'lambda_l1': 7.939154294216456e-08, 'lambda_l2': 0.0001359064372443865, 'num_leaves': 118, 'feature_fraction': 0.7606690070459252, 'bagging_fraction': 0.8248435466776274, 'bagging_freq': 6, 'min_child_samples': 57}. Best is trial 0 with value: 0.972027972027972.
[I 2020-12-11 01:26:57,240] Trial 2 finished with value: 0.951048951048951 and parameters: {'lambda_l1': 5.360294728728285, 'lambda_l2': 0.31044435499483225, 'num_leaves': 39, 'feature_fraction': 0.4004672595046086, 'bagging_fraction': 0.9953269355747305, 'bagging_freq': 1, 'min_child_samples': 80}. Best is trial 0 with value: 0.972027972027972.
[I 2020-12-11 01:26:57,272] Trial 3 finished with value: 0.972027972027972 and parameters: {'lambda_l1': 0.0031979998894294754, 'lambda_l2': 1.1577019024773634e-08, 'num_leaves': 90, 'feature_fraction': 0.5747374841188252, 'bagging_fraction': 0.7671117368334277, 'bagging_freq': 2, 'min_child_samples': 96}. Best is trial 0 with value: 0.972027972027972.
[I 2020-12-11 01:26:57,305] Trial 4 finished with value: 0.9370629370629371 and parameters: {'lambda_l1': 5.804965855340144, 'lambda_l2': 1.2443486010325558e-06, 'num_leaves': 191, 'feature_fraction': 0.8711055768358081, 'bagging_fraction': 0.5198042692950159, 'bagging_freq': 7, 'min_child_samples': 68}. Best is trial 0 with value: 0.972027972027972.
[I 2020-12-11 01:26:57,349] Trial 5 finished with value: 0.993006993006993 and parameters: {'lambda_l1': 0.00015880568272775815, 'lambda_l2': 0.5488626278802704, 'num_leaves': 136, 'feature_fraction': 0.502314474212375, 'bagging_fraction': 0.43903095579116774, 'bagging_freq': 4, 'min_child_samples': 93}. Best is trial 5 with value: 0.993006993006993.
```

**Comment by hvy** [comment]
What do you think about this comment https://github.com/optuna/optuna/pull/2076#discussion_r538191544 ?

**Comment by crcrpar** [comment]
You should check `computation time summary` instead.
```bash
computation time summary:
    - ../../tutorial/10_key_features/005_visualization.py:                       5.47 sec   0.0 MB
    - ../../tutorial/10_key_features/003_efficient_optimization_algorithms.py:   1.45 sec   0.0 MB
    - ../../tutorial/10_key_features/001_first.py:                               0.59 sec   0.0 MB
    - ../../tutorial/20_recipes/001_rdb.py:                                      0.35 sec   0.0 MB
    - ../../tutorial/20_recipes/004_cli.py:                                      0.26 sec   0.0 MB
    - ../../tutorial/20_recipes/005_user_defined_sampler.py:                     0.26 sec   0.0 MB
    - ../../tutorial/20_recipes/003_attributes.py:                               0.14 sec   0.0 MB
    - ../../tutorial/10_key_features/002_configurations.py:                      0.00 sec   0.0 MB
    - ../../tutorial/10_key_features/004_distributed.py:                         0.00 sec   0.0 MB
```

**Comment by crcrpar** [comment]
Why is this pull request still draft?

**Comment by crcrpar** [comment]
@toshihikoyanase, why do you keep this pull request draft? Are you stuck with the https://github.com/optuna/optuna/pull/2076#discussion_r538191544?

**Comment by hvy** [comment]
I could push the change for the comment above if you're busy.

**Comment by toshihikoyanase** [comment]
@crcrpar Thank you for your comment. I'll make it review-ready.
@hvy I checked https://github.com/optuna/optuna/pull/2076#discussion_r538191544, and I think the root cause of the visualization error is the number of hyperparamters. How about reducing them? I think you suggested in https://github.com/optuna/optuna/pull/2076#discussion_r538194690 although it is for a different reason.

**Comment by hvy** [comment]
Thanks for checking in. I'm fine either way. If we reduce the numbers, it's should probably be kept to at least 3 to make HPI somewhat interesting. However, we're currently specifying two parameters at several places so these might have to stay in any case.

**Comment by hvy** [comment]
By the way, is it ready for review? It's still named "WIP" but marked as ready.

**Comment by toshihikoyanase** [comment]
>  it's should probably be kept to at least 3 to make HPI somewhat interesting.

I removed `lambda_1`, `lambda_2`, `num_leaves` and `feature_fraction` and kept `bagging_fraction`, `bagging_freq` and `min_child_samples`. If we add one more hyperparameter, the layout of the contour plot and the slice plot will not be shown properly without the `params` argument.

image

image

**Review by hvy — APPROVED** [review]
Thanks, LGTM!

@crcrpar can you jump in as a second reviewer?

**Review by crcrpar — APPROVED** [review]
Thanks, let's see how things work.

**Pull request merged**
