### PR TITLE
Fix distribution's `_contains`

### LINKED ISSUE #2557: trial.suggest_int() ignores step
I used `trial.suggest_int()` with step. But, `suggest_int()` ignores arguments when study has trials with different distributions.

## Environment

- Optuna version: 2.6.0 
- Python version: 3.7.10
- OS: (I used Google Colab)
- (Optional) Other libraries and their versions:

## Error messages, stack traces, or logs

```
# error messages, stack traces, or logs
```

## Steps to reproduce

1. run reproducible example on Google Colab

## Reproducible examples (optional)

Bug case:
```python
import optuna

sampler = optuna.samplers.TPESampler(multivariate=True, n_startup_trials=10)
study = optuna.create_study(direction='maximize', sampler=sampler)

test_int_dist = optuna.distributions.IntUniformDistribution(0, 100) # no step
for v in range(100):
  trial = optuna.trial.create_trial(
          params={'test-int':v},
          distributions={'test-int': test_int_dist},
          value=0)
  study.add_trial(trial)

trial = study.ask()
trial.suggest_int('test-int', low=0, high=100, step=5) # specific step
```

the output is this:
image

correct case:
```python
import optuna

sampler = optuna.samplers.TPESampler(multivariate=True, n_startup_trials=10)
study = optuna.create_study(direction='maximize', sampler=sampler)

test_int_dist = optuna.distributions.IntUniformDistribution(0, 100, step=5) 
for v in range(100):
  trial = optuna.trial.create_trial(
          params={'test-int':v},
          distributions={'test-int': test_int_dist},
          value=0)
  study.add_trial(trial)

trial = study.ask()
trial.suggest_int('test-int', low=0, high=100, step=5) # specific step
```

### PR DESCRIPTION
**Pull request by not522**
## Motivation
Fix #2557. The distribution's `_contains` should take account of the `step` argument.

## Description of the changes
- Fix distributions' `_contains`
- Fix test

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@nzw0301 Could you review this PR if you have time?

**Review by HideakiImamura — APPROVED** [review]
Looks solid. LGTM!

**Review by nzw0301 — APPROVED** [review]
LGMT!

**Comment by nzw0301** [comment]
we need to update the document to pass the doctest:  https://optuna.readthedocs.io/en/stable/reference/generated/optuna.samplers.GridSampler.html

**Comment by not522** [comment]
`GridSampler`'s behavior seems to need discussion. I think it non-intuitive to ignore the step. However, it is documented...

**Comment by not522** [comment]
Please merge #2663 first.

**Comment by HideakiImamura** [comment]
The #2663 has been fixed. Could you merge the master?

**Review by HideakiImamura — APPROVED** [review]
Thanks for the update. LGTM.

@nzw0301 Please merge this PR after your approval.

**Comment by nzw0301** [comment]
Likewise, LGTM! Thank you for the update! I should have given more informative comments :(

**Pull request merged**
