### PR TITLE
Refactor pareto front

### PR DESCRIPTION
**Pull request by contramundum53**
## Motivation
Currently, `plot_pareto_front` calls `_get_pareto_front_info` internally and plots it. However, there is a testability issue in this design. We cannot separate the tests for `_get_pareto_front_info` and the tests for plotting, because we need a `study` object anyway for testing `plot_pareto_front`. 
We extract a function `_get_pareto_front_plot` that takes `_ParetoFrontInfo` and returns the plotted figure.

Dependent PRs: #3752 #3753 

## Description of the changes
* Extract a function `_get_pareto_front_plot` that takes `_ParetoFrontInfo` and returns the plotted figure.
* Add `include_dominated_trials` and `has_constraints_func` in `_ParetoFrontInfo` such that `_ParetoFrontInfo` is information-complete.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@c-bata Could you review this PR?

**Comment by c-bata** [comment]
@HideakiImamura Sorry, could you please only assign me to pull requests for Storage, CMA-ES, or something that needs design discussions? :pray:

**Comment by HideakiImamura** [comment]
@knshnb Could you review this PR?

**Review by HideakiImamura — APPROVED** [review]
LGTM. Note that #3753 should be merged at first.

**Comment by knshnb** [comment]
I'm sorry for the delayed response. It seems all the dependent PRs have been merged, so let me review this by tomorrow.

**Review by knshnb — APPROVED** [review]
LGTM!

**Pull request merged**
