### PR TITLE
Fix: Update output format options in CLI commands to include 'value' choice

### PR DESCRIPTION
**Pull request by iamarunbrahma**
## Motivation
The `--format` option has been implemented with the "value" choice for the study-names subcommand, but other subcommands like Studies and Trials don't have this option. This inconsistency in the CLI interface makes it harder for users to get output in a consistent format across different commands.

Fixes issue #5815

## Description of the changes
This PR makes the following changes to `optuna/cli.py`:

1. Added "value" format option to the `_Studies` class format choices:
   ```python
   choices=("value", "json", "table", "yaml")
   ```

2. Added "value" format option to the `_Trials` class format choices:
   ```python
   choices=("value", "json", "table", "yaml")
   ```

3. Changed the default format in the `_Ask` class from "table" to "json" to maintain consistency with test expectations:
   ```python
   default="json"
   ```

These changes ensure that:
- All CLI commands now support the same set of format options
- Users can use the "value" format consistently across all commands
- The behavior matches the test suite expectations

The changes have been tested with:
- Full test suite (98 tests passing)
- Code formatting tools (black, flake8, isort)
- Type checking (mypy)

### CODE REVIEW

**Comment by iamarunbrahma** [comment]
@not522 can you please review the code changes?

**Comment by not522** [comment]
@gen740 Could you review this PR?

**Comment by not522** [comment]
Could you also update `test_cli.py`?

**Comment by iamarunbrahma** [comment]
> Could you separate modification of `gp.py` for another PR? It's not related this PR.

Thanks @not522, I have removed the changes. Will create a separate PR

**Comment by iamarunbrahma** [comment]
> Could you also update `test_cli.py`?

I implemented "value" format changes in `test_cli.py`. But, test cases were failing as the `_parse_output` function returns a list for "value" format, but the test cases expect a dictionary-like object with keys. Hence, reverted the changes from `test_cli.py`.

Kindly, review the updated PR and let me know if you have any more suggestions.

**Comment by not522** [comment]
Thank you. The tests seem complicated, so I think it is OK to skip in this PR and handle in another PR.

I found that the following change is needed. Could you change this PR as follows?

```python
$ git diff
diff --git a/optuna/cli.py b/optuna/cli.py
index bbd054ce5..aec53935e 100644
--- a/optuna/cli.py
+++ b/optuna/cli.py
@@ -246,10 +246,7 @@ def _format_output(
         values, header = _convert_to_dict([records], columns, flatten)
 
     if output_format == "value":
-        if isinstance(records, list):
-            return _dump_value(values, header).strip()
-        else:
-            return str(values[0]).strip()
+        return _dump_value(values, header).strip()
     elif output_format == "table":
         return _dump_table(values, header).strip()
     elif output_format == "json":
```

#### Checking the modification.

```
$ optuna create-study --storage "sqlite:///tmp.db" --study-name "tmp"
$ optuna ask --storage "sqlite:///tmp.db" --study-name "tmp"
$ optuna tell --storage "sqlite:///tmp.db" --study-name "tmp" --trial-number 0 --value 0
```

* Result with this PR.

```
$ optuna best-trial --storage "sqlite:///tmp.db" --study-name "tmp" --format value
{'number': 0, 'value': 0.0, 'datetime_start': '2024-12-10 18:59:03', 'datetime_complete': '2024-12-10 18:59:18', 'duration': '0:00:15.303841', 'state': 'COMPLETE'}
```

* Result with the modification
```
$ optuna best-trial --storage "sqlite:///tmp.db" --study-name "tmp" --format value
0 0.0 2024-12-10 18:59:03 2024-12-10 18:59:18 0:00:15.303841 COMPLETE
```

**Comment by iamarunbrahma** [comment]
> Thank you. The tests seem complicated, so I think it is OK to skip in this PR and handle in another PR.
> 
> I found that the following change is needed. Could you change this PR as follows?
> 
> ```python
> $ git diff
> diff --git a/optuna/cli.py b/optuna/cli.py
> index bbd054ce5..aec53935e 100644
> --- a/optuna/cli.py
> +++ b/optuna/cli.py
> @@ -246,10 +246,7 @@ def _format_output(
>          values, header = _convert_to_dict([records], columns, flatten)
>  
>      if output_format == "value":
> -        if isinstance(records, list):
> -            return _dump_value(values, header).strip()
> -        else:
> -            return str(values[0]).strip()
> +        return _dump_value(values, header).strip()
>      elif output_format == "table":
>          return _dump_table(values, header).strip()
>      elif output_format == "json":
> ```
> 
> #### Checking the modification.
> ```
> $ optuna create-study --storage "sqlite:///tmp.db" --study-name "tmp"
> $ optuna ask --storage "sqlite:///tmp.db" --study-name "tmp"
> $ optuna tell --storage "sqlite:///tmp.db" --study-name "tmp" --trial-number 0 --value 0
> ```
> 
> * Result with this PR.
> 
> ```
> $ optuna best-trial --storage "sqlite:///tmp.db" --study-name "tmp" --format value
> {'number': 0, 'value': 0.0, 'datetime_start': '2024-12-10 18:59:03', 'datetime_complete': '2024-12-10 18:59:18', 'duration': '0:00:15.303841', 'state': 'COMPLETE'}
> ```
> 
> * Result with the modification
> 
> ```
> $ optuna best-trial --storage "sqlite:///tmp.db" --study-name "tmp" --format value
> 0 0.0 2024-12-10 18:59:03 2024-12-10 18:59:18 0:00:15.303841 COMPLETE
> ```

@not522 Implemented the above changes

**Comment by iamarunbrahma** [comment]
@not522 Implemented the above changes

**Review by not522 — APPROVED** [review]
Thank you! LGTM!

**Review by gen740 — APPROVED** [review]
LGTM!

**Pull request merged**
