### PR TITLE
Mitigate a blocking issue while running migrations with SQLAlchemy 2.0

### LINKED ISSUE #4371: Long time running test of MySQL storage with server
### Expected behavior

Finish the test of `Tests (Storage with server)` with MySQL in several minutes. 

### Environment

- Optuna version: 22e57eba9cf1f352800b99d8d6c8a23c47bad239
- Python version: 3.9, 3.11 (as long as I see)
- OS: Ubuntu 22.0.4 in GitHub Actions
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
https://github.com/optuna/optuna/actions/runs/4039069661
```

### Steps to reproduce

Run a CI job `Test (Storage with server)`

### Additional context (optional)

_No response_

### PR DESCRIPTION
**Pull request by c-bata**
## Motivation

Refs #4371 

## Summary

The cause is a "Waiting for metadata lock" in MySQL when creating the *alembic_version` table and inserting the revision, so MySQL driver keeps waiting to read the query result from the socket.

```
mysql> show full processlist;
+----+--------+------------------+--------+---------+------+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Id | User   | Host             | db     | Command | Time | State                           | Info                                                                                                                           |
+----+--------+------------------+--------+---------+------+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
|  8 | optuna | 172.17.0.1:35254 | optuna | Query   |    0 | init                            | show full processlist                                                                                                          |
|  9 | optuna | 172.17.0.1:50758 | optuna | Sleep   |   64 |                                 | NULL                                                                                                                           |
| 10 | optuna | 172.17.0.1:50760 | optuna | Query   |   64 | Waiting for table metadata lock | CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL,
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
) |
+----+--------+------------------+--------+---------+------+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
3 rows in set (0.00 sec)
```

By applying this patch, the frequency of the problem was mitigated to 2 out of 11 attempts. There still seems to be another problem, but that is currently being investigated and will be addressed in a following PR.

https://github.com/optuna/optuna/actions/runs/4071530931/jobs/7013678631

### SQLAlchemy v1.4.46 (master)

```
INFO:sqlalchemy.engine.Engine:SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
INFO:sqlalchemy.engine.Engine:[cached since 43.12s ago] {'table_schema': 'optuna', 'table_name': 'alembic_version'}
INFO:sqlalchemy.engine.Engine:SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
INFO:sqlalchemy.engine.Engine:[cached since 43.13s ago] {'table_schema': 'optuna', 'table_name': 'alembic_version'}
INFO:sqlalchemy.engine.Engine:
CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL,
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)

INFO:sqlalchemy.engine.Engine:[no key 0.00037s] {}
INFO:sqlalchemy.engine.Engine:INSERT INTO alembic_version (version_num) VALUES ('v3.0.0.d')
INFO:sqlalchemy.engine.Engine:[generated in 0.00020s] {}
INFO:sqlalchemy.engine.Engine:COMMIT
--Return--
> /Users/c-bata/go/src/github.com/optuna/optuna/optuna/storages/_rdb/storage.py(1063)_set_alembic_revision()->None
-> context.stamp(script, revision)
```

### SQLAlchemy v2.0.1 (master)

```
INFO:sqlalchemy.engine.Engine:DESCRIBE `optuna`.`alembic_version`
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:DESCRIBE `optuna`.`alembic_version`
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:
CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL,
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)

INFO:sqlalchemy.engine.Engine:[no key 0.00033s] {}
```

### SQLAlchemy v2.0.1 (this PR)

```
INFO:sqlalchemy.engine.Engine:DESCRIBE `optuna`.`alembic_version`
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:DESCRIBE `optuna`.`alembic_version`
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:
CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL,
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00039s] {}
INFO:sqlalchemy.engine.Engine:INSERT INTO alembic_version (version_num) VALUES ('v3.0.0.d')
INFO:sqlalchemy.engine.Engine:[generated in 0.00023s] {}
INFO:sqlalchemy.engine.Engine:COMMIT
--Return--
> /Users/c-bata/go/src/github.com/optuna/optuna/optuna/storages/_rdb/storage.py(1064)_set_alembic_revision()->None
-> context.stamp(script, revision)
```

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@contramundum53 @toshihikoyanase Could you review this PR?

**Review by contramundum53 — APPROVED** [review]
In [the official document](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Connection), the `connect()` method is always used with `with` block. I couldn't understand what would happen without the `connect()` method, but this change looks good to me.

**Review by toshihikoyanase — COMMENTED** [review]
The change looks good to me. I investigated the codebase of SQLAlchemy, and `Connection` is expected to be closed when it is not used.

- `self.engine.connect()` ([Engine.connect](https://github.com/sqlalchemy/sqlalchemy/blob/318d36a1c25ee6007761fadf987f46d7c6ebb003/lib/sqlalchemy/engine/base.py#L3222)) returns [Connection](https://github.com/sqlalchemy/sqlalchemy/blob/318d36a1c25ee6007761fadf987f46d7c6ebb003/lib/sqlalchemy/engine/base.py#L87)
- In the docstring of `connect()` method, the behavior of `Connection.__exit__` is explained as follows:

        Where above, after the block is completed, the connection is "closed"
        and its underlying DBAPI resources are returned to the connection pool.
        This also has the effect of rolling back any transaction that
        was explicitly begun or was begun via autobegin, and will
        emit the :meth:`_events.ConnectionEvents.rollback` event if one was
        started and is still in progress.
- The implementation of `Connection.close` can be found [here](https://github.com/sqlalchemy/sqlalchemy/blob/318d36a1c25ee6007761fadf987f46d7c6ebb003/lib/sqlalchemy/engine/base.py#L1208-L1254)

Maybe this is out of scope of this PR, but I found another unclosed connection. Do you think we can apply the change to it?

https://github.com/c-bata/optuna/blob/d77f11dd1e031197af0f563e4d757c0f9cfd94d7/optuna/storages/_rdb/storage.py#L1097

```python
    def get_current_version(self) -> str:
        context = alembic_migration.MigrationContext.configure(self.engine.connect())
        version = context.get_current_revision()
        assert version is not None

        return version
````

**Comment by c-bata** [comment]
Thank you for your thorough review!

> Maybe this is out of scope of this PR, but I found another unclosed connection. Do you think we can apply the change to it?

Good catch. Yes, it sounds safer to apply the change to it. I will push that change.

**Review by toshihikoyanase — APPROVED** [review]
Thank you for your update. LGTM!
Could you rebase `master` to resolve the CI issues?

**Comment by c-bata** [comment]
Thank you for your review! I've pushed a merge commit to resolve CI issues.

**Pull request merged**
