### PR TITLE
remove `_log_normal_cdf`

### PR DESCRIPTION
**Pull request by kstoneriv3**
## Motivation

`_log_normal_cdf` seems not used at all so I suggest removing it.

### CODE REVIEW

**Review by hvy — APPROVED** [review]
Thanks, LGTM!

**Review by crcrpar — APPROVED** [review]
Looks good. Could you update this branch so as to

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by HideakiImamura** [comment]
@kstoneriv3 By the way, could you merge master to pass the CI?

**Pull request merged**
