### PR TITLE
Fix inconsistencies between terminator and terminator visualization i…

### PR DESCRIPTION
**Pull request by SimonPop**
Hi!

The goal of this pull request is to answer issue #5073 

## Motivation
As mentioned in the issue, the objective is to harmonize the `plot_terminator_improvement` function and `Terminator` class when initializing the `error_evaluator` object. 

## Description of the changes
It adds a similar logic to the initialization of the `error_evaluator` for `plot_terminator_improvement` so that it reflects what the `Terminator` class does.

## Suggestions
Currently, I replicated the logic in `plot_terminator_improvement`. Should I factorize that code with that of the `Terminator` class so that when updated, we do not risk creating the same discrepancy in the future? 

I could add a static method to Terminator to initialize `error_evaluator`. What do you think? That way, I could also add a unit test more easily.

### CODE REVIEW

**Comment by y0z** [comment]
@contramundum53 Could you review this PR?

**Comment by contramundum53** [comment]
Thank you for your contribution!

**Review by contramundum53 — APPROVED** [review]
LGTM!

**Comment by contramundum53** [comment]
@HideakiImamura Could you review this PR as the author of the issue?

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
