### PR TITLE
Add an example of enqueue_trial

### PR DESCRIPTION
**Pull request by c-bata**
See https://github.com/optuna/optuna/pull/520#discussion_r379248121

ScreenShot 2020-02-14 16 27 48

### CODE REVIEW

**Comment by c-bata** [comment]
The following might be better.

```

        Example:

            .. testcode::

               import optuna

               def objective(trial):
                   x = trial.suggest_uniform('x', 0, 10)
                   return x ** 2

               study = optuna.create_study()
               study.enqueue_trial({'x': 5})
               study.optimize(objective, n_trials=1)

               print("x = {}".format(study.trials[0].params['x']))

            .. testoutput::

               x = 5
```

ScreenShot 2020-02-14 16 33 46

**Comment by hvy** [comment]
Thanks for you very quick action. I'm perfectly fine with either of your suggestions. The current example with two calls to `enqueue_trial` seem more demonstrative without being too complicated so I would like to approve it as is but please fill me in if I'm missing your point.

**Comment by c-bata** [comment]
Thank you for your feedback. I leave the current example.

**Comment by hvy** [comment]
Let me go ahead and merge this PR.

**Pull request merged**
