### PR TITLE
Fix test_pytorch_lightning.py

### LINKED ISSUE #3418: Support latest PyTorch lightning
### Expected behavior

Optuna works with the latest PyTorch-Lightning (1.6.0).

### Environment

- Optuna version: 3.0.0b0.dev
- Python version: 
- OS: Independent
- (Optional) Other libraries and their versions: PyTorch-Lightning 1.6.0

### Error messages, stack traces, or logs

```shell
tests/integration_tests/test_pytorch_lightning.py:158: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
optuna/study/study.py:399: in optimize
    _optimize(
optuna/study/_optimize.py:68: in _optimize
    _optimize_sequential(
optuna/study/_optimize.py:162: in _optimize_sequential
    trial = _run_trial(study, func, catch)
optuna/study/_optimize.py:262: in _run_trial
    raise func_err
optuna/study/_optimize.py:211: in _run_trial
    value_or_values = func(trial)
tests/integration_tests/test_pytorch_lightning.py:143: in objective
    trainer = pl.Trainer(
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py:339: in insert_env_defaults
    return fn(self, **kwargs)
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:561: in __init__
    self._call_callback_hooks("on_init_start")
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1617: in _call_callback_hooks
    fn(self, *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <optuna.integration.pytorch_lightning.PyTorchLightningPruningCallback object at 0x7f892c1c5730>
trainer = <pytorch_lightning.trainer.trainer.Trainer object at 0x7f892c1c5040>

    def on_init_start(self, trainer: Trainer) -> None:
>       self.is_ddp_backend = trainer._accelerator_connector.distributed_backend is not None
E       AttributeError: 'AcceleratorConnector' object has no attribute 'distributed_backend'

optuna/integration/pytorch_lightning.py:60: AttributeError
```

https://github.com/optuna/optuna/runs/5745775785?check_suite_focus=true

```
tests/integration_tests/test_pytorch_lightning.py:6: in <module>
    import pytorch_lightning as pl
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/__init__.py:30: in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py:26: in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/callbacks/pruning.py:31: in <module>
    from pytorch_lightning.core.lightning import LightningModule
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/core/__init__.py:16: in <module>
    from pytorch_lightning.core.lightning import LightningModule
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py:40: in <module>
    from pytorch_lightning.loggers import LightningLoggerBase
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/loggers/__init__.py:18: in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/loggers/tensorboard.py:26: in <module>
    from torch.utils.tensorboard import SummaryWriter
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py:4: in <module>
    LooseVersion = distutils.version.LooseVersion
E   AttributeError: module 'distutils' has no attribute 'version'
```

https://github.com/optuna/optuna/runs/5745734509?check_suite_focus=true

### Steps to reproduce

See our CI failures.

### Additional context (optional)

It may be the simplest way to support PyTorch v1.11.0 (https://github.com/PyTorchLightning/pytorch-lightning/issues/12324).

🔗 https://github.com/optuna/optuna/pull/3417

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Resolve #3418 and #4116 

## Description of the changes

Refactor deprecated features 
- `trainer.training_type_plugin` is deleted since v1.8 ([PR#11239](https://github.com/Lightning-AI/lightning/pull/11239)). The attribute `training_type_plugin` is just renamed to `strategy`, so refactored as suggested.

- An optional argument of `trainer`, `accelerator` stopped to accept `ddp_cpu`. Instead, we can pass `ddp` to `strategy` and `cpu` to `accelerator`. Also, `num_processes` will be removed, so we give the number of processes to `devices` instead.

-  `AcceleratorConnector.distributed_backend` is deleted, but now they have `AcceleratorConnector.is_distributed` instead, so refactored as suggested.

- `callback.on_init_start()` is deleted since v1.8 ([Issue#10894](https://github.com/Lightning-AI/lightning/issues/10894), [PR#10940](https://github.com/Lightning-AI/lightning/pull/10940), [PR#14867](https://github.com/Lightning-AI/lightning/pull/14867)).
Although they don't provide exactly equivalent alternative, it would be possible to move this confirmation to somewhere else. Although it seems [`strategy.setup_environment`](https://github.com/Lightning-AI/lightning/blob/3e7c014845f939c20774486ee3798dbcef4db7f9/src/pytorch_lightning/trainer/trainer.py#L1034) is the right place to implement this check, implementing as a method of `Strategy` will affect user's code. Therefore it will be reasonable to implement as `callback.setup` or `callback.on_fit_start()`.

### CODE REVIEW

**Comment by grburgess** [comment]
Out of curiosity, is all working for PL 1.8 for this branch w.r.t. the pruner?

**Comment by Alnusjaponica** [comment]
Thanks for the question. It is what we aim to do in this PR. @grburgess

**Comment by grburgess** [comment]
Thanks! I checked out this branch to try (which I should have done in the first place) and indeed the issue seems fixed

**Comment by Alnusjaponica** [comment]
Thank you for trying the patch. Please note that the problem of distributed processing still remains for now.

**Comment by Alnusjaponica** [comment]
## Problem
When you use DDP and optuna.TrialPruned() is raised from the child process, Pytorch Lightning tries to resynchronize to fix the "error" and finally deal it as a DeadlockDetectedException, which terminates the whole process. For more details, see [reconciliate_processes](https://github.com/Lightning-AI/lightning/blob/15ef52bc732d1f907de4de58683f131652c0d68c/src/pytorch_lightning/strategies/ddp.py#L427). To fix this problem, we need to change environment variable or private variable.

## Alternative
Stop supporting DDP in order to fix daily test integration (#4116) and to support PyTorch Lightning after v1.6.

**Comment by nzw0301** [comment]
When I tried to fix this issue before, I also thought that calling `TrialPruned` in the main process manually like catboost callback is another approach,
https://github.com/optuna/optuna-examples/blob/main/catboost/catboost_pruning.py#L57.

**Comment by Alnusjaponica** [comment]
@nzw0301 
Thank you for your advice. I'll see if the suggested approach works for this case.
If it is possible, I am going to apply the change to support DDP after #4327.

**Pull request closed without merging**
