### PR TITLE
Move tests for `create_trial`

### PR DESCRIPTION
**Pull request by not522**
## Motivation
Move tests for `create_trial` from `test_trial.py` to `test_frozen.py` because it is implemented in `_frozen.py`.

## Description of the changes
Move tests for `create_trial` from `test_trial.py` to `test_frozen.py`.

### CODE REVIEW

**Review by contramundum53 — APPROVED** [review]
LGTM.

**Comment by contramundum53** [comment]
The check seems to be failing in a irrelevant place.

**Comment by contramundum53** [comment]
Could you review this PR? @HideakiImamura

**Review by HideakiImamura — APPROVED** [review]
LGTM.

Could you merge the master branch?

**Pull request merged**
