### PR TITLE
Make src comments more descriptive in examples/pytorch_lightning_simple.py

### PR DESCRIPTION
**Pull request by iamshnoo**
## Motivation

Solves #1590 for Hacktoberfest.

## Description of the changes

I added the description mentioned in the issue for the required comment. Do let me know if any other parts have to be changed as well and I can push another commit for it.

Specifically, the comment on line 73 for this file
```python
 # Assigning the layers as class variables (PyTorch requirement).
```
has been updated in the first commit to explain the necessity of doing so.

### CODE REVIEW

**Review by HideakiImamura — COMMENTED** [review]
Thanks for the PR! The given explanation looks good to me. How about adding "for the same reason as above" to the following dropout section?

**Comment by iamshnoo** [comment]
Added it. Thanks!

**Review by HideakiImamura — APPROVED** [review]
Looks great! Thanks!

**Review by hvy — APPROVED** [review]
LGTM!

**Pull request merged**
