### PR TITLE
Prefix '_' to private attributes of classes in `optuna.integration`.

### PR DESCRIPTION
**Pull request by toshihikoyanase**
Similarly to #697, this PR changes the name of private attributes of the classes in `optuna.integration`.

### CODE REVIEW

**Comment by hvy** [comment]
@toshihikoyanase, I am about to start reviewing the changes but could you resolve the conflicts you think?

**Comment by toshihikoyanase** [comment]
@hvy, I resolved the conflicts. The PR is ready for review.

**Comment by hvy** [comment]
Is this a good time to delete [`ChainerMNTrial.trial_id`](https://github.com/optuna/optuna/blob/master/optuna/integration/chainermn.py#L296)?

**Comment by hvy** [comment]
`optuna.integration.cma.MIN_SIGMA0` seems quite internal to me but is this something that the user possibly is concerned with?

**Comment by toshihikoyanase** [comment]
> [`optuna.integration.cma.MIN_SIGMA0`](https://github.com/optuna/optuna/blob/master/optuna/integration/cma.py#L39) seems quite internal to me but is this something that the user possibly is concerned with? Similarly, [`names_from_tuner`](https://github.com/optuna/optuna/pull/705/files#diff-456cd17454181c4f30511dc3c6d058c2R24).

Thank you for pointing it out. As you mentioned, they are internal variables, and users rarely refer to them. So, I'll make them private.

**Comment by hvy** [comment]
Found two symbols in `sklearn` which I am not too confident about but though that might be work clarifying.
- [`safe_indexing`](https://github.com/optuna/optuna/blob/master/optuna/integration/sklearn.py#L74) seems rather trivial and internal.
- The [`logger`](https://github.com/optuna/optuna/blob/master/optuna/integration/sklearn.py#L58).

**Comment by hvy** [comment]
Should we go through symbols in `optuna.integrations.lightgbm_tuner` in a separate PR? Maybe its `optimize.py` is hefty.

**Comment by hvy** [comment]
As for your 1st and 3rd points, makes sense. (It wasn't immediately obvious that `lightgbm_tuner` was experimental at first but I now noticed that it's excluded from the docs.)

**Pull request merged**
