### PR TITLE
Match the argument order of `download_artifact` to that of `upload_artifact`

### PR DESCRIPTION
**Pull request by nabenabe0928**
## Motivation

I united the argument order of `download_artifact` to that of `upload_artifact` to avoid confusion.

### CODE REVIEW

**Comment by y0z** [comment]
@c-bata, @porink0424 Could you review this PR?

**Comment by toshihikoyanase** [comment]
Could you show us the correspondence of the arguments between `download_artifact` and `upload_artifact `, please?

**Comment by nabenabe0928** [comment]
@toshihikoyanase 
The current API for each function looks like this:

```python
def upload_artifact(study_or_trial, file_path, artifact_store, ...) -> str:
    ...

def download_artifact(artifact_store, artifact_id, file_path) -> None:
    ...
```

I updated `download_artifact` to:

```python
def download_artifact(file_path, artifact_store, artifact_id) -> None:
    ...
```

so that `file_path` comes before `artifact_store` for both functions.
Another possibility is to make them:

```python
def upload_artifact(artifact_store, file_path, study_or_trial,  ...) -> str:
    ...

def download_artifact(artifact_store, file_path, artifact_id) -> None:
    ...
```

Although this change makes the order clearer, it will be a breaking change.
I avoided the breaking change in this PR, but what do you think, @c-bata ?

**Review by porink0424 — APPROVED** [review]
I think this change is enough, and further breaking change is a bit much.

**Pull request closed without merging**
