### PR TITLE
Add constraints support to `matplotlib._optimization_history_plot`

### PR DESCRIPTION
**Pull request by hrntsm**
## Motivation

Reflect #4793  updates to matplotlib part

## Description of the changes

Constraints are applied in the same way as plotly

Screenshot 2023-07-18 at 22 00 41

Screenshot 2023-07-18 at 22 00 58

### CODE REVIEW

**Comment by hrntsm** [comment]
I noticed in the PR below that the matplotlib side also has markers on the best value, but the plotly side only has lines. Should I match one to the other?
https://github.com/optuna/optuna-visualization-regression-tests/pull/13

**Comment by c-bata** [comment]
> I noticed in the PR below that the matplotlib side also has markers on the best value, but the plotly side only has lines. Should I match one to the other? [optuna/optuna-visualization-regression-tests#13](https://github.com/optuna/optuna-visualization-regression-tests/pull/13)

Good catch 👍 I don't think it's a high priority, but we can align the implementation between plotly and matplotlib. In Optuna Dashboard, the history plot do not render all makers on the best value line since it increases the calculation cost when a lot of trials exist. So if we have to choose one, I prefer plotly's approach.

Screenshot 2023-07-19 11 36 47

**Review by c-bata — APPROVED** [review]
LGTM!


Here is an output image of https://github.com/optuna/optuna-visualization-regression-tests/pull/13.

Screenshot 2023-07-19 12 07 29

**Comment by hrntsm** [comment]
Fixed best value does not include markers.
Screenshot 2023-07-19 at 12 44 36
Screenshot 2023-07-19 at 12 44 49

**Review by HideakiImamura — APPROVED** [review]
Thanks for the PR. LGTM!

**Pull request merged**
