### PR TITLE
Fix inappropriate behavior in `plot_rank()` when `None` values exist in trial

### LINKED ISSUE #5633: Inappropriate behavior of `plot_rank()` in `optuna.visualization`  when `None` values exist in trials
### Expected behavior

Currently, if `None` value exists in trials, the function `plot_rank()` in `optuna.visualization` shows inappropriate behavior:

- When using `plotly` (i.e., using `optuna.visualization.plot_rank`):

   - trial with `None` value will be ignored and not plotted.

- When using `matplotlib` (i.e., using `optuna.visualization.matplotlib.plot_rank`):

   - an error occurs and no plot will be made.

The expected behavior is as follows:

- a plot with all trials is made even if the trials contain `None` values (for both `plotly` and `matplotlib`).

### Environment

- Optuna version: master branch
- Python version: any
- OS: any

### Error messages, stack traces, or logs

The error message when using `matplotlib` is follows:

```py
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 10
      7 study = optuna.create_study()
      8 study.optimize(objective, n_trials=20)
---> 10 fig = optuna.visualization.matplotlib.plot_rank(study)
     11 fig.show()

File ~/Documents/2_PFN/pfn-workspace/optuna/optuna/_experimental.py:82, in experimental_func.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
     71 @functools.wraps(func)
     72 def wrapper(*args: Any, **kwargs: Any) -> "FT":
     73     warnings.warn(
     74         "{} is experimental (supported from v{}). "
     75         "The interface can change in the future.".format(
   (...)
     79         stacklevel=2,
     80     )
---> 82     return func(*args, **kwargs)

File ~/Documents/2_PFN/pfn-workspace/optuna/optuna/visualization/matplotlib/_rank.py:98, in plot_rank(study, params, target, target_name)
     93 _logger.warning(
     94     "Output figures of this Matplotlib-based `plot_rank` function would be different from "
     95     "those of the Plotly-based `plot_rank`."
     96 )
     97 info = _get_rank_info(study, params, target, target_name)
...
     94         ", ".join(names[:-1]) + " or " + names[-1]
     95         if len(names) > 1 else names[0],
     96         type_name(type(v))))

TypeError: 'value' must be an instance of str or bytes, not a None
```

### Steps to reproduce

The following code yields the error above:

```py
def objective(trial: optuna.Trial) -> float:
    x = trial.suggest_float("x", -100, 100)
    trial.suggest_categorical("y", ["foo", None])
    return x**2

study = optuna.create_study()
study.optimize(objective, n_trials=20)

fig = optuna.visualization.matplotlib.plot_rank(study)
fig.show()
```

### Additional context (optional)

This issue is related to this PR:

- #5599 .

This PR simply suppressed the issue reported here and left TODO comments saying that this issue should be addressed in the future. The another issue is resolved in this PR:

- #5630 .

One solution about this issue is convert `None` value to the string `"None"` before the plot is made.
Specifically, `None` value in `info.xs` and `info.ys` in `optuna.visualization._get_rank_subplot` and `optuna.visualization.matplotlib._add_rank_subplot` should be converted before they being passed to these functions.

The current code can be found here:

- for `optuna.visualization.plot_rank`:
    https://github.com/optuna/optuna/blob/1f38f73efae96d4d0099142efc794ea802f864a0/optuna/visualization/_rank.py#L301-L303

- and for `optuna.visualization.matplotlib.plot_rank`:

   https://github.com/optuna/optuna/blob/1f38f73efae96d4d0099142efc794ea802f864a0/optuna/visualization/matplotlib/_rank.py#L163

.

The conversion can simply be done by these code:

```py
["None" if x is None else x for y in info.xs]
["None" if y is None else y for y in info.ys]
```

and these values should be passed in these functions.

### PR DESCRIPTION
**Pull request by kAIto47802**
## Motivation

This PR aims to:

- Resolve #5633 .

Also, this PR is related to:

- #5599 .

## Description of the changes

- Convert the `None` value to the string `"None"` before the plot is made.
- Remove xfail from the unit tests because this PR solves the bug.

### CODE REVIEW

**Comment by nabenabe0928** [comment]
```python
import matplotlib.pyplot as plt

import optuna


def objective(trial: optuna.Trial) -> float:
    trial.suggest_categorical("x", [1, "1"])
    trial.suggest_float("y", -1, 1)
    return 0


study = optuna.create_study()
study.optimize(objective, n_trials=100)
fig = optuna.visualization.plot_rank(study)
fig.show()
optuna.visualization.matplotlib.plot_rank(study)
plt.show()

```

Plotly

image

Matplotlib

```python
Traceback (most recent call last):
  File "/home/shuhei/pfn-work/optuna-dev/optuna/e.py", line 17, in <module>
    optuna.visualization.matplotlib.plot_rank(study)
  File "/home/shuhei/pfn-work/optuna-dev/optuna/optuna/_experimental.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/shuhei/pfn-work/optuna-dev/optuna/optuna/visualization/matplotlib/_rank.py", line 98, in plot_rank
    return _get_rank_plot(info)
  File "/home/shuhei/pfn-work/optuna-dev/optuna/optuna/visualization/matplotlib/_rank.py", line 119, in _get_rank_plot
    pc = _add_rank_subplot(axs, sub_plot_infos[0][0])
  File "/home/shuhei/pfn-work/optuna-dev/optuna/optuna/visualization/matplotlib/_rank.py", line 163, in _add_rank_subplot
    return ax.scatter(x=info.xs, y=info.ys, c=info.colors / 255, edgecolors="grey")
  File "/home/shuhei/pfn-work/optuna-dev/optuna/venv/lib/python3.9/site-packages/matplotlib/__init__.py", line 1473, in inner
    return func(
  File "/home/shuhei/pfn-work/optuna-dev/optuna/venv/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 4781, in scatter
    x, y = self._process_unit_info([("x", x), ("y", y)], kwargs)
  File "/home/shuhei/pfn-work/optuna-dev/optuna/venv/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2585, in _process_unit_info
    axis.update_units(data)
  File "/home/shuhei/pfn-work/optuna-dev/optuna/venv/lib/python3.9/site-packages/matplotlib/axis.py", line 1747, in update_units
    default = self.converter.default_units(data, self)
  File "/home/shuhei/pfn-work/optuna-dev/optuna/venv/lib/python3.9/site-packages/matplotlib/category.py", line 105, in default_units
    axis.set_units(UnitData(data))
  File "/home/shuhei/pfn-work/optuna-dev/optuna/venv/lib/python3.9/site-packages/matplotlib/category.py", line 181, in __init__
    self.update(data)
  File "/home/shuhei/pfn-work/optuna-dev/optuna/venv/lib/python3.9/site-packages/matplotlib/category.py", line 216, in update
    _api.check_isinstance((str, bytes), value=val)
  File "/home/shuhei/pfn-work/optuna-dev/optuna/venv/lib/python3.9/site-packages/matplotlib/_api/__init__.py", line 91, in check_isinstance
    raise TypeError(
TypeError: 'value' must be an instance of str or bytes, not a int
```

**Comment by nabenabe0928** [comment]
@kAIto47802 
- [ ] Convert every single choice to string

**Review by nabenabe0928 — APPROVED** [review]
LGTM!
Followup could be to add the unittest to verify the change in this PR, i.e. to test whether the plot works even with `None` in `choices`.

**Review by not522 — APPROVED** [review]
LGTM!

**Pull request merged**
