### PR TITLE
add some jitters in `_MultivariateParzenEstimators`

### PR DESCRIPTION
**Pull request by kstoneriv3**
## Motivation

As discussed in #1917, the multivariate TPE lacks some of the jitters (jitters `EPS` are often added to variables before division or logarithm for avoiding errors) that independent TPE has. This PR aims to make the use of jitters consistent between multivariate and independent TPEs.

### CODE REVIEW

**Comment by kstoneriv3** [comment]
I do not understand why the CI is failing.

**Comment by nzw0301** [comment]
I think this is because a new Pytorch-lightning version, v1.0, has beed released, and this update breaks some backward compatibility.

**Review by HideakiImamura — APPROVED** [review]
Thanks for the PR! LGTM!

Could you merge the master to pass the CI?

**Review by hvy — APPROVED** [review]
Thank you, that was quick. LGTM!

**Pull request merged**
