### PR TITLE
refactor:  Fixed a flake8 error

### PR DESCRIPTION
**Pull request by jmsykes83**
Error:
		Fixed a flake8 error that was saying
		the line was 101>99.  I fixed the error
		by moving the whole line down one row.

### CODE REVIEW

**Comment by nzw0301** [comment]
fake8 looks unhappy with the introduction of the change. In addition, the current Optuna does not have flake8 error according to the master branch's CI.

**Comment by nzw0301** [comment]
I think this error comes from using newer flake8. In Optuna CI, flake8 version is 3.8.4. Indeed, when I used flake8 5.0.0, I could reproduce the result. I suppose https://github.com/optuna/optuna/pull/3833 might have a similar problem.

**Comment by himkt** [comment]
```sh
> tox -e flake8 -e black -e blackdoc -e isort -e mypy                                                                                                                               2022-08-01 00:09:33
.tox is correct? [y, n, a, e]:n
GLOB sdist-make: /Users/himkt/work/github.com/himkt/optuna/setup.py
flake8 recreate: /Users/himkt/work/github.com/himkt/optuna/.tox/flake8
flake8 installdeps: flake8
flake8 inst: /Users/himkt/work/github.com/himkt/optuna/.tox/.tmp/package/1/optuna-3.0.0rc0.dev0.zip
flake8 installed: alembic==1.8.1,attrs==22.1.0,autopage==0.5.1,cliff==3.10.1,cmaes==0.8.2,cmd2==2.4.2,colorlog==6.6.0,flake8==5.0.0,greenlet==1.1.2,importlib-metadata==4.12.0,importlib-resources==5.9.0,Mako==1.2.1,MarkupSafe==2.1.1,mccabe==0.7.0,numpy==1.23.1,optuna @ file:///Users/himkt/work/github.com/himkt/optuna/.tox/.tmp/package/1/optuna-3.0.0rc0.dev0.zip,packaging==21.3,pbr==5.9.0,prettytable==3.3.0,pycodestyle==2.9.0,pyflakes==2.5.0,pyparsing==3.0.9,pyperclip==1.8.2,PyYAML==6.0,scipy==1.8.1,SQLAlchemy==1.4.39,stevedore==4.0.0,tqdm==4.64.0,typing_extensions==4.3.0,wcwidth==0.2.5,zipp==3.8.1
flake8 run-test-pre: PYTHONHASHSEED='3070457183'
flake8 run-test: commands[0] | flake8 .
```

I just realized `tox` installs the latest flake8, which is not intended I think.

**Comment by jmsykes83** [comment]
> ```shell
> > tox -e flake8 -e black -e blackdoc -e isort -e mypy                                                                                                                               2022-08-01 00:09:33
> .tox is correct? [y, n, a, e]:n
> GLOB sdist-make: /Users/himkt/work/github.com/himkt/optuna/setup.py
> flake8 recreate: /Users/himkt/work/github.com/himkt/optuna/.tox/flake8
> flake8 installdeps: flake8
> flake8 inst: /Users/himkt/work/github.com/himkt/optuna/.tox/.tmp/package/1/optuna-3.0.0rc0.dev0.zip
> flake8 installed: alembic==1.8.1,attrs==22.1.0,autopage==0.5.1,cliff==3.10.1,cmaes==0.8.2,cmd2==2.4.2,colorlog==6.6.0,flake8==5.0.0,greenlet==1.1.2,importlib-metadata==4.12.0,importlib-resources==5.9.0,Mako==1.2.1,MarkupSafe==2.1.1,mccabe==0.7.0,numpy==1.23.1,optuna @ file:///Users/himkt/work/github.com/himkt/optuna/.tox/.tmp/package/1/optuna-3.0.0rc0.dev0.zip,packaging==21.3,pbr==5.9.0,prettytable==3.3.0,pycodestyle==2.9.0,pyflakes==2.5.0,pyparsing==3.0.9,pyperclip==1.8.2,PyYAML==6.0,scipy==1.8.1,SQLAlchemy==1.4.39,stevedore==4.0.0,tqdm==4.64.0,typing_extensions==4.3.0,wcwidth==0.2.5,zipp==3.8.1
> flake8 run-test-pre: PYTHONHASHSEED='3070457183'
> flake8 run-test: commands[0] | flake8 .
> ```
> 
> I just realized `tox` installs the latest flake8, which is not intended I think.

Ok, thanks for the heads-up.  I will look into it.

**Comment by himkt** [comment]
The problem is caused because versions of flake8, isort, black, and blackdoc are not fixed in `tox.ini`. We need to fix versions of them. I think installing Optuna using `basepython` (py38 is enough) and `extras` (`checking`) instead of `deps` for installing linter/formatter solves the problem (Of course we can also add the version constraints for them, however, we don't want to write version information in more than one place).
https://github.com/optuna/optuna/blob/c6aac178c33b268abbd7db52efc504331194d05e/tox.ini#L96-L118

We really appreciate if you send a patch to fix this problem! (just for the note: we are actively discussing whether it continues to use `tox`, since some developers only use `formats.sh`)

**Pull request closed without merging**
