### PR TITLE
Bump up PyTorch version

### PR DESCRIPTION
**Pull request by crcrpar**
related: #2034

### CODE REVIEW

**Comment by hvy** [comment]
Could you check the CI failure?

**Comment by crcrpar** [comment]
It's unrelated to this pull request. The failure occurred in some pull requests at the time, and thereafter it hasn't.

**Comment by crcrpar** [comment]
Or, do you mean "you should fix the error"?

**Comment by hvy** [comment]
Sorry and thanks for the explanation. Seems to work fine after rebuild.

**Comment by crcrpar** [comment]
```
~/ghq/github.com/optuna/optuna master 4m 32s
optuna ❯ python -c "import torch; print(torch.__version__)"
1.7.1

~/ghq/github.com/optuna/optuna master
optuna ❯ python examples/pytorch_simple.py > /dev/null
[I 2020-12-16 12:45:13,757] A new study created in memory with name: no-name-6b3bedd7-eb83-4184-aacb-7ab2dc4c2996
[I 2020-12-16 12:45:18,952] Trial 0 finished with value: 0.94140625 and parameters: {'n_layers': 3, 'n_units_l0': 106, 'dropout_l0': 0.2234073271295492, 'n_units_l1': 125, 'dropout_l1': 0.26673571839331334, 'n_units_l2': 91, 'dropout_l2': 0.21274138084347488, 'optimizer': 'RMSprop', 'lr': 0.0015297528243772554}. Best is trial 0 with value: 0.94140625.
[I 2020-12-16 12:45:23,644] Trial 1 finished with value: 0.92109375 and parameters: {'n_layers': 1, 'n_units_l0': 97, 'dropout_l0': 0.3775713194120752, 'optimizer': 'Adam', 'lr': 0.001349335925166156}. Best is trial 0 with value: 0.94140625.
[I 2020-12-16 12:45:28,166] Trial 2 finished with value: 0.38984375 and parameters: {'n_layers': 1, 'n_units_l0': 123, 'dropout_l0': 0.20429791067714131, 'optimizer': 'SGD', 'lr': 0.0018085207712691146}. Best is trial 0 with value: 0.94140625.
[I 2020-12-16 12:45:32,660] Trial 3 finished with value: 0.87890625 and parameters: {'n_layers': 1, 'n_units_l0': 87, 'dropout_l0': 0.2546413648320384, 'optimizer': 'SGD', 'lr': 0.0503736741459419}. Best is trial 0 with value: 0.94140625.
[I 2020-12-16 12:45:37,215] Trial 4 finished with value: 0.5078125 and parameters: {'n_layers': 1, 'n_units_l0': 24, 'dropout_l0': 0.31417876570597136, 'optimizer': 'SGD', 'lr': 0.004200463366826182}. Best is trial 0 with value: 0.94140625.
[I 2020-12-16 12:45:37,686] Trial 5 pruned.
[I 2020-12-16 12:45:38,150] Trial 6 pruned.
[I 2020-12-16 12:45:38,640] Trial 7 pruned.
[I 2020-12-16 12:45:39,102] Trial 8 pruned.
[I 2020-12-16 12:45:39,616] Trial 9 pruned.
[I 2020-12-16 12:45:40,120] Trial 10 pruned.
[I 2020-12-16 12:45:40,632] Trial 11 pruned.
[I 2020-12-16 12:45:41,125] Trial 12 pruned.
[I 2020-12-16 12:45:41,631] Trial 13 pruned.
[I 2020-12-16 12:45:46,474] Trial 14 finished with value: 0.9125 and parameters: {'n_layers': 2, 'n_units_l0': 114, 'dropout_l0': 0.47609619687772087, 'n_units_l1': 110, 'dropout_l1': 0.2013791430520977, 'optimizer': 'RMSprop', 'lr': 0.004957851067249797}. Best is trial 0 with value: 0.94140625.
[I 2020-12-16 12:45:46,981] Trial 15 pruned.
[I 2020-12-16 12:45:51,662] Trial 16 finished with value: 0.91640625 and parameters: {'n_layers': 1, 'n_units_l0': 92, 'dropout_l0': 0.24436719310483768, 'optimizer': 'Adam', 'lr': 0.0008791655370693048}. Best is trial 0 with value: 0.94140625.
[I 2020-12-16 12:45:52,156] Trial 17 pruned.
[I 2020-12-16 12:45:56,888] Trial 18 finished with value: 0.9265625 and parameters: {'n_layers': 1, 'n_units_l0': 120, 'dropout_l0': 0.37347525364157425, 'optimizer': 'Adam', 'lr': 0.0016234428549713003}. Best is trial 0 with value: 0.94140625.
[I 2020-12-16 12:45:57,407] Trial 19 pruned.
[I 2020-12-16 12:45:57,905] Trial 20 pruned.
[I 2020-12-16 12:46:02,657] Trial 21 finished with value: 0.92890625 and parameters: {'n_layers': 1, 'n_units_l0': 105, 'dropout_l0': 0.3667471215162053, 'optimizer': 'Adam', 'lr': 0.0016493448522204729}. Best is trial 0 with value: 0.94140625.
[I 2020-12-16 12:46:03,136] Trial 22 pruned.
[I 2020-12-16 12:46:07,975] Trial 23 finished with value: 0.9203125 and parameters: {'n_layers': 1, 'n_units_l0': 107, 'dropout_l0': 0.3104102935998286, 'optimizer': 'Adam', 'lr': 0.002126526881842769}. Best is trial 0 with value: 0.94140625.
[I 2020-12-16 12:46:08,497] Trial 24 pruned.
[I 2020-12-16 12:46:08,974] Trial 25 pruned.
[I 2020-12-16 12:46:13,731] Trial 26 finished with value: 0.94453125 and parameters: {'n_layers': 1, 'n_units_l0': 128, 'dropout_l0': 0.34788254164893323, 'optimizer': 'Adam', 'lr': 0.002079906503061857}. Best is trial 26 with value: 0.94453125.
[I 2020-12-16 12:46:14,225] Trial 27 pruned.
[I 2020-12-16 12:46:18,887] Trial 28 finished with value: 0.9421875 and parameters: {'n_layers': 1, 'n_units_l0': 55, 'dropout_l0': 0.291062576635172, 'optimizer': 'RMSprop', 'lr': 0.0027551395610581923}. Best is trial 26 with value: 0.94453125.
[I 2020-12-16 12:46:23,577] Trial 29 finished with value: 0.93203125 and parameters: {'n_layers': 1, 'n_units_l0': 55, 'dropout_l0': 0.22998547636120767, 'optimizer': 'RMSprop', 'lr': 0.0034219419957648507}. Best is trial 26 with value: 0.94453125.
[I 2020-12-16 12:46:24,058] Trial 30 pruned.
[I 2020-12-16 12:46:28,688] Trial 31 finished with value: 0.95 and parameters: {'n_layers': 1, 'n_units_l0': 58, 'dropout_l0': 0.22757601916029566, 'optimizer': 'RMSprop', 'lr': 0.0026066475943559322}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:46:31,912] Trial 32 pruned.
[I 2020-12-16 12:46:36,498] Trial 33 finished with value: 0.92734375 and parameters: {'n_layers': 1, 'n_units_l0': 53, 'dropout_l0': 0.24493914791090587, 'optimizer': 'RMSprop', 'lr': 0.0022433666174366757}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:46:36,941] Trial 34 pruned.
[I 2020-12-16 12:46:37,423] Trial 35 pruned.
[I 2020-12-16 12:46:38,803] Trial 36 pruned.
[I 2020-12-16 12:46:40,677] Trial 37 pruned.
[I 2020-12-16 12:46:45,239] Trial 38 finished with value: 0.93828125 and parameters: {'n_layers': 1, 'n_units_l0': 59, 'dropout_l0': 0.26171687096981466, 'optimizer': 'RMSprop', 'lr': 0.005547605539329795}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:46:45,714] Trial 39 pruned.
[I 2020-12-16 12:46:46,200] Trial 40 pruned.
[I 2020-12-16 12:46:50,787] Trial 41 finished with value: 0.9390625 and parameters: {'n_layers': 1, 'n_units_l0': 61, 'dropout_l0': 0.21670193277665503, 'optimizer': 'RMSprop', 'lr': 0.0045596203638192685}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:46:55,364] Trial 42 finished with value: 0.934375 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'dropout_l0': 0.20006560316277433, 'optimizer': 'RMSprop', 'lr': 0.002257958293766287}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:47:00,017] Trial 43 finished with value: 0.93828125 and parameters: {'n_layers': 1, 'n_units_l0': 74, 'dropout_l0': 0.20849624876486633, 'optimizer': 'RMSprop', 'lr': 0.007915237362307334}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:47:04,624] Trial 44 finished with value: 0.940625 and parameters: {'n_layers': 1, 'n_units_l0': 62, 'dropout_l0': 0.23403786900217866, 'optimizer': 'RMSprop', 'lr': 0.004234566290464568}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:47:05,080] Trial 45 pruned.
[I 2020-12-16 12:47:05,577] Trial 46 pruned.
[I 2020-12-16 12:47:06,056] Trial 47 pruned.
[I 2020-12-16 12:47:08,388] Trial 48 pruned.
[I 2020-12-16 12:47:08,881] Trial 49 pruned.
[I 2020-12-16 12:47:09,373] Trial 50 pruned.
[I 2020-12-16 12:47:14,148] Trial 51 finished with value: 0.93359375 and parameters: {'n_layers': 1, 'n_units_l0': 55, 'dropout_l0': 0.22070529407723355, 'optimizer': 'RMSprop', 'lr': 0.004027801135954042}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:47:14,656] Trial 52 pruned.
[I 2020-12-16 12:47:15,125] Trial 53 pruned.
[I 2020-12-16 12:47:16,540] Trial 54 pruned.
[I 2020-12-16 12:47:16,986] Trial 55 pruned.
[I 2020-12-16 12:47:17,912] Trial 56 pruned.
[I 2020-12-16 12:47:22,628] Trial 57 finished with value: 0.93984375 and parameters: {'n_layers': 1, 'n_units_l0': 86, 'dropout_l0': 0.23736786614081623, 'optimizer': 'RMSprop', 'lr': 0.00423093614640637}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:47:27,403] Trial 58 finished with value: 0.9421875 and parameters: {'n_layers': 1, 'n_units_l0': 99, 'dropout_l0': 0.38830619889586865, 'optimizer': 'Adam', 'lr': 0.006924561178193748}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:47:32,120] Trial 59 finished with value: 0.9484375 and parameters: {'n_layers': 1, 'n_units_l0': 111, 'dropout_l0': 0.38705242387370836, 'optimizer': 'Adam', 'lr': 0.009155836162103711}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:47:32,689] Trial 60 pruned.
[I 2020-12-16 12:47:37,407] Trial 61 finished with value: 0.94375 and parameters: {'n_layers': 1, 'n_units_l0': 125, 'dropout_l0': 0.3858039999489952, 'optimizer': 'Adam', 'lr': 0.009233419774183101}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:47:42,153] Trial 62 finished with value: 0.940625 and parameters: {'n_layers': 1, 'n_units_l0': 100, 'dropout_l0': 0.3916936069296789, 'optimizer': 'Adam', 'lr': 0.010977499054678656}. Best is trial 31 with value: 0.95.
[I 2020-12-16 12:47:44,090] Trial 63 pruned.
[I 2020-12-16 12:47:48,869] Trial 64 finished with value: 0.953125 and parameters: {'n_layers': 1, 'n_units_l0': 128, 'dropout_l0': 0.3611061423366454, 'optimizer': 'Adam', 'lr': 0.014166205537645606}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:47:53,637] Trial 65 finished with value: 0.9421875 and parameters: {'n_layers': 1, 'n_units_l0': 128, 'dropout_l0': 0.3639248110155308, 'optimizer': 'Adam', 'lr': 0.007408935734545433}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:47:58,368] Trial 66 finished with value: 0.94765625 and parameters: {'n_layers': 1, 'n_units_l0': 128, 'dropout_l0': 0.362136529096683, 'optimizer': 'Adam', 'lr': 0.01401582075050741}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:48:03,164] Trial 67 finished with value: 0.93984375 and parameters: {'n_layers': 1, 'n_units_l0': 124, 'dropout_l0': 0.38502615042003097, 'optimizer': 'Adam', 'lr': 0.014969532298011193}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:48:04,163] Trial 68 pruned.
[I 2020-12-16 12:48:08,911] Trial 69 finished with value: 0.94375 and parameters: {'n_layers': 1, 'n_units_l0': 116, 'dropout_l0': 0.3478012330551283, 'optimizer': 'Adam', 'lr': 0.009544141596546844}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:48:13,186] Trial 70 pruned.
[I 2020-12-16 12:48:18,011] Trial 71 finished with value: 0.93984375 and parameters: {'n_layers': 1, 'n_units_l0': 118, 'dropout_l0': 0.40685044190391284, 'optimizer': 'Adam', 'lr': 0.00946449765992212}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:48:22,785] Trial 72 finished with value: 0.95078125 and parameters: {'n_layers': 1, 'n_units_l0': 122, 'dropout_l0': 0.3621228493312689, 'optimizer': 'Adam', 'lr': 0.01406629458592396}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:48:27,623] Trial 73 finished with value: 0.95234375 and parameters: {'n_layers': 1, 'n_units_l0': 124, 'dropout_l0': 0.37607777259106384, 'optimizer': 'Adam', 'lr': 0.013577391674453662}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:48:28,597] Trial 74 pruned.
[I 2020-12-16 12:48:33,306] Trial 75 finished with value: 0.9421875 and parameters: {'n_layers': 1, 'n_units_l0': 121, 'dropout_l0': 0.39561066024349484, 'optimizer': 'Adam', 'lr': 0.015003019809588142}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:48:33,823] Trial 76 pruned.
[I 2020-12-16 12:48:36,222] Trial 77 pruned.
[I 2020-12-16 12:48:38,130] Trial 78 pruned.
[I 2020-12-16 12:48:39,094] Trial 79 pruned.
[I 2020-12-16 12:48:43,863] Trial 80 finished with value: 0.9515625 and parameters: {'n_layers': 1, 'n_units_l0': 123, 'dropout_l0': 0.3701770416163666, 'optimizer': 'Adam', 'lr': 0.0058121297178741396}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:48:44,834] Trial 81 pruned.
[I 2020-12-16 12:48:49,805] Trial 82 finished with value: 0.94609375 and parameters: {'n_layers': 1, 'n_units_l0': 125, 'dropout_l0': 0.3717312741635504, 'optimizer': 'Adam', 'lr': 0.008509641579091025}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:48:54,570] Trial 83 finished with value: 0.93046875 and parameters: {'n_layers': 1, 'n_units_l0': 114, 'dropout_l0': 0.36873165533025154, 'optimizer': 'Adam', 'lr': 0.011294859066626705}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:48:59,669] Trial 84 finished with value: 0.946875 and parameters: {'n_layers': 1, 'n_units_l0': 128, 'dropout_l0': 0.3777775806992278, 'optimizer': 'Adam', 'lr': 0.016107177444385175}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:49:01,193] Trial 85 pruned.
[I 2020-12-16 12:49:01,714] Trial 86 pruned.
[I 2020-12-16 12:49:02,667] Trial 87 pruned.
[I 2020-12-16 12:49:07,423] Trial 88 finished with value: 0.94453125 and parameters: {'n_layers': 1, 'n_units_l0': 128, 'dropout_l0': 0.33645355934278626, 'optimizer': 'Adam', 'lr': 0.01829470511630487}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:49:07,932] Trial 89 pruned.
[I 2020-12-16 12:49:08,916] Trial 90 pruned.
[I 2020-12-16 12:49:09,410] Trial 91 pruned.
[I 2020-12-16 12:49:14,405] Trial 92 finished with value: 0.93203125 and parameters: {'n_layers': 1, 'n_units_l0': 128, 'dropout_l0': 0.3389493985067478, 'optimizer': 'Adam', 'lr': 0.018204862802094147}. Best is trial 64 with value: 0.953125.
[I 2020-12-16 12:49:19,213] Trial 93 finished with value: 0.95390625 and parameters: {'n_layers': 1, 'n_units_l0': 120, 'dropout_l0': 0.3267108665822297, 'optimizer': 'Adam', 'lr': 0.012577741647390017}. Best is trial 93 with value: 0.95390625.
[I 2020-12-16 12:49:19,718] Trial 94 pruned.
[I 2020-12-16 12:49:24,497] Trial 95 finished with value: 0.94375 and parameters: {'n_layers': 1, 'n_units_l0': 122, 'dropout_l0': 0.3271041259661316, 'optimizer': 'Adam', 'lr': 0.013669761471998953}. Best is trial 93 with value: 0.95390625.
[I 2020-12-16 12:49:29,244] Trial 96 finished with value: 0.94375 and parameters: {'n_layers': 1, 'n_units_l0': 123, 'dropout_l0': 0.3956435902953432, 'optimizer': 'Adam', 'lr': 0.011775528846939446}. Best is trial 93 with value: 0.95390625.
[I 2020-12-16 12:49:29,752] Trial 97 pruned.
[I 2020-12-16 12:49:30,233] Trial 98 pruned.
[I 2020-12-16 12:49:30,728] Trial 99 pruned.
```

**Comment by hvy** [comment]
Thanks for the verification, do you happen to know it if works with PyTorch lightning and the other libraries as well? And ouch, conflicts now with the recent change to `setup.py`.

**Comment by crcrpar** [comment]
worked.

---

Ignite

```
~/ghq/github.com/optuna/optuna hotfix/skip-fastai-example
optuna ❯ python examples/pytorch_ignite_simple.py
[I 2020-12-16 15:26:47,620] A new study created in memory with name: no-name-ff285709-d471-4a25-b21b-8746c69401fc
Epoch: 1 Validation accuracy: 0.78
Epoch: 2 Validation accuracy: 0.88
Epoch: 3 Validation accuracy: 0.92
Epoch: 4 Validation accuracy: 0.93
Epoch: 5 Validation accuracy: 0.94
Epoch: 6 Validation accuracy: 0.95
Epoch: 7 Validation accuracy: 0.95
Epoch: 8 Validation accuracy: 0.96
Epoch: 9 Validation accuracy: 0.96
Epoch: 10 Validation accuracy: 0.96
[I 2020-12-16 15:27:15,539] Trial 0 finished with value: 0.958 and parameters: {'dropout_rate': 0.04773091612220537, 'fc2_input_dim': 61}. Best is trial 0 with value: 0.958.
Epoch: 1 Validation accuracy: 0.61
Epoch: 2 Validation accuracy: 0.83
Epoch: 3 Validation accuracy: 0.85
Epoch: 4 Validation accuracy: 0.90
Epoch: 5 Validation accuracy: 0.91
Epoch: 6 Validation accuracy: 0.92
Epoch: 7 Validation accuracy: 0.93
Epoch: 8 Validation accuracy: 0.93
Epoch: 9 Validation accuracy: 0.93
Epoch: 10 Validation accuracy: 0.93
[I 2020-12-16 15:27:32,103] Trial 1 finished with value: 0.93 and parameters: {'dropout_rate': 0.7742371779573348, 'fc2_input_dim': 59}. Best is trial 0 with value: 0.958.
Epoch: 1 Validation accuracy: 0.78
Epoch: 2 Validation accuracy: 0.87
Epoch: 3 Validation accuracy: 0.91
Epoch: 4 Validation accuracy: 0.93
Epoch: 5 Validation accuracy: 0.93
Epoch: 6 Validation accuracy: 0.94
Epoch: 7 Validation accuracy: 0.94
Epoch: 8 Validation accuracy: 0.95
Epoch: 9 Validation accuracy: 0.95
Epoch: 10 Validation accuracy: 0.95
[I 2020-12-16 15:27:48,155] Trial 2 finished with value: 0.951 and parameters: {'dropout_rate': 0.04285526039378007, 'fc2_input_dim': 77}. Best is trial 0 with value: 0.958.
Epoch: 1 Validation accuracy: 0.74
Epoch: 2 Validation accuracy: 0.88
Epoch: 3 Validation accuracy: 0.91
Epoch: 4 Validation accuracy: 0.91
Epoch: 5 Validation accuracy: 0.92
Epoch: 6 Validation accuracy: 0.94
Epoch: 7 Validation accuracy: 0.94
Epoch: 8 Validation accuracy: 0.94
Epoch: 9 Validation accuracy: 0.95
Epoch: 10 Validation accuracy: 0.95
```

Lightning
```
~/ghq/github.com/optuna/optuna hotfix/skip-fastai-example 1m 54s
optuna ❯ python examples/pytorch_lightning_simple.py
[I 2020-12-16 15:28:42,560] A new study created in memory with name: no-name-7bd59e20-019d-45c7-ba79-3ba51e59ee9e
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type | Params
-------------------------------
0 | model | Net  | 94 K
/home/masaki/.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
/home/masaki/.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Epoch 9: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 476/476 [00:12<00:00, 38.54it/s, loss=0.128]
[I 2020-12-16 15:30:54,538] Trial 0 finished with value: 0.9732142686843872 and parameters: {'n_layers': 2, 'dropout': 0.34892504823683423, 'n_units_l0': 103, 'n_units_l1': 122}. Best is trial 0 with value: 0.9732142686843872.
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type | Params
-------------------------------
0 | model | Net  | 13 K
Epoch 5:  82%|████████████████████████████████████████████████████████████████████████████████████████████████▉                     | 391/476 [00:12<00:02, 31.00it/s, loss=1.436]
```

**Review by hvy — APPROVED** [review]
Thanks for verifying the examples. They seem to work and changes otherwise LGTM!

**Pull request merged**
