### PR TITLE
Fix `matplotlib.plot_parallel_coordinate` with log distributions

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Resolve https://github.com/optuna/optuna/issues/3370

## Description of the changes

I think we do not need to take the log of parameters in this visualisation method except for line collection.

By this PR, the plot function generates

Screenshot 2022-03-11 at 6 05 22

As a reference, plotly shows the following plot:

Screenshot 2022-03-11 at 6 07 33

### Code

```python
from optuna.study import create_study
from optuna.visualization.matplotlib import plot_parallel_coordinate
from optuna.distributions import LogUniformDistribution
from optuna.trial import create_trial
import matplotlib.pyplot as plt


study_log_params = create_study()
study_log_params.add_trial(
    create_trial(
        value=0.0,
        params={"param_a": 1e-6, "param_b": 10},
        distributions={
            "param_a": LogUniformDistribution(1e-7, 1e-2),
            "param_b": LogUniformDistribution(1, 1000),
        },
    )
)
study_log_params.add_trial(
    create_trial(
        value=1.0,
        params={"param_a": 2e-5, "param_b": 200},
        distributions={
            "param_a": LogUniformDistribution(1e-7, 1e-2),
            "param_b": LogUniformDistribution(1, 1000),
        },
    )
)
study_log_params.add_trial(
    create_trial(
        value=0.1,
        params={"param_a": 1e-4, "param_b": 30},
        distributions={
            "param_a": LogUniformDistribution(1e-7, 1e-2),
            "param_b": LogUniformDistribution(1, 1000),
        },
    )
)
figure = plot_parallel_coordinate(study_log_params)
plt.savefig("lovely.png")
```

Adding `plt.savefig(sys.stdout.buffer)` to other matplotlib will be a followup.

### CODE REVIEW

**Comment by nzw0301** [comment]
As a result, the plot is like
Screenshot 2022-03-11 at 0 54 10


HOWEVER, the white line on the `param_a` axis is located incorrectly. The line should be above `10^-5`.

**Comment by himkt** [comment]
Thank you for the fix. Looks solid and I confirmed that the error was fixed.
How about renaming `_values` to some concrete name? (e.g. `values_for_lc`)

**Review by HideakiImamura — APPROVED** [review]
Thank for the PR. I confirmed that the introduced test fails with the current implementation and have fixed with the new implmentation. LGTM!

**Comment by nzw0301** [comment]
@himkt Thanks. I've renamed it by following your suggestion.

**Review by himkt — APPROVED** [review]
LGTM. Sorry for the late.

**Pull request merged**
