### PR TITLE
Fix `RegretBoundEvaluator` document

### PR DESCRIPTION
**Pull request by not522**
## Motivation

The implementation of `RegretBoundEvaluator` was updated by #5241, but the document update for the arguments has been missed.

## Description of the changes

- Update the argument documentation to match the implementation.
  - Removing `gp` and `min_lcb_n_additional_samples`
  - Adding `seed`

### CODE REVIEW

**Comment by not522** [comment]
@eukaryo @nabenabe0928 @kAIto47802 Could you review this PR?

**Review by kAIto47802 — APPROVED** [review]
Thank you for fixing, LGTM!

**Review by nabenabe0928 — APPROVED** [review]
LGTM!

**Review by eukaryo — APPROVED** [review]
LGTM

**Pull request merged**
