### PR TITLE
Added see also section for best_trial

### PR DESCRIPTION
**Pull request by divyanshugit**
## Motivation
Partially fixed https://github.com/optuna/optuna/issues/2940.

## Description of the changes
Added a section for see also which redirects to the tutorial of [Re-use the best values](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/010_reuse_best_trial.html) in `optuna/optuna/study/study.py`

### CODE REVIEW

**Comment by himkt** [comment]
Hello @divyanshugit, thank you for the PR. Welcome to Optuna!

You put the link in `Study.best_trials`, but, the tutorial describes how to use `Study.best_trial`.
I think the see also section you added should be moved to `Study.best_trial`.

**Comment by divyanshugit** [comment]
> Hello @divyanshugit, thank you for the PR. Welcome to Optuna!
> 
> You put the link in `Study.best_trials`, but, the tutorial describes how to use `Study.best_trial`. I think the see also section you added should be moved to `Study.best_trial`.

Sorry, my bad. Fixed it.

**Review by himkt — APPROVED** [review]
Looks nice!

**Review by toshihikoyanase — APPROVED** [review]
LGTM. Thank you for your contribution!

image

By the way, the re-use the best values may be improved in terms of the following points:
- The title can be `re-use the best parameters` instead of `re-use the best values`. This is because the best value means the best objective value in most of the Optuna references.
- The tutorial can mention `Study.best_trials` for multi-objective optimization.
But, I don't think they are in the scope of this PR.

**Comment by toshihikoyanase** [comment]
@himkt has already approved this PR, so let me merge it.

**Comment by divyanshugit** [comment]
> * The title can be `re-use the best parameters` instead of `re-use the best values`. This is because the best value means the best objective value in most of the Optuna references.
> * The tutorial can mention `Study.best_trials` for multi-objective optimization.

@toshihikoyanase If there are no issues related to this, then Should I create one and fix it?

**Comment by toshihikoyanase** [comment]
@divyanshugit Thank you for your response. I don't think existing issues track them, so it will be a great help if you kindly create a new one.

**Pull request merged**
