### PR TITLE
Remove Python3.9 from example CI

### PR DESCRIPTION
**Pull request by crcrpar**
Python3.9 example job has failed due to segmentation fault: https://github.com/optuna/optuna/actions/workflows/examples.yml.

### CODE REVIEW

**Comment by crcrpar** [comment]
The failure of Integration test is expected. Ref: #2379

**Comment by hvy** [comment]
Is it better to just revert https://github.com/optuna/optuna/pull/2222 (or reflect the changes in `setup.py`)?

**Comment by crcrpar** [comment]
sounds good

**Comment by toshihikoyanase** [comment]
@hvy Let me assign the PR since you have already commented on it.

**Comment by hvy** [comment]
The changes LGTM besides the `setup.py` changes.

**Comment by crcrpar** [comment]
Oh wait, I thought that you're going to revert the #2222.

**Comment by hvy** [comment]
Sorry, seems like there were some lossy communication. Create a revert PR https://github.com/optuna/optuna/pull/2382.

**Pull request closed without merging**
