### PR TITLE
Refactor _grid.py

### PR DESCRIPTION
**Pull request by eukaryo**
## Motivation

I want to refactor and speed-up the grid-sampler.

## Description of the changes

- I utilized `before_trial`. Codes in `infer_relative_search_space` were moved into `before_trial`.
- For the first N trials, the pre-shuffled `_all_grids` were to be executed in order, based on ~`_trial_id`~`trial.number`.
  - This change reduces the number of calls of `_get_unvisited_grid_ids` function, which is heavy and tends to output the same parameters multiple times.
  - This change may resolve or mitigate https://github.com/optuna/optuna/issues/4627 .

### CODE REVIEW

**Comment by c-bata** [comment]
@Alnusjaponica @not522 Could you review this PR?

**Comment by not522** [comment]
Could you use `trial.number` instead of `trial._trial_id`? `_trial_id` can be larger than the number of trials.

```python
import optuna

storage = "sqlite:///tmp.db"

study1 = optuna.create_study(storage=storage)
study1.optimize(lambda t: 0, n_trials=10)

study2 = optuna.create_study(storage=storage)
study2.optimize(lambda t: 0, n_trials=10)

print(study2.trials[-1]._trial_id)  # 20
```

**Comment by eukaryo** [comment]
Thank you for your review and suggestion! I revised the code to use `trial.number`.

**Comment by c-bata** [comment]
Let me reassign the reviewer to @cross32768 since @Alnusjaponica  is already assigned many PR reviews.

**Review by cross32768 — APPROVED** [review]
LGTM!

**Review by not522 — APPROVED** [review]
LGTM!

**Pull request merged**
