### PR TITLE
Rename filenames for `JournalFileStorage` in  documents and a tutorial

### PR DESCRIPTION
**Pull request by eukaryo**
## Motivation

`journal.log` is currently used as the filename in example codes of documents and a tutorial of `JournalFileStorage`, but I think the name is ambiguous and confusing.

## Description of the changes

I renamed `journal.log` to ~`JournalFileStorageLog.jsonl`~ `journal_file_storage_jsonl.log`, in example codes of documents and a tutorial.

### CODE REVIEW

**Review by HideakiImamura — COMMENTED** [review]
This is not a strong opinion, but the camel case in the filename is not standard. How about "journal_file_storage_log.jsonl"?

**Comment by HideakiImamura** [comment]
@porink0424 Could you review this PR?

**Comment by nabenabe0928** [comment]
I have the same opinion.
I would use `-` instead of `_` though.

https://github.com/optuna/optuna/pull/5535#pullrequestreview-2150301950

**Comment by eukaryo** [comment]
I think Optuna Dashboard may expects `.log` to open a file, so I renamed with `journal_file_storage_jsonl.log`.

**Review by porink0424 — APPROVED** [review]
LGTM!

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
