### PR TITLE
Do not wait for next heartbeat on study completion.

### LINKED ISSUE #2685: Waiting for Heartbeat
## Expected behavior

After `study.optimize` with a high heartbeat interval (e.g. 60s) finishes running trials, it should exit almost immediately. 

## Environment

- Optuna version: 2.7.0
- Python version: 3.9
- OS: Fedora 33
- (Optional) Other libraries and their versions: PostgreSQL

## Observed Behavior
Instead of exiting immediately, the main thread tries to join with the heartbeat thread, which only completes after the next scheduled hearbeat. This can lead to high delays where the program does basically nothing.

## Steps to reproduce

1. Create a RDB storage with a heartbeat interval of 60s.
2. Create a fast objective, a study and call `study.optimize(n_trials=1)`.
3. Measure runtime.

## Additional context (optional)
It might be better to use the [`wait(timeout=...)`](https://docs.python.org/3/library/threading.html#threading.Event.wait) method [here](https://github.com/optuna/optuna/blob/2fd68d0102a22e76b5a4a142cc87722d92dcf667/optuna/_optimize.py#L340).

### PR DESCRIPTION
**Pull request by Turakar**
Fixes #2685. This PR contains the proposed change exactly.

### CODE REVIEW

**Comment by hvy** [comment]
@Turakar, thanks you for the quick PR!

@HideakiImamura could you also have/ a look at this PR?

**Review by HideakiImamura — APPROVED** [review]
Looks solid! LGTM!

**Review by hvy — APPROVED** [review]
Sorry for the delayed response. Thanks a lot for the PR and LGTM!

It also seems like `Event.wait` is efficiently implemented in Python 3.

**Comment by Turakar** [comment]
Just a quick query: When do you plan to release v2.8.0?

**Comment by hvy** [comment]
Although not fixed, we are planning a release in July. Do you have some preference?

**Comment by Turakar** [comment]
As early as possible, but I guess I will go for nightly or some custom patch then.

**Pull request merged**
