### PR TITLE
Support BoTorch >= 0.4.0

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Some of BoTorch's API used in optuna has been changed since the latest stable version, v0.4.0. Please see also #2381.

## Description of the changes

- Replace the old argument with the new one
- Specify the version of botorch

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
@crcrpar @HideakiImamura Could you review this PR?

**Review by HideakiImamura — APPROVED** [review]
Looks perfect! LGTM!

**Comment by crcrpar** [comment]
Sorry, but I'm inappropriate as a reviewer due to the lack of familiarity.

**Comment by crcrpar** [comment]
@HideakiImamura @hvy @toshihikoyanase @himkt @keisuke-umezawa @c-bata Could some of you kindly review this on my behalf?

**Comment by HideakiImamura** [comment]
@himkt Could you review this PR if you have time?

**Review by himkt — APPROVED** [review]
Let me approve this PR since the example works well in my environment and tests are passed. Thank you @nzw0301 for the update!

**Pull request merged**
