### PR TITLE
Add trial.user_attrs to pareto_front hover text

### PR DESCRIPTION
**Pull request by kasparthommen**
Add trial.user_attrs to pareto_front hover text if trial.user_attrs has entries.

This implements https://github.com/optuna/optuna/issues/3081.

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
Thank you for your PR! I think this feature helps data analysis on notebooks while keeping the plot clean.

@Crissman @keisuke-umezawa Could you review this PR, please?

@nzw0301 I guess you may have comments on this feature since you created some visualization issues. Please feel free to add comments.

**Comment by nzw0301** [comment]
Great! How about dealing with a not JSON serialisable object? For example, the following code contains such an object.

```python
import optuna
import numpy as np

def objective(trial):
    x = trial.suggest_float("x", 0, 5)
    y = trial.suggest_float("y", 0, 3)

    v0 = 4 * x ** 2 + 4 * y ** 2
    v1 = (x - 5) ** 2 + (y - 5) ** 2
    trial.set_user_attr("some_debug_info", "foo_bar")
    trial.set_user_attr("model", np.random.rand(1))  # not json serialisable
    return v0, v1


study = optuna.create_study(directions=["minimize", "minimize"])
study.optimize(objective, n_trials=50)

fig = optuna.visualization.plot_pareto_front(study)
fig.show()
```

I suppose that a simple way is to call `str` if an object is not JSON serialisable.

**Comment by kasparthommen** [comment]
@nzw0301 Very good point! I have correspondingly updated the PR and added unit tests that verify that such cases are now handled correctly. Please review.

**Comment by keisuke-umezawa** [comment]
@kasparthommen Seems good to me! Could you add pareto_front images to show the difference?

**Comment by kasparthommen** [comment]
@keisuke-umezawa Certainly - just here or in the official docs?

**Comment by nzw0301** [comment]
Here, I suppose.

**Comment by kasparthommen** [comment]
Sure, I'm using the following code to produce the examples below:

```python
import numpy as np
import optuna
import plotly


def objective(trial):
    x = trial.suggest_float("x", 0, 5)
    y = trial.suggest_float("y", 0, 3)

    v0 = 4 * x ** 2 + 4 * y ** 2
    v1 = (x - 5) ** 2 + (y - 5) ** 2
    trial.set_user_attr("some_debug_info", "foo_bar")
    trial.set_user_attr("model", np.random.rand(1))
    return v0, v1


study = optuna.create_study(directions=["minimize", "minimize"])
study.optimize(objective, n_trials=50)

fig = optuna.visualization.plot_pareto_front(study)
plotly.offline.plot(fig, 'pareto.html')
```

Without `user_attrs` (i.e., after commenting out the two `trial.set_user_attr(...)`):
image


With `user_attrs`:
image

**Review by keisuke-umezawa — APPROVED** [review]
Thank you for the quick update! LGTM.

**Review by Crissman — APPROVED** [review]
Nice improvement. 👍

**Pull request merged**
