### PR TITLE
Delete tensorboard integration for migration to optuna-integration

### PR DESCRIPTION
**Pull request by dheemantha-bhat**
### Motivation
**Progress**  https://github.com/optuna/optuna/issues/4484

**Description of the changes**
Move integration/tensorboard.py and its test from optuna/optuna.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
Thanks for the PR. Basically, LGTM. Could you apply the formatter? You can execute the formatter by running `bash ./formats.sh` after `pip install -e ".[checking]"`. 

By the way, we commuters are now on vacation for the New Year's vacations. Therefore, the review may be delayed until the New Year. We apologize for any inconvenience.

**Review by not522 — APPROVED** [review]
Thank you for your PR! LGTM.
Note: The CI fail is not related this PR.

**Comment by not522** [comment]
@HideakiImamura Could you review this PR?

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
