### PR TITLE
Make `set_study_directions()` of `RedisStorage` faster

### PR DESCRIPTION
**Pull request by masap**
## Description of the changes
By using `mset()` instead of `pipeline()`, this patch improve performance of DB access related process in `set_study_directions()` from 322(usec) to 268(usec).

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

chart

### CODE REVIEW

**Comment by hvy** [comment]
@himkt , @keisuke-umezawa could you review this change as well together with https://github.com/optuna/optuna/pull/3392?

**Review by keisuke-umezawa — APPROVED** [review]
LGTM!

**Comment by keisuke-umezawa** [comment]
Note: https://stackoverflow.com/questions/54900928/should-i-always-use-pipelining-when-there-are-more-than-1-command-in-redis

**Comment by masap** [comment]
Fixed conflict.

**Review by himkt — APPROVED** [review]
Although the test coverage slightly degraded, I believe this change doesn't contribute to the change. Let me merge based on the discussion of https://github.com/optuna/optuna/pull/3391. Thank you!

https://app.codecov.io/gh/optuna/optuna/compare/3393/changes

**Comment by masap** [comment]
Thanks !

**Pull request merged**
