### PR TITLE
Add `matplotlib.plot_parallel_coordinate` example

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

See #2091

## Description of the changes

Add the example that is the same code as plotly's one.

### CODE REVIEW

**Review by crcrpar — APPROVED** [review]
Looks good, thanks.

image

**Comment by nzw0301** [comment]
@crcrpar  Thank you for your review! I'm a bit concern about the left-most xlabel's position. It is cut off, so sphinx or optuna's plot function may need to fix it.


Reference: [Why is my xlabel cut off in my matplotlib plot?](https://stackoverflow.com/questions/6774086/why-is-my-xlabel-cut-off-in-my-matplotlib-plot)

**Comment by crcrpar** [comment]
Yeah, the truncation of x-labels is not cool.

But, I would not fix that by editing the current implementation like changing the configuration or calling `tight_layout`.
This is because those changes are unrelated to the logic of optuna.visualization functions.
If you kindly fix the truncation in the plot of the example code, I'd like you to do that in the example code with comments like
"getting ax and calling `tight_layout` to avoid the cut-off of x-labels in the figure".
Anyway, I don't think the fix necessary in this pull request.

**Review by hvy — APPROVED** [review]
Thank you for the PR as always. I agree with with @crcrpar that the label fix is outside the scope of this PR, and whether to use `tight_layout` might be an open discussion. LGTM!

**Pull request merged**
