### PR TITLE
Add README for creating alembic revision

### PR DESCRIPTION
**Pull request by himkt**
See https://github.com/optuna/optuna/issues/2279 for the detailed motivation.

This PR adds a guide for creating a revision file for alembic.

### CODE REVIEW

**Comment by himkt** [comment]
I want @toshihikoyanase to give me a review. 🙋

**Comment by hvy** [comment]
Great. @toshihikoyanase , @nzw0301 could you review this PR?

**Comment by nzw0301** [comment]
In my opinion, this procedure can be put on documentation, not under `optuna/storage/_rdb/`. I'm not sure who can find this file.

**Comment by toshihikoyanase** [comment]
I'm sorry for the delayed response. 

> In my opinion, this procedure can be put on documentation, not under optuna/storage/_rdb/. I'm not sure who can find this file...

Sounds reasonable. How about adding a new page to the [Optuna developer wiki](https://github.com/optuna/optuna/wiki)? 
The page can be updated by only the committers, but I don't think many developers want to update it.

**Comment by himkt** [comment]
I'm so sorry for the inactiveness. I agree with @toshihikoyanase and @nzw0301 that there is a better place to put this document. Let me close for now.

**Pull request closed without merging**
