### PR TITLE
Update PostgreSQL version in CI to latest

### PR DESCRIPTION
**Pull request by not522**
## Motivation
The current CI uses PostgreSQL 10.1, but it has already reached the end of life.
https://www.postgresql.org/support/versioning/

## Description of the changes
This PR updates the PostgreSQL version in CI to the latest.

### CODE REVIEW

**Comment by eukaryo** [comment]
@y0z Could you review this PR?

**Review by eukaryo — APPROVED** [review]
LGTM; btw, how about specifying a version? For example, “current minor” of just one major version before “latest” (15.8 for now) also seems moderate.

**Comment by not522** [comment]
Since the major version of PostgreSQL is updated every year, I think that CI tends to be stale if the version is fixed.

**Comment by eukaryo** [comment]
Thank you, I understand.

**Review by y0z — APPROVED** [review]
LGTM

**Pull request merged**
