### PR TITLE
Fix `parametrize_sampler`

### PR DESCRIPTION
**Pull request by not522**
## Motivation
Many samplers are accidentally excluded from `parametrize_sampler`.

## Description of the changes
Fix `parametrize_sampler`

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
@not522 Good catch! I'm sorry but I happened to introduce this bug on the test 😅 in #2928. Let me review this PR.

@himkt Could you review this PR, please?

**Comment by toshihikoyanase** [comment]
Let me remove the `bug` label since it is a bug in the unit tests, not a bug in Optuna itself.

**Review by toshihikoyanase — APPROVED** [review]
LGTM! Thank you for your fix.

I understand that `[1] + [2] if ... else [3]` is equivalent to `([1] + [2]) if ... else [3]` as follows:
```pyhon
>>> [1] + [2] if True else [3]
[1, 2]
>>> [1] + [2] if False else [3]
[3]
```

```python
>>> [1] + ([2] if True else [3])
[1, 2]
>>> [1] + ([2] if False else [3])
[1, 3]
```
So, the current master tests only the `BoTorchSampler` if Python version is >=3.7.0.

The number of test cases is as follows:
- `master`: 216
- this branch: 694

**Review by himkt — APPROVED** [review]
It's difficult to notice. 😅 Really nice catch @not522!

**Pull request merged**
