### PR TITLE
Ensure n_below is never negative in TPESampler

### LINKED ISSUE #5020: Better raising an error or making n_below zero for more robust splits
### Motivation

When spliting trials in TPESampler, n_below might be negative value [here](https://github.com/optuna/optuna/blob/master/optuna/samplers/_tpe/sampler.py#L606-L616).
The problem is that `sorted_trials[:n_below]` and `sorted_trials[n_below:]` may exhibit completely unexpected behavior when `n_below < 0`.

### Suggestion

To this end, I suppose that we should raise an error when we get `n_below < 0` during the process [here](https://github.com/optuna/optuna/blob/master/optuna/samplers/_tpe/sampler.py#L606-L616) or we should enforce `n_below >= 0` by using `max(n_below, 0)`.

In my opinion, the second solution is better as I assume that the order of adding trials to `samples_below` is sorted by priority.

It should look like the following after my modification:

```python
below_complete, above_complete = _split_complete_trials(complete_trials, study, n_below)
n_below = max(0, n_below - len(below_complete))
below_pruned, above_pruned = _split_pruned_trials(pruned_trials, study, n_below)
n_below = max(0, n_below - len(below_pruned))
below_infeasible, above_infeasible = _split_infeasible_trials(infeasible_trials, n_below)
```

### Additional context (optional)

_No response_

### PR DESCRIPTION
**Pull request by pplkit**
## Motivation
Fix for ensuring robust splits in TPESampler:

Previously, there was a potential issue where `n_below` could become negative, leading to unexpected behavior when splitting trials. 

Fixes #5020 

## Description of the changes
Ensured `n_below` is non-negative in TPESampler to prevent unexpected trial splits.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@nabenabe0928 @gen740 Could you review this PR?

**Review by nabenabe0928 — APPROVED** [review]
Thank you for the PR!
LGTM:)

**Comment by p1kit** [comment]
Hi, sorry I am new to open-source. 
Wanted to know what else is pending to get this PR merged? I can see that I have got 1 approval.

**Comment by nabenabe0928** [comment]
@p1kit 
We are working on other PRs and some other jobs in our company, so it will sometimes take time to be merged.
If you do not get any updates in two weeks, could you please remind us of this PR again?

**Comment by p1kit** [comment]
Sure , no worries :)

**Comment by p1kit** [comment]
bumping up

**Comment by nabenabe0928** [comment]
> bumping up @nabenabe0928

Thanks, it is more likely to be merged after our intensive PR durations where we concentrate on many minor fixes.
It will finish in one to two weeks, so we will merge yours after that!
Sorry for the inconvenience:(

**Review by gen740 — APPROVED** [review]
Sorry for my late reply, and thank you for the PR. LGTM!
However, some tests have failed. Please merge the master branch and ensure all tests pass before we proceed with merging this PR. Thanks!

**Pull request merged**
