### PR TITLE
Update action versions

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Try the rest of them in https://github.com/optuna/optuna/issues/4165:

- actions/cache@v2 -> v3 of `.github/workflows/mac-tests.yml`
- actions/upload-artifact@v2 -> v3
- actions/labeler@v2 -> v4
- codecov/codecov-action@v1 -> v3
- pypa/gh-action-pypi-publish@v1.1.0 -> v1

## Description of the changes

Update the versions as specified by the issue. I skimmed the release notes; they mainly fixed bugs and updated their dependencies.

### CODE REVIEW

**Comment by c-bata** [comment]
@Alnusjaponica Could you review this PR?

**Comment by nzw0301** [comment]
If necessary, I'd be happy to add updating `setup-python` since https://github.com/optuna/optuna/pull/4307 drops the changes.

**Comment by Alnusjaponica** [comment]
Sure! I work on this review this week. @c-bata 
Thank you for your suggestion. Now that #4301 is merged, we don't have to worry about `mac-tests` at all, do we? If that is the case, I think it will be natural to just recover the change in`.github/workflows/mac-tests.yml` within #4307. Otherwise, I would like you to update `setup-python` too. @nzw0301

**Comment by nzw0301** [comment]
@Alnusjaponica Thank you for your comment.

> we don't have to worry about mac-tests at all, do we?

Yes, I suppose so if #4307 merges or rebases onto the master branch to include https://github.com/optuna/optuna/pull/4301. Eiter way is okay for me.

**Comment by toshihikoyanase** [comment]
@Alnusjaponica @nzw0301 Thank you for the discussion on `mac-tests`. I understand that #4307 can update the `setup-python` version. I don't want to bother you, and I created a draft PR (https://github.com/optuna/optuna/pull/4343) to follow-up #4307. I just wanted to merge #4307 if possible since it was a PR from a first-time contributor.

**Comment by Alnusjaponica** [comment]
@toshihikoyanase Thank you for your follow-up.
@nzw0301 Thank you for your suggestion. Considering the situation, it seems better to update actions/cache@v2 -> v3 and action/setup-python@v2 -> v4 of `.github/workflows/mac-tests.yml`. Please note that we need to rebase onto the master branch to include both #4307 and #4344

**Comment by Alnusjaponica** [comment]
I read through release note of [actions/upload-artifact](https://github.com/actions/upload-artifact/releases), [actions/labeler](https://github.com/actions/labeler/releases), [codecov/codecov-action](https://github.com/codecov/codecov-action/releases), [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish/releases), and agree that they mainly fixed bugs and updated their dependencies.

Are you also going to update `.github/workflows/mac-tests.yml` in this PR?

**Comment by nzw0301** [comment]
@Alnusjaponica Thank you for checking them too! Sorry, I didn't push the change to update `actions/cache@v2` to `v3` in `.github/workflows/mac-tests.yml` I've pushed it too.

**Comment by Alnusjaponica** [comment]
@nzw0301 Thanks for your update. LGTM

**Review by Alnusjaponica — APPROVED** [review]

**Review by c-bata — COMMENTED** [review]
Thank you for the pull request! I confirmed that the all action versions are updated.

<details>

```
(venv) [x86_64] $ git grep codecov-action
.github/workflows/coverage.yml:      uses: codecov/codecov-action@v3
(venv) [x86_64] $ git grep labeler
.github/workflows/labeler.yml:    - uses: actions/labeler@v4
(venv) [x86_64] $ git grep actions/cache
.github/workflows/coverage.yml:      uses: actions/cache@v3
.github/workflows/mac-tests.yml:      uses: actions/cache@v3
.github/workflows/mac-tests.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-kurobako.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-kurobako.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-kurobako.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-kurobako.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-mo-kurobako.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-mo-kurobako.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-mo-kurobako.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-naslib.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-naslib.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-naslib.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-naslib.yml:      uses: actions/cache@v3
.github/workflows/performance-benchmarks-naslib.yml:      uses: actions/cache@v3
.github/workflows/speed-benchmarks.yml:      uses: actions/cache@v3
.github/workflows/sphinx-build.yml:      uses: actions/cache@v3
.github/workflows/sphinx-build.yml:      uses: actions/cache@v3
.github/workflows/tests-integration.yml:      uses: actions/cache@v3
.github/workflows/tests-mpi.yml:      uses: actions/cache@v3
.github/workflows/tests-storage.yml:      uses: actions/cache@v3
.github/workflows/tests-with-minimum-versions.yml:      uses: actions/cache@v3
.github/workflows/tests.yml:      uses: actions/cache@v3
(venv) [x86_64] $ git grep actions/upload-artifact
.github/workflows/performance-benchmarks-bayesmark.yml:      uses: actions/upload-artifact@v3
.github/workflows/performance-benchmarks-bayesmark.yml:      uses: actions/upload-artifact@v3
.github/workflows/performance-benchmarks-bayesmark.yml:      uses: actions/upload-artifact@v3
.github/workflows/performance-benchmarks-kurobako.yml:    - uses: actions/upload-artifact@v3
.github/workflows/performance-benchmarks-mo-kurobako.yml:    - uses: actions/upload-artifact@v3
.github/workflows/performance-benchmarks-naslib.yml:    - uses: actions/upload-artifact@v3
.github/workflows/sphinx-build.yml:    - uses: actions/upload-artifact@v3
.github/workflows/sphinx-build.yml:    - uses: actions/upload-artifact@v3
(venv) [x86_64] $ git grep actions/setup-python
.github/workflows/checks-integration.yml:    - uses: actions/setup-python@v2
.github/workflows/checks.yml:    - uses: actions/setup-python@v2
.github/workflows/coverage.yml:      uses: actions/setup-python@v2
.github/workflows/mac-tests.yml:      uses: actions/setup-python@v2
.github/workflows/mac-tests.yml:      uses: actions/setup-python@v2
.github/workflows/performance-benchmarks-bayesmark.yml:      uses: actions/setup-python@v2
.github/workflows/performance-benchmarks-bayesmark.yml:      uses: actions/setup-python@v2
.github/workflows/performance-benchmarks-kurobako.yml:      uses: actions/setup-python@v2
.github/workflows/performance-benchmarks-mo-kurobako.yml:      uses: actions/setup-python@v2
.github/workflows/performance-benchmarks-naslib.yml:      uses: actions/setup-python@v2
.github/workflows/pypi-publish.yml:      uses: actions/setup-python@v2
.github/workflows/reviewdog.yml:    - uses: actions/setup-python@v2
.github/workflows/speed-benchmarks.yml:      uses: actions/setup-python@v2
.github/workflows/sphinx-build.yml:    - uses: actions/setup-python@v2
.github/workflows/sphinx-build.yml:    - uses: actions/setup-python@v2
.github/workflows/tests-integration.yml:      uses: actions/setup-python@v2
.github/workflows/tests-mpi.yml:      uses: actions/setup-python@v2
.github/workflows/tests-storage.yml:      uses: actions/setup-python@v2
.github/workflows/tests-with-minimum-versions.yml:      uses: actions/setup-python@v2
.github/workflows/tests.yml:      uses: actions/setup-python@v2
(venv) [x86_64] $ git grep gh-action-pypi-publish
.github/workflows/pypi-publish.yml:      uses: pypa/gh-action-pypi-publish@v1
.github/workflows/pypi-publish.yml:      uses: pypa/gh-action-pypi-publish@v1
```

</details>

**Review by c-bata — APPROVED** [review]

**Pull request merged**
