### PR TITLE
Add a version constraint for Torch

### PR DESCRIPTION
**Pull request by nabenabe0928**
## Motivation

As Windows test fails now due to torch==2.2.0 ([issue](https://github.com/pytorch/pytorch/issues/118737)), I fix this problem by introducing the version constraint. 

## Description of the changes

I added the version constraint of `torch<2.2.0`.

### CODE REVIEW

**Comment by nabenabe0928** [comment]
@y0z @HideakiImamura Could you review this PR?

**Comment by HideakiImamura** [comment]
The CI fails due to the torchvision. The `torchvision` was also released in Jan 31. https://pypi.org/project/torchvision/

How about adding the constraint on the `torchvision` too?

**Comment by nabenabe0928** [comment]
@HideakiImamura The issue has been resolved!

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Review by y0z — APPROVED** [review]
LGTM

**Pull request merged**
