### PR TITLE
Reduce `SELECT` statements by passing `study_id` to `check_and_add` in `TrialParamModel`

### PR DESCRIPTION
**Pull request by porink0424**
## Motivation

This PR is motivated by the desire to improve performance by reducing the number of unnecessary `SELECT` statements being executed in the basic optimization flow.

## Description of the changes

- In `check_and_add` in `TrialParamModel`, `TrialModel.find_or_raise_by_id` was being called internally to retrieve `study_id` for getting `previous_record`, which was redundant as it was also being called in the flow of `set_trial_param`. This PR removes the redundant query by passing `study_id` as an argument.

## Verification of reduced `SELECT` statements

```python
import optuna
import logging

optuna.logging.set_verbosity(optuna.logging.WARNING)

study = optuna.create_study(storage="mysql+pymysql://optuna:password@127.0.0.1:3306/optuna")


def objective(trial: optuna.Trial) -> float:
    s = 0.0
    for i in range(8):
        s += trial.suggest_float(f"x{i}", 0.0, 1.0)
    return s


logging.basicConfig()
logging.getLogger("sqlalchemy.engine").setLevel(logging.INFO)
study.optimize(objective, n_trials=1)
```

```bash
❯ python mysql_optimize.py 2>! tmp.txt
❯ grep -o SELECT tmp.txt | wc -l
```

### Number of `SELECT` statements

Before the change: 66
**After the change: 58**

The reduction of 8 queries is due to calling `trial.suggest_float` 8 times.

### CODE REVIEW

**Comment by c-bata** [comment]
Let me change the label from `code-fix` to `enhancement` since this PR changes the behavior of Optuna without breaking changes.

**Comment by nabenabe0928** [comment]
@y0z I will check this PR after @kAIto47802 approves the PR! 

Does this work or is it something very urgent?
@c-bata

**Comment by c-bata** [comment]
@nabenabe0928 It's not urgent, so please take your time.

**Review by y0z — APPROVED** [review]
LGTM

**Comment by c-bata** [comment]
@porink0424 Could you resolve merge conflicts?

**Comment by porink0424** [comment]
@kAIto47802 Thank you for the quick review.

@nabenabe0928, the conflicts have been resolved, could you review this when you have a moment?

**Review by nabenabe0928 — APPROVED** [review]
LGTM!

**Pull request merged**
