### PR TITLE
Remove unused `type:ignore`s

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Pass `Checks(Integration)`.
## Description of the changes
Remove unused `type:ignore`s. 
See https://github.com/optuna/optuna/actions/runs/5469744986/jobs/9959032168 for more details.

### CODE REVIEW

**Comment by Alnusjaponica** [comment]
See https://github.com/Alnusjaponica/optuna/pull/18 to see if this really works.

**Review by not522 — APPROVED** [review]
LGTM! I'll merge it after the CI passes.

**Comment by Alnusjaponica** [comment]
Thanks. I'll close https://github.com/Alnusjaponica/optuna/pull/18.

**Comment by Alnusjaponica** [comment]
@not522 Seems like `documentation` does not start for some reason. Could you re-run the tests or merge without the CI?

**Pull request merged**
