### PR TITLE
Remove `n_jobs` for `study.optimize` in `examples/`

### PR DESCRIPTION
**Pull request by jeromepatel**
## Motivation

Refer Issue #2581 
## Description of the changes

Set the `n_jobs=1` in `examples/rl/sb3_simple.py` as it has been deprecated in v2.7.0.

### CODE REVIEW

**Comment by nzw0301** [comment]
Thank you for your pull request! How about removing `N_JOBS` and use the default value in `optimize`?

**Comment by jeromepatel** [comment]
@nzw0301 Thank you for your suggestion. As the default value is 1 in `optimize`, I agree with the decision of removing them.

**Review by nzw0301 — APPROVED** [review]
Great!

**Comment by HideakiImamura** [comment]
@toshihikoyanase Could you review this PR?

**Review by toshihikoyanase — APPROVED** [review]
Thank you for your PR. LGTM!

**Pull request merged**
