### PR TITLE
Remove unused `type: ignore`

### PR DESCRIPTION
**Pull request by himkt**
Fix the CI failure in master branch.

## Description of the changes
- eb6df49 Remove `type: ignore`

I tested the CI on my mirrored repository:

- before (same as HEAD): https://github.com/himkt/optuna-warn-unused-ignores/commit/a079506e9a47fc9ec980be2a06a3ac5169bb4a86
- after: https://github.com/himkt/optuna-warn-unused-ignores/commit/dde32036d9909cead57233fdd9c9e408f1fdb6e3

### CODE REVIEW

**Comment by himkt** [comment]
Tests of scipy failed. It might be related to scipy's upgrade.

**Comment by himkt** [comment]
#3834 or the proper fix will be resolve the failure.

**Review by nzw0301 — APPROVED** [review]
Nice.

**Comment by nzw0301** [comment]
I think this change looks trivial, so let me merge this PR with one approval.

**Pull request merged**
