### PR TITLE
fixing docstrings -- WandB Multirun Integration

### PR DESCRIPTION
**Pull request by captain-pool**
There were slight discrepancies with the docstrings I added in the previous PR: #3403 . This PR fixes those, and adds another example usage.

@xadrianzetx @nzw0301

### CODE REVIEW

**Comment by nzw0301** [comment]
Thanks! Unfortunately, https://github.com/optuna/optuna/pull/3477 tries to fix a common part that will be changed by this PR, so this might cause conflict.

**Comment by nzw0301** [comment]
@captain-pool  If you do not mind, I will incorporate your suggestion to #3477 and close this PR. What do you think?

**Comment by captain-pool** [comment]
For sure. Please feel free. :)

**Comment by nzw0301** [comment]
I really appreciate your understanding. Thanks!

**Pull request closed without merging**
