### PR TITLE
Test samplers are reproducible

### PR DESCRIPTION
**Pull request by not522**
## Motivation
Merge #3756 first.
I added tests to check that the built-in samplers are reproducible.

## Description of the changes
- Add tests to check samplers are reproducible.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@not522 The #3791 has been merged. Could you make this PR ready for review?

**Comment by HideakiImamura** [comment]
@contramundum53 Could you review this PR?

**Review by contramundum53 — APPROVED** [review]
LGTM!

**Review by HideakiImamura — APPROVED** [review]
LGTM!

**Pull request merged**
