### PR TITLE
Modify class paths and remove unused deprecated class related to `JournalStorage`

### PR DESCRIPTION
**Pull request by eukaryo**
## Description of the changes

- replaced wrong path: `optuna.storages.JournalFileSymlinkLock`-> `optuna.storages.journal.JournalFileSymlinkLock`
- replaced wrong path: `optuna.storages.JournalFileOpenLock`-> `optuna.storages.journal.JournalFileOpenLock`
- replaced wrong path: `optuna.storages.JournalFileBackend`-> `optuna.storages.journal.JournalFileBackend`
- replaced wrong path: `optuna.storages.BaseJournalBackend`-> `optuna.storages.journal.BaseJournalBackend`
- removed unused deprecated class: `BaseJournalLogSnapshot`
- renamed file path in docs: `journal_file_storage_jsonl.log` -> `optuna_journal_storage.log`

### CODE REVIEW

**Comment by not522** [comment]
Could you split this PR into three separate PRs: fixing the paths, removing unused class ,and renaming the log file?

**Comment by eukaryo** [comment]
Sorry, I see.

**Comment by nabenabe0928** [comment]
This PR is separately addressed in the following PRs:
- https://github.com/optuna/optuna/pull/5560
- https://github.com/optuna/optuna/pull/5561
- https://github.com/optuna/optuna/pull/5562

**Comment by nabenabe0928** [comment]
As this PR is addressed by the aforementioned three PRs, I will close this PR.

**Pull request closed without merging**
