### PR TITLE
Add config dict interface

### PR DESCRIPTION
**Pull request by Minyus**
Current version of Optuna has the following obstacles to use.

1. [Multiple imports] Sampler and Prurner classes need to be imported in addition to `create_study` function.
2. [Chaos of  `trial.suggest_...` ] To switch enabling and disabling Optuna, all the `trial.suggest_...` codes need to be commented out or put in `if` statements. If the code is long, `trial.suggest_...` codes can be scattered and difficult to manage.

To overcome these obstacles, I developed config dict interface.
Config dict interface parses a configuration dictionary, which can be stored as a YAML file, to set up Optuna.

Here are 2 ways to use.

1. `create_study_from_dict` 

An alternative of `create_study`

```python
from optuna import create_study_from_dict
import yaml

yaml_string = '''
direction: minimize
sampler:
  type: TPESampler
  seed: 123
pruner:
  type: MedianPruner
'''

params_dict = yaml.safe_load(yaml_string)

study = create_study_from_dict(params_dict)

def objective(trial):
    x = trial.suggest_uniform('x', -10, 10)
    return (x - 2) ** 2

study.optimize(objective, n_trials=5)

print('Best parameters:', study.best_params)
print('Best value:', study.best_value)
```

2. `study_optimize` decorator

This new interface is somewhat close to [Hyperopt](https://hyperopt.github.io/hyperopt/) and [Scikit-Optimize](https://hyperopt.github.io/hyperopt/), but much more modular and centralized than those.

```python
from optuna import optuna_decorator
import yaml

yaml_string = '''
study_foo:
  optuna_create_study:
    direction: minimize
    sampler:
      type: TPESampler
      seed: 123
    pruner:
      type: MedianPruner
  optuna_study_optimize:
    n_trials: 5
x:
  optuna_suggest: uniform
  low: -10
  high: 10
'''

params_dict = yaml.safe_load(yaml_string)

@study_optimize()
def objective(args):
    # Optionally, pruning can be set up using args['optuna_trial']
    return (args['x'] - 2) ** 2

study = objective(params_dict)

print('Best parameters:', study.best_params)
print('Best value:', study.best_value)
```

Please see the docstring in `facade.py` for details and `test_facade.py` for more use cases.

### CODE REVIEW

**Comment by sile** [comment]
Thank you for your PR.

Your proposed interface seems interesting.
However, I think this is not a small change, so I would like to consider it deeply within Optuna dev team.
Unfortunately, several core developers of Optuna are on a business trip this week, so please give us some time for reviewing this PR.

BTW, I think that the second obstacle (i.e., `Chaos of trial.suggest_...`) may be mitigated by using [`FixedTrial`](https://optuna.readthedocs.io/en/stable/reference/trial.html#optuna.trial.FixedTrial)(see also: [How can I test my objective functions?](https://optuna.readthedocs.io/en/stable/faq.html#how-can-i-test-my-objective-functions)).
What do you think?

**Comment by Minyus** [comment]
Noted about the review schedule. 
Have a nice Obon vacation as well (if some of your team have).

Yes, `FixedTrial` can mitigate the trouble, but it is still dependency on Optuna. 
There are some users who want to remove Optuna-related codes after finishing tuning.

The new interface makes it easy to add and remove Optuna-related codes; the objective function needs no modification depending on whether Optuna is used or not (especially if pruning is not needed).

In a word, the new interface provides *modularity* for Optuna.

It is just a wrapper and does not change any existing codes. 
It will be useful for some users while being harmless for the other users.

**Comment by sile** [comment]
Thank you for your explanation.
I understand the motivation of this PR well.

**Comment by sile** [comment]
Hi @Minyus,

Sorry for the too late reply.

We think that the idea behind this PR is really nice and we are inspired a lot by it, but we decided that we don't merge this PR.
We would like to tackle the issues (i.e., `multiple imports` and `chaos of trial.suggest_...`) that motivated this PR in the future as described in the following sections.

## About `[Multiple imports]`

Although `create_study_from_dict` function seems useful for some users, we think that there is a room of discussion about the API or dict format design. For instance, Optuna allows [user-defined samplers] and pruners, so some advanced users might want to specify their own samplers/pruners in the dict interface. To support user-defined samplers/pruners, we need to extend the current dict interface to support specifying arbitrary classes.

[user-defined samplers]: https://optuna.readthedocs.io/en/stable/tutorial/sampler.html

Besides, we have a plan to implement optuna-shell interface that allows users to optimize normal (including non-Python) command-line programs directly from the terminal (c.f. #368).
This feature is likely to require to configure samplers/pruners via YAML or JSON file
(it would be similar to the dict interface). To avoid providing similar but slightly different functionalities within a package, we would like to consider the dict interface together when we implement the shell interface.

## About `[Chaos of trial.suggest_... ]`

We have received similar issues/requests from other users, so we would like to address this issue fundamentally.

Although the API design is still under consideration, we plan to add `search_space` argument to `Study.optimize` method. The argument takes a search space defined in a dict format, and the hyperparameters in the search space can be accessed in objective function via `Trial` object (see blew).

```python
# This code is based on https://github.com/pfnet/optuna/blob/master/examples/sklearn_simple.py.

predefined_search_space = {
    'classifier': {'CategoricalDistribution': {'choices': ['SVC', 'RandomForest']}},
    'svc_c': {'LogUniformDistribution': {'low': 1e-10, 'high': 1e10}},
}


def objective(trial):
    iris = sklearn.datasets.load_iris()
    x, y = iris.data, iris.target

    # The values of the hyperparameters defined in `search_space` can
    # be retrieved via `obj[key]` notation.
    classifier_name = trial['classifier']
    if classifier_name == 'SVC':
        svc_c = trial['svc_c']  # Ditto.
        classifier_obj = sklearn.svm.SVC(C=svc_c, gamma='auto')
    else:
        # Because `trial` is a normal `Trial` object, other Trial APIs can also be used.
        rf_max_depth = trial.suggest_int('rf_max_depth', 2, 32)
        classifier_obj = sklearn.ensemble.RandomForestClassifier(
            max_depth=rf_max_depth, n_estimators=10)

    score = sklearn.model_selection.cross_val_score(classifier_obj, x, y, n_jobs=-1, cv=3)
    accuracy = score.mean()
    return accuracy


study = optuna.create_study()
study.optimize(objective, search_space=predefined_search_space)
```

Thanks to the above API design, it can be integrated with the existing API style and handle conditional search spaces naturally.

---

Anyway, thank you very much for your proposal.

**Pull request closed without merging**
