### PR TITLE
Remove `enable_cache` option from `RDBStorage`.

### PR DESCRIPTION
**Pull request by sile**
Because there are no practical merits to disable storage cache, this PR removes the `enable_cache` option and makes the cache always enabled.

### CODE REVIEW

**Comment by hvy** [comment]
By the way, do we still need the slow tests (`INCLUDE_SLOW_TESTS`) after this change? 🤔

**Comment by sile** [comment]
> we still need the slow tests (INCLUDE_SLOW_TESTS) after this change?

Yes. For instance, the environment variable will be still used at [test_study.py#L33](https://github.com/optuna/optuna/pull/706/files#diff-48005dfcd962e57ca1be2ec86e03144eR33) after merging this PR.

**Comment by hvy** [comment]
Ah sorry, my question was rather if that test (these parameterizations https://github.com/optuna/optuna/pull/706/files#diff-48005dfcd962e57ca1be2ec86e03144eR34-R35) is still necessary.

**Comment by sile** [comment]
@hvy I see, thanks. I'm not 100% confident but I think the slow test might be removed. Let's discuss this topic in another issue or PR.

**Pull request merged**
