### PR TITLE
Mitigate string-length limitation of `RDBStorage`

### PR DESCRIPTION
**Pull request by toshihikoyanase**
## Motivation
This PR relates to #1860.

SQLAlchemy has multiple types for string data. Currently, [`sqlalchemy.types.String`](https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.String) is used for variable-length strings such as `Trial.system_attr` and `Trial.user_attr`. It has strict length limitation, i.e., 2048 characters.
On the other hand, [`sqlalchemy.types.Text`](https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.Text) may be suitable for such variable-length strings. It is corresponding to `TEXT` type of each database system, which is designed for large text objects.

Although `TEXT` is not a standard type of SQL, many database systems implement it.

| Database | Corresponding type | Length limitation|
| --- | --- | --- |
|SQLite| [TEXT](https://github.com/sqlalchemy/sqlalchemy/blob/2ce1f1d9a8011a4673428850f01b04196e070957/lib/sqlalchemy/dialects/sqlite/base.py#L2166-L2167) | [SQLITE_MAX_LENGTH](https://www.sqlite.org/limits.html#max_length) |
|PostgreSQL| [text](https://github.com/sqlalchemy/sqlalchemy/blob/2ce1f1d9a8011a4673428850f01b04196e070957/lib/sqlalchemy/dialects/postgresql/base.py#L2042) | [unlimited](https://www.postgresqltutorial.com/postgresql-char-varchar-text/)|
|MySQL| [text](https://github.com/sqlalchemy/sqlalchemy/blob/2ce1f1d9a8011a4673428850f01b04196e070957/lib/sqlalchemy/dialects/mysql/base.py#L1375) | [2^16 + 2](https://dev.mysql.com/doc/refman/8.0/en/blob.html) bytes |
|SQL Server| [text](https://github.com/sqlalchemy/sqlalchemy/blob/2ce1f1d9a8011a4673428850f01b04196e070957/lib/sqlalchemy/dialects/mssql/base.py#L1344) | [2^31-1](https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver15) bytes |
|Oracle| [CLOB](https://github.com/sqlalchemy/sqlalchemy/blob/2ce1f1d9a8011a4673428850f01b04196e070957/lib/sqlalchemy/dialects/oracle/cx_oracle.py#L559-L561) | [128TB depending on database block size](https://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm)|

## Description of the changes

This PR replace `String` type with `Text` type.

### TODO

- [x] schema migration script for MySQL

### Example script

```python
import sys
import optuna


def objective(trial):
    trial.set_user_attr("a", "a" * 10000)
    trial.set_system_attr("b", "b" * 10000)
    trial.suggest_categorical("x", [i for i in range(10000)])
    return 1

study = optuna.create_study(storage=sys.argv[1])
study.set_user_attr("c", "c" * 10000)
study.set_system_attr("d", "d" * 10000)
study.optimize(objective, n_trials=1)
```

```console
$ MYSQL_HOST=localhost
$ docker run --name mysql -e MYSQL_ROOT_PASSWORD=test -p 3306:3306 -p 33060:33060 -d mysql:8
$ docker run --network host -it --rm mysql:8  mysql -h ${MYSQL_HOST} -uroot -ptest -e "create database test_optuna;"
$ python long-string.py mysql+pymysql://root:test@${MYSQL_HOST}:3306/test_optuna
```

**Output**

`master`

```console
$ python long-string.py mysql+pymysql://root:test@${MYSQL_HOST}:3306/test_optuna
sqlalchemy.exc.DataError: (pymysql.err.DataError) (1406, "Data too long for column 'value_json' at row 1")
[SQL: INSERT INTO study_user_attributes (study_id, `key`, value_json) VALUES (%(study_id)s, %(key)s, %(value_json)s)]
[parameters: {'study_id': 1, 'key': 'c', 'value_json': '"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc ... (9704 characters truncated) ... cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"'}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
```

This PR
```console
$ python long-string.py mysql+pymysql://root:test@${MYSQL_HOST}:3306/test_optuna
[I 2021-02-26 14:48:12,410] A new study created in RDB with name: no-name-18194847-bf32-4258-b6f3-65919c2fefaa
[I 2021-02-26 14:48:12,563] Trial 0 finished with value: 1.0 and parameters: {'x': 8993}. Best is trial 0 with value: 1.0.
```

### CODE REVIEW

**Comment by keisuke-umezawa** [comment]
@hvy 
Could you also review it?

**Comment by hvy** [comment]
Thanks a lot for this simple fix. I haven't went over in detail yet but some quick questions,

- Does this require a DB migration (`ALTER TABLE`)? If so, we might want to provide a migration script.
- Does this have any performance impacts that we should be aware of?
- Should we document/add unit tests? (this could be a separate issue since that'd widen the scope)

**Comment by toshihikoyanase** [comment]
I checked the changes in the tables using  SQLite, MySQL and PostgreSQL.
We need to add a migration script for these changes. But, the migration code is not generated by Alembic, so I'll add it manually.

SQLite3

<details>
<summary>diff of SQLite</summary>

```diff
32c32
<       value_json VARCHAR(2048), 
---
>       value_json TEXT, 
42c42
<       value_json VARCHAR(2048), 
---
>       value_json TEXT, 
64c64
<       value_json VARCHAR(2048), 
---
>       value_json TEXT, 
74c74
<       value_json VARCHAR(2048), 
---
>       value_json TEXT, 
85c85
<       distribution_json VARCHAR(2048), 
---
>       distribution_json TEXT, 
```

</details>

MySQL

<details>
<summary>Diff of MySQL tables</summary>

```diff
105c105
<   `value_json` varchar(2048) DEFAULT NULL,
---
>   `value_json` text,
133c133
<   `value_json` varchar(2048) DEFAULT NULL,
---
>   `value_json` text,
215c215
<   `distribution_json` varchar(2048) DEFAULT NULL,
---
>   `distribution_json` text,
243c243
<   `value_json` varchar(2048) DEFAULT NULL,
---
>   `value_json` text,
271c271
<   `value_json` varchar(2048) DEFAULT NULL,
---
>   `value_json` text,
```

</details>

PostgreSQL

<details>
<summary>Diff of PostgreSQL tables</summary>

```diff
140c140
<     value_json character varying(2048)
---
>     value_json text
176c176
<     value_json character varying(2048)
---
>     value_json text
284c284
<     distribution_json character varying(2048)
---
>     distribution_json text
320c320
<     value_json character varying(2048)
---
>     value_json text
356c356
<     value_json character varying(2048)
---
>     value_json text
```
</details>

**Comment by c-bata** [comment]
How about using `JSON` column instead of `TEXT`?
https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.JSON

**Comment by toshihikoyanase** [comment]
> How about using `JSON` column instead of `TEXT`?

Thank you for the offline-discussion. In summary, we'll use `TEXT` mainly for the users who use old versions of DB servers. For example, HPC users and private cloud users may have no choice to upgrade the DB servers.

**Review by c-bata — COMMENTED** [review]
The changes basically LGTM. Can we remove here?
https://github.com/optuna/optuna/blob/ce81e201871ffa954e90472ca747bb1f2bac10c9/optuna/storages/_rdb/models.py#L31

**Comment by toshihikoyanase** [comment]
> Does this have any performance impacts that we should be aware of?

I executed a simple benchmark using SQLite3, MySQL 8.0 and PostgreSQL 12. I ran the following script ten times and averaged the wall-clock time. We can see the performance degradation in SQLite3. It took 30% more time. On the other hand, the execution times of MySQL and PostgreSQL are comparable.

I think we expect SQLite3 is for casual experiments, and DB servers like MySQL and PostgreSQL are for large-scale experiments. So, the performance degradation of SQLite3 can be acceptable, but I'm not fully sure. What do you think?

<details>
<summary>benchmark-2395.py</summary>


```python
import sys
import optuna


def objective(trial):
    trial.set_user_attr("a", "a" * 2000)
    trial.set_system_attr("b", "b" * 2000)
    trial.suggest_categorical("x", [f"categorical_variable_{i:02}" for i in range(60)])
    return 1

optuna.logging.set_verbosity(optuna.logging.ERROR)
study = optuna.create_study(storage=sys.argv[1])
study.set_user_attr("c", "c" * 2000)
study.set_system_attr("d", "d" * 2000)
study.optimize(objective, n_trials=200)
```
</details>

|DBMS|[master](https://github.com/optuna/optuna/commit/30f58b5ccc7200f1622e7017f59b47b48af534d5) | This PR | This PR / master |
| --- | --- | --- |  --- |
|SQLite3|5.894 | 7.827|1.327|
|MySQL|7.552 | 7.531|0.997|
|PostgreSQL|4.5235 | 4.6395|1.025|

**Comment by toshihikoyanase** [comment]
I took profiles with cProfile.

## `Study.set_system_attr` and `Study.set_user_atter`

I measured the execution time of `study.set_user_attr` and `study.set_system_attr`.

<details>
<summary> proflie `Study.system_attr` and `Study.user_attr` </summary>

```python
import sys
import optuna


def main():
    for i in range(100):
        study.set_user_attr(f"{i:03}", "c" * 2000)
        study.set_system_attr(f"{i:03}", "d" * 2000)

import cProfile as profile
optuna.logging.set_verbosity(optuna.logging.ERROR)
study = optuna.create_study(storage=sys.argv[1])

profile.run('main()', sys.argv[2])
```
</details>

The following graphs are visualization results. The difference of total execution time is 0.912s and 1.03s. The feature took 12% slower than the master branch. The major part of the increase came from `session.commit()` time (0.655s to 0.726s, difference is about 0.07s). 

The master branch
image

This branch
image

## `Study.suggest_categorical`

I also took profile of `trial.suggest_categorical` with 60 items in `choices`.

<details>
<summary> profile of `Study.optimize` </summary>

```python
import sys
import optuna


def objective(trial):
    trial.suggest_categorical("x", [f"categorical_variable_{i:02}" for i in range(60)])
    return 1

optuna.logging.set_verbosity(optuna.logging.ERROR)
study = optuna.create_study(storage=sys.argv[1])

def main():
    study.optimize(objective, n_trials=100)

import cProfile as profile

profile.run('main()', sys.argv[2])
```
</details>

Large portions of the execution time are occupied by `suggest_categorical`, `create_new_trial`, and `set_trial_state`. These methods include `session.commit`, and `session.commit()`  of this branch was about 30% slower than the main branch (1.21 to 1.55).

The master branch
image

This branch
image


## `Study.suggest_float`

I also tested with the script without `suggest_categorical`, `set_system_attr` or `set_user_attr`. The execution time of this PR is also slower.

<details>
<summary> profiling `Study.optimize` without `suggest_categorical` </summary>
import sys
import optuna


def objective(trial):
    trial.suggest_float("x", 0, 1)
    return 1

optuna.logging.set_verbosity(optuna.logging.ERROR)
study = optuna.create_study(storage=sys.argv[1])

def main():
    study.optimize(objective, n_trials=100)

import cProfile as profile

profile.run('main()', sys.argv[2])
</details>

The master

image


The feature

image

**Comment by toshihikoyanase** [comment]
I executed the same experiment using SQLite, but the execution time was not stable. I doubted the time differences mainly came from the external noise sources such as the other processes writing the same disk and security software.
So, I used another clean machine to rerun the experiment (https://github.com/optuna/optuna/pull/2395#issuecomment-787708685).

The results are shown as follows:

|DBMS|master | This PR | This PR / master |
| --- | --- | --- |  --- |
|SQLite3|15.4975 (0.40) | 15.2633 (0.34)|0.98|
|MySQL|23.6462 (0.81)| 23.4407 (0.22)|0.99|
|PostgreSQL|16.7208 (0.45)| 16.7819 (0.42)|1.00|

Then, we cannot see significant differences. This result is consistent with the SQLite3 implementation because it simply uses the same `TEXT` type internally for both `VARCHAR`and `TEXT` according to the [official document](https://www.sqlite.org/datatype3.html).

**Review by hvy — APPROVED** [review]
Thank you for the benchmarks and the detailed investigation. The numbers look promising and the changes LGTM besides the comment by c-bata san regarding the obsolete `MAX_STRING_LENGTH` constant.

For the record, also verified the upgrade script with SQLite, MySQL and PostgreSQL.

**Comment by toshihikoyanase** [comment]
@c-bata @hvy Thank you for your careful review. I removed the `MAX_STRING_LENGTH` constant in the commit https://github.com/optuna/optuna/pull/2395/commits/6eba4be8ca9dff1ef34784463a8c8248acd7d597. I confirmed that it is not used anymore.

**Review by keisuke-umezawa — APPROVED** [review]
LGTM! Thank you for checking performance and migration scripts!

**Review by c-bata — APPROVED** [review]

**Review by ytsmiling — APPROVED** [review]
Thank you for creating this PR. Let me report that I confirmed that
* the migration script worked without problems in my environment (MySQL, optuna v2.5  -> this branch)
* this PR fixed a problem that have occurred when the `#choices` in `CategoricalDistribution`  is large.

**Comment by hvy** [comment]
Let me merge this PR since it has four approvals. It requires a migration so we should be careful and highlight it in the release note but it will improve the usability for users using the RDB storage.

**Comment by PhilipMay** [comment]
Should #1860 also be closed now?

**Comment by hvy** [comment]
Thanks for the heads up, let me do that.

**Pull request merged**
