### PR TITLE
Remove mxnet

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Progress https://github.com/optuna/optuna/issues/4484 and resolve https://github.com/optuna/optuna/issues/4789. 

## Description of the changes
Move `MXNetPruningCallback`, related test and docs.

### CODE REVIEW

**Comment by c-bata** [comment]
@gen740 @contramundum53 Could you review this PR?

**Review by contramundum53 — COMMENTED** [review]
LGTM.
I'll give an approval after https://github.com/optuna/optuna-integration/pull/31 is merged.

**Review by gen740 — APPROVED** [review]
LGTM!

**Comment by Alnusjaponica** [comment]
@gen740 Thanks for the update.
@contramundum53 Could you merge this PR?

**Comment by Alnusjaponica** [comment]
@contramundum53 Hi, there's no blocker for this PR. Could you merge this?

**Review by contramundum53 — APPROVED** [review]
LGTM!

**Pull request merged**
