### PR TITLE
Handle non-numerical params in `matplotlib.contour_plot`

### PR DESCRIPTION
**Pull request by xadrianzetx**
## Motivation

Previously, an error was raised when matplotlib backed contour plot was created with non-numerical params from `CategoricalDistribution`. This PR introduces a handler for such cases, similar to plotly backend. Discovered while working on #3199, and implements one of the tests cases mentioned there, along with bugfix.

## Description of the changes

* Handle non-numerical params in `matplotlib.contour_plot`
* Write tests

### CODE REVIEW

**Comment by hvy** [comment]
Thanks as always for the PRs, sounds like you're right.
@nzw0301 , @HideakiImamura could you review this PR if you have time?

**Review by nzw0301 — APPROVED** [review]
LGTM! Nice catch!

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by HideakiImamura** [comment]
@xadrianzetx Could you resolve a conflict?

**Comment by xadrianzetx** [comment]
Thanks for pinging me @HideakiImamura, conflicts resolved.

**Pull request merged**
