### PR TITLE
Example xgb cv

### PR DESCRIPTION
**Pull request by sskarkhanis**

### CODE REVIEW

**Review by sskarkhanis — COMMENTED** [review]
I've made the changes and pushed

**Review by toshihikoyanase — APPROVED** [review]
Thank you for your PR. LGTM!

[Note for reviewers]
The XGBoost example with cross-validation was originally discussed in #1202 submitted by the same author. Although we may be able to improve the code style, I think I can submit a follow-up PR for it.

**Review by HideakiImamura — APPROVED** [review]
Thanks for the PR! LGTM!

**Comment by toshihikoyanase** [comment]
@sskarkhanis Thank you for completing the long-running PR since #1202. Let me slightly modify the PR title for the release note.

**Pull request merged**
