### PR TITLE
Copy datasets before objective evaluation.

### PR DESCRIPTION
**Pull request by toshihikoyanase**
## Motivation

As discussed in #1718, LightGBM datasets have parameters and they will be tuned during the model training. I guess the dataset parameters can be the cause of #1500.

## Description of the changes

This PR simply copied the dataset before training the booster models. Currently, I used the shallow copy, and I confirmed that I could enable `feature_pre_filter` when I ran the  `examples/lightgbm_tuner_cv.py`.

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
I made this PR review-ready. Please take a look.

@Y-oHr-N I think this trick was also applied to your original OptGBM and may be related to #1018. Please feel to add comments.

**Comment by Y-oHr-N** [comment]
I have faced a similar problem during the development of OptGBM.
This process is necessary for the tuning to work correctly.

**Comment by toshihikoyanase** [comment]
@Y-oHr-N Thank you for your comment. Please feel free to add comments on implementation if you have any feedback.

**Comment by Y-oHr-N** [comment]
There is no feedback. LGTM.

**Comment by toshihikoyanase** [comment]
Thank you for your review comment!

**Review by HideakiImamura — APPROVED** [review]
@toshihikoyanase Thanks for the PR and @Y-oHr-N Thanks for the review comment!

The change looks good to me. In my understanding, `lgb.train` may change the `train_set` and `valid_sets` in kwargs, but `lgb.cv` does not.

**Comment by toshihikoyanase** [comment]
@HideakiImamura 
Thank you for your review.

> `lgb.train` may change the `train_set` and `valid_sets` in `kwargs`, but `lgb.cv` does not.

In terms of `valid_sets`, `lgb.cv` does not have it as can be seen in [the reference](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.cv.html#lightgbm.cv). On the other hand, the parameter of `train_set` may be changed by `lgb.cv`, and `copy(train_set)` is added right before `lgb.cv`.

**Comment by HideakiImamura** [comment]
Let me merge this PR since I and @Y-oHr-N approved.

**Pull request merged**
