### PR TITLE
Revert "Avoid latest `click==8.1.0` that removed a deprecated feature"

### PR DESCRIPTION
**Pull request by hvy**
https://github.com/optuna/optuna/pull/3428, but from fork.

### CODE REVIEW

**Comment by hvy** [comment]
Not critical but preferably merged before b0.

**Comment by hvy** [comment]
@keisuke-umezawa , @toshihikoyanase could you review this revert?

**Review by himkt — APPROVED** [review]
LGTM. Let me merge with one approval based on the evidence of CI success.

**Review by toshihikoyanase — APPROVED** [review]
LGTM. Thanks. c.f., https://github.com/optuna/optuna/pull/3413#issuecomment-1083540356

**Pull request merged**
