### PR TITLE
Simplify type annotations for `tests/test_distributions.py`

### PR DESCRIPTION
**Pull request by boringbyte**
## Motivation
This PR aims to enhance type annotation handling in Optuna to the module `tests/test_distributions.py` and contributes to solving https://github.com/optuna/optuna/issues/4508.

## Description of the changes
Apply changes to `tests/test_distributions.py` by replacing `Dict` and `Optional` from `typing` module.

### CODE REVIEW

**Comment by y0z** [comment]
Could you please merge the latest master into this branch to resolve the CI errors?

**Comment by boringbyte** [comment]
Merged master into branch

**Review by y0z — APPROVED** [review]
LGTM

**Comment by y0z** [comment]
@porink0424 Could you review this PR?

**Review by nabenabe0928 — APPROVED** [review]
LGTM!

**Pull request merged**
