### PR TITLE
Add type hints to tests/storages_tests/rdb_tests

### PR DESCRIPTION
**Pull request by akihironitta**
## Motivation  
Please refer to the issue #711 .  

## Description of the changes  
I added type hints to `tests/storages_tests/rdb_tests/test_storage.py` and `tests/storages_tests/rdb_tests/test_models.py`.

### CODE REVIEW

**Comment by crcrpar** [comment]
@hvy Don't we have to merge the master or rebase this branch since the integration test failed with the below message?

```
 ==================================== ERRORS ====================================
______ ERROR collecting tests/integration_tests/test_pytorch_lightning.py ______
tests/integration_tests/test_pytorch_lightning.py:17: in <module>
    class Model(pl.LightningModule):
tests/integration_tests/test_pytorch_lightning.py:57: in Model
    ???
E   AttributeError: module 'pytorch_lightning' has no attribute 'data_loader'
```

**Comment by hvy** [comment]
Hm, seems that way for the GitHub Actions. I thought that the PR HEAD was merged with (the latest) `master` on rebuild (it's explicitly done here in [`.circleci/config.yml`](https://github.com/optuna/optuna/blob/master/.circleci/config.yml#L30)). 

@akihironitta, could you do what's suggest by @crcrpar above?

**Comment by akihironitta** [comment]
I've just merged the master! I am not quite sure if I am doing right since I am a very beginning learner in Git/GitHub. I hope it goes well...

**Comment by hvy** [comment]
Thanks for the swift action, seems like you got it right. Let me have your changes merged.

**Pull request merged**
