### PR TITLE
[WIP] Support parallelizing a sequential algorithm TPE

### PR DESCRIPTION
**Pull request by tohmae**
This PR addresses issue #892.

The usage is as follows.

```python
import optuna
from optuna.samplers import CLSampler

def objective(trial):
    x = trial.suggest_uniform("x", -10, 10)
    y = trial.suggest_uniform("y", -5, 5)
    z = trial.suggest_uniform("z", -2, 2)
    return x ** 2 + (y - 2) ** 2 + (z - 3) ** 2

study = optuna.create_study(sampler=CLSampler(param_names=["x","y","z"],strategy="min"))
study.optimize(objective, n_trials=50, n_jobs=5)

### CODE REVIEW

**Comment by HideakiImamura** [comment]
Thanks for the PR. This PR seems to be related to https://github.com/optuna/optuna/pull/1729.

IMO, changing `_optimize.py` is overkill. If we prepare the batch evaluation interface which will be introduced in #1729, we can use `CLSampler` in a simpler way. So, how about waiting for the #1729 to proceed with this PR?

From another point of view, `CLSampler` can be implemented by wrapping "any" sampler as `PartialFixedSampler` does. What do you think?

**Comment by HideakiImamura** [comment]
> From another point of view, CLSampler can be implemented by wrapping "any" sampler as PartialFixedSampler does. What do you think?

More concretely, I mean the following implementation is fine because the constant lier algorithm can be combined with any sampling algorithms.
```python
class CLSampler(BaseSampler):
    def __init__(param_names: List[str], strategy: str, base_sampler: BaseSampler):
        ...
```

**Comment by tohmae** [comment]
Thank you for your prompt response.
As you pointed out, I also think that changing _optimize.py is overkill.
I want to wait for #1729.
CLSampler will be implemented by wrapping any sampler as you reviewd.

**Comment by HideakiImamura** [comment]
Oops. Sorry for the confusion; the constant liar algorithm can be used not only in batch evaluation, as I imagined, but also in distributed optimization, as you implemented. I was mistaken. I think this PR can go ahead without waiting for #1729.

By the way, I don't think you need to modify _optimize.py when using it in distributed optimization. Why did you modify it? Could you elaborate more bit?

**Comment by tohmae** [comment]
Thank you for your comment. I have not used distributed optimization much, so I implemented in batch evaluation. 
I tried to implement the constant liar algorithm in distributed optimization, but
it is hard to implement study.ask and trial._suggest_parallel in multi processes.
Now study.ask seemed to work correctly in multi processes by locking table, 
but trial._suggest_parallel dit not work correctly in multi processes.
If you have some time, it would be great to hear your thoughts.

The usage is as follows.
foo.py
```python
import optuna
from optuna.samplers import TPESampler,CLSampler

def objective(trial):
    x = trial.suggest_uniform("x", -10, 10)
    y = trial.suggest_uniform("y", -5, 5)
    z = trial.suggest_uniform("z", -2, 2)
    return x ** 2 + (y - 2) ** 2 + (z - 3) ** 2

if __name__ == '__main__':
    clsampler=CLSampler(param_names=["x","y","z"],strategy="max",concurrency=5,base_sampler=TPESampler())
    study = optuna.load_study(study_name='distributed-example', storage='mysql://root@localhost/example', sampler=clsampler)
    study.optimize(objective, n_trials=100)
 ```
Process 1:
 ```sh
$ python foo.py
 ```
Process 2:
 ```sh
$ python foo.py
 ```

**Comment by HideakiImamura** [comment]
Your code example looks great to me. I'll dive into your implementation from now.

**Comment by HideakiImamura** [comment]
I have looked through the implementation details. Do we really need to work on `optuna.Study` or `optuna.Trial`? What `CLSampler` wants to do is something like this.
- Sample a predetermined number (`concurrency` or `n_batches`) of samples simultaneously.
- Each time it is requested by a `trial` object, it selects one of the sampled values and passes it on.

I'm wondering if these requirements can be achieved by simply implementing the `CLSampler` as follows. Keep a queue of length `n_batches` in `CLSampler`, and when `sample_independent` or `sample_relative` is called, pop one from the queue and output it. If the queue is empty, sample `n_batches` of samples with the constant liar algorithm.

Then, I don't think you need to modify the following files, which is done in the current implementation. `optuna/samplers/_tpe/sampler.py, optuna/storages/_cached_storage.py, optuna/storages/_rdb/models.py, optuna/storages/_rdb/storage.py , optuna/study.py, optuna/trial/_trial.py`.

**Comment by HideakiImamura** [comment]
This algorithm is very important to Optuna, and it may be quicker to talk about it verbally to work out the implementation details. We can discuss it online if you like.

**Comment by toshihikoyanase** [comment]
Thank you for working on #892.

Just FYI, but let me share my prototypical implementation of the Constant Liar for TPE. It simply replaces the observation values of `RUNNING` trials with a constant value given by users. I guess it simply follows the definition of the constant liar.

https://gist.github.com/toshihikoyanase/d2bbf883f4f4acde1793ccc7effee4b7#file-cltpe_sampler-py-L119-L120
(Please note that I created this about a half year ago, so it may not work with the current version of Optuna.)

Although the change is quite limited compared with this PR, I think my approach can work with  both of the situations you discussed:

1. Batch optimization

I think we can employ my approach for batch optimization. When we suggest four trials in a batch, we can repeat the sampling algorithm four times internally. Then, the constant liar can be used to avoid the values which are suggested in the same batch.

2. Parallel optimization

I think my approach also works in parallel/distributed settings. In each worker, the sampler executes the sampling algorithm independently, and the constant liar will supply the tentative objective values for the trials launched by the other workers.

In the following gist, I casually evaluated my implementation in a parallel setting, so please take a look:

https://gist.github.com/toshihikoyanase/d2bbf883f4f4acde1793ccc7effee4b7#gistcomment-3361888

Without constant liar
image

With constant liar
image

**Comment by tohmae** [comment]
Thank you for your comments.

>I'm wondering if these requirements can be achieved by simply implementing the CLSampler as follows. Keep a queue of length n_batches in CLSampler, and when sample_independent or sample_relative is called, pop one from the queue and output it. If the queue is empty, sample n_batches of samples with the constant liar algorithm.

I am sorry, it is difficult for me.

>This algorithm is very important to Optuna, and it may be quicker to talk about it verbally to work out the implementation details.

Issue #892 was open for a long time, so I created the PR comfortably.
If it is very important to Optuna, I want to return #892 to you.　:bow:

**Comment by jeromepatel** [comment]
@tohmae may I ask you that are you still working on this PR/Draft?

**Comment by tohmae** [comment]
I am sorry for the late reply. I close this draft once.

**Pull request closed without merging**
