### PR TITLE
A Proposal of `LatinHypercubeSampler`

### PR DESCRIPTION
**Pull request by kstoneriv3**
## Motivation

I would like to discuss whether it makes sense to include Latin hypercube sampling in optuna. Latin hypercube sampling is a stratified sampling method that usually performs better than random sampling in HPO.

## Discussion

I would like to hear opinions on the following points.
*  Whether it makes sense to add Latin hypercube sampling in optuna. 
Maybe `QMCSampler` is a good enough alternative. One advantage of LatinHypercube over QMC is that the Latin hypercube is more performant when the number of parameters is large. QMCs are known to degrade their performance when the dimension of the sample space is large. Theoretically, QMC excels in situations where there are several hyperparameters that all influence the objective value, which Latin hypercube is suited for situations where there are a lot of hyperparameters but only a few of them influence the objective value.
* (If we include it, ) whether it should be implement it as a new `qmc_type` of `QMCSampler` or introduce an `LHSampler`.
As Latin hypercube requires that the total sample size is pre-determined, I personally think its interface should be separated from `QMCSampler`. 
* ~~The algorithm requires that the total sample size is pre-determined. However, there is an online algorithm that does not require the information. It needs to be discussed whether we should use an online algorithm that does not require the total sample size to be pre-determined at the construction of sampler. (The algorithm can produce 2^k samples by adaptively doubling the total sample size.)~~ *(Edited)* Some of the advanced Latin hypercube algorithms supported in scipy cannot be samples this way. So I assume this is not a good sampling strategy.

## Benchmark
*(Edited)* The benchmark I took was inappropriate because it was comparing Latin hypercube with median pruner against random sampler without any pruner... . I will add new benchmark results later.

### CODE REVIEW

**Comment by kstoneriv3** [comment]
@HideakiImamura @hvy The current implementation is based on #2423 so I assume you should be able to review it smoothly if we decide to include it to optuna.

**Comment by kstoneriv3** [comment]
An example of Latin hypercube sampling algorithm:
```python
# Sample n samples of Latin hypercube samples in d dimensional unit cube (i.e. [0, 1]^d).
def LatinHypercube(n, d):

    samples = np.zeros([n, d])
    for i in range(d):
        # Enforce a unique point per grid
        perm = np.random.permutation(n)
        noise = np.random.uniform(low=0, high=1, size=n)
        samples[:, i] = perm + noise

    # Scale them to fit [0, 1]^d
    samples = 1. / n * samples
    return samples
```
This way Latin hypercube makes sure that there is always one sample in each grid `[(k-1)/n, k/n]` for any `k = 1, ..., n`.

**Comment by tupui** [comment]
> * Whether it makes sense to add Latin hypercube sampling in optuna.
>   Maybe `QMCSampler` is a good enough alternative. One advantage of LatinHypercube over QMC is that the Latin hypercube is more performant when the number of parameters is large. QMCs are known to degrade their performance when the dimension of the sample space is large.

This is not true. The only case where LHS is **as** performant as QMC (Sobol') is when it's heavily optimised. There are lot of literature on the topic I can provide if necessary (ex. Sergei Kucherenko). From a pure theoretical point of view, Sobol' satisfies more uniformity properties than LHS which only provides a guarantee on 1D sub-projections.

> Theoretically, QMC excels in situations where there are several hyperparameters that all influence the objective value, which Latin hypercube is suited for situations where there are a lot of hyperparameters but only a few of them influence the objective value.

LHS is not a weighted sampling strategy, hence this is not true.

> * ~The algorithm requires that the total sample size is pre-determined. However, there is an online algorithm that does not require the information. It needs to be discussed whether we should use an online algorithm that does not require the total sample size to be pre-determined at the construction of sampler. (The algorithm can produce 2^k samples by adaptively doubling the total sample size.)~ _(Edited)_ Some of the advanced Latin hypercube algorithms supported in scipy cannot be samples this way. So I assume this is not a good sampling strategy.

Indeed, SciPy does not provide any adaptive LHS strategy. But it's definitely something I would like to have if someone can help.

**Comment by kstoneriv3** [comment]
> > * Whether it makes sense to add Latin hypercube sampling in optuna.
> >   Maybe `QMCSampler` is a good enough alternative. One advantage of LatinHypercube over QMC is that the Latin hypercube is more performant when the number of parameters is large. QMCs are known to degrade their performance when the dimension of the sample space is large.
> 
> This is not true. The only case where LHS is **as** performant as QMC (Sobol') is when it's heavily optimised. There are lot of literature on the topic I can provide if necessary (ex. Sergei Kucherenko). From a pure theoretical point of view, Sobol' satisfies more uniformity properties than LHS which only provides a guarantee on 1D sub-projections.
> 
> > Theoretically, QMC excels in situations where there are several hyperparameters that all influence the objective value, which Latin hypercube is suited for situations where there are a lot of hyperparameters but only a few of them influence the objective value.
> 
> LHS is not a weighted sampling strategy, hence this is not true.

I do not get your point here. Consider objective function f(x_1, ..., x_n) = g(x_n). Regardless of n, Latin hypercube with strength 1 has the same convergence rate. On the other hand, for large n, QMC's convergence rate degrades (at least, in practice,) as far as I understand. QMCs need a relatively low effective dimension of the problem (see PCA and Brownian bridge construction of the Brownian motion using QMC) while Latin hypercube does not have such constraints.

> > * ~The algorithm requires that the total sample size is pre-determined. However, there is an online algorithm that does not require the information. It needs to be discussed whether we should use an online algorithm that does not require the total sample size to be pre-determined at the construction of the sampler. (The algorithm can produce 2^k samples by adaptively doubling the total sample size.)~ _(Edited)_ Some of the advanced Latin hypercube algorithms supported in scipy cannot be sampled this way. So I assume this is not a good sampling strategy.
> 
> Indeed, SciPy does not provide any adaptive LHS strategy. But it's definitely something I would like to have if someone can help.

I believe it is possible to sample Latin hypercube with strength 1 in an online manner so that each 2^k sample becomes a Latin hypercube by the doubling method(, which is a well-known algorithm design technique). However, for Latin hypercube with a strength of more than 1, I do not believe such an online sampling is possible.

**Comment by tupui** [comment]
> I do not get your point here. Consider objective function f(x_1, ..., x_n) = g(x_n). Regardless of n, Latin hypercube with strength 1 has the same convergence rate. On the other hand, for large n, QMC's convergence rate degrades (at least, in practice,) as far as I understand. QMCs need a relatively low effective dimension of the problem (see PCA and Brownian bridge construction of the Brownian motion using QMC) while Latin hypercube does not have such constraints.

The convergence rate depends on the effective dimensionality of the function. The convergence rate of LHS is by no mean guaranteed to be better than MC. It's only guaranteed to be at worst the same as MC. QMC has a better convergence rate than LHS even when the number of effective dimensions is high.

Have a look at the following articles

* https://www.researchgate.net/publication/276210905_Exploring_multi-dimensional_spaces_a_Comparison_of_Latin_Hypercube_and_Quasi_Monte_Carlo_Sampling_Techniques
* https://www.broda.co.uk/doc/Aplication_QMC_Finance.pdf
* https://www.researchgate.net/publication/354089921_Construction_and_comparison_of_high-dimensional_Sobol'_sequence_generators (I am a co-author)

> I believe it is possible to sample Latin hypercube with strength 1 in an online manner so that each 2^k sample becomes a Latin hypercube by the doubling method(, which is a well-known algorithm design technique). However, for Latin hypercube with a strength of more than 1, I do not believe such an online sampling is possible.

This should work yes. There is a lot of literature there, we would need to look at the most used/robust algorithm.

**Comment by kstoneriv3** [comment]
> The convergence rate depends on the effective dimensionality of the function. The convergence rate of LHS is by no mean guaranteed to be better than MC. It's only guaranteed to be at worst the same as MC. QMC has a better convergence rate than LHS even when the number of effective dimensions is high.
> 
> Have a look at the following articles
> 
> * https://www.researchgate.net/publication/276210905_Exploring_multi-dimensional_spaces_a_Comparison_of_Latin_Hypercube_and_Quasi_Monte_Carlo_Sampling_Techniques
> * https://www.broda.co.uk/doc/Aplication_QMC_Finance.pdf
> * https://www.researchgate.net/publication/354089921_Construction_and_comparison_of_high-dimensional_Sobol'_sequence_generators (I am a co-author)

OK, but if we assume that QMC almost always has better convergence guarantees, I do not think it makes sense to introduce Latin hypercube to Optuna, as that will just increase the maintenance cost while offering almost no benefits to users. Do you think there is still any advantage of using Latin hypercube compared to Sobol' and Halton sequences?

**Comment by tupui** [comment]
> OK, but if we assume that QMC almost always has better convergence guarantees, I do not think it makes sense to introduce Latin hypercube to Optuna, as that will just increase the maintenance cost while offering almost no benefits to users. Do you think there is still any advantage of using Latin hypercube compared to Sobol' and Halton sequences?

To me, it would mainly be to get the name and possibly new users 😅 So I think it's better to get it in the existing sampler you introduced.

Though, one clear advantage of LHS is when the number of sample is low, one can use the optimised version and get better results than QMC (with the constraints of fixed sample size OC). It can be costly to do but perform better than scrambled versions of QMC (I didn't read yet optimization of QMC, I will look).

**Comment by kstoneriv3** [comment]
> > ... Do you think there is still any advantage of using Latin hypercube compared to Sobol' and Halton sequences?
> 
> To me, it would mainly be to get the name and possibly new users So I think it's better to get it in the existing sampler you introduced.

Well, I do not think the current implementation of `QMCSampler` is not compatible with `scipy.stats.qmc.LatinHypercube` unfortunately, as it samples the points of QMC one by one (not all at once). Thus, the introduction of LatinHypercube should make the code unnecessarily complicated IMO.

> Though, one clear advantage of LHS is when the number of sample is low, one can use the optimised version and get better results than QMC (with the constraints of fixed sample size OC). It can be costly to do but perform better than scrambled versions of QMC (I didn't read yet optimization of QMC, I will look).

Does it mean that as long as we use the unscrambled version of QMC, Latin hypercube is no better than QMC?

**Comment by tupui** [comment]
> Does it mean that as long as we use the unscrambled version of QMC, Latin hypercube is no better than QMC?

Other way around. As long as you use the scrambled version of QMC, it _should_ be better than LHS. _Should_ as in, always problem dependent, but a general rule which work most of the time.

**Pull request closed without merging**
