### PR TITLE
Fix verbosity for `tests/integration_tests/lightgbm_tuner_tests/test_optimize.py`

### PR DESCRIPTION
**Pull request by nyanhi**
## Motivation
To address the issue #3079. 

## Description of the changes
Specified `verbose_eval = False` to suppress the log of intermediate values.
Specified `verbose = -1` for `test_tune_num_leaves_negative_max_depth()` to suppress warning and info like below from LightGBM library:

```
Warning: m...[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000017 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 25
[LightGBM] [Info] Number of data points in the train set: 10, number of used features: 5
[LightGBM] [Info] Start training from score 0.700000
Warning: ] [Warning] No further splits with positive gain, best gain: -inf
Warning: ] [Warning] Stopped training because there are no more leaves that meet the split requirements
```

### CODE REVIEW

**Comment by nzw0301** [comment]
Thank you for your contribution! I'm worried about using `verbose_eval=False` because `verbose_eval` has been deprecated since lightgbm 3.3.0 and Optuna plans to use callback-ish way in its test as described in https://github.com/optuna/optuna/issues/3036 that will be addressed by this ongoing PR, https://github.com/optuna/optuna/pull/3049. So could you use the callback instead of `verbose_eval=False`?

**Comment by nyanhi** [comment]
Thank you for the suggestion, that makes sense! Sorry I just realized the sequence of discussion.
I will try to replace it with the `log_evaluation()` callback.

**Comment by toshihikoyanase** [comment]
@nzw0301 Thank you for your comment. I should have mentioned the deprecation of `verbose_eval`. Could you continue your review, please?

**Comment by nzw0301** [comment]
Sorry, I could not install lightgbm >= 3.3.0 via conda due to https://github.com/microsoft/LightGBM/issues/4736 to locally check the tests. `pip install` never works on my environment (M1 mac), so let me assign myself once :(

**Comment by toshihikoyanase** [comment]
@nzw0301 Thank you for letting me know. I got it.
@himkt Could you review this PR? If you don't have the test environment (due to https://github.com/microsoft/LightGBM/issues/4736), please feel free to unassign yourself.

**Review by himkt — COMMENTED** [review]
Thank you for the patch! I confirmed that a tons of logs observed in https://github.com/optuna/optuna/issues/3079 disappeared.

I have one question: don't we need to add a version constraint for lightgbm (>=3.3.0)?
(`log_evaluation` seems to have been introduced in [v3.3.0](https://github.com/microsoft/LightGBM/releases/tag/v3.3.0), right?)

**Comment by nyanhi** [comment]
Thank you. Per my understanding, #3036 and https://github.com/optuna/optuna/pull/3014#issuecomment-949480109 mentioned that only the latest version of LightGBM is supported in this module for the time being. (Please chime in if my understanding is not correct)

**Comment by himkt** [comment]
Thank you for referring the discussion. I now understand we only support the latest version of LightGBM well. I was wondering we should update our version restriction like in the case of scikit-learn.
https://github.com/optuna/optuna/blob/d30263dc47f30015412dd76b8481d37a04cc70ee/setup.py#L142

However, Optuna doesn't always specify a minimum requirements. 💭  I'm wondering it would be safer to add it because LightGBM 3.2.x is relatively new and users may use it. @toshihikoyanase What do you think about it?

**Comment by toshihikoyanase** [comment]
@nyanhi Thank you for updating the test code. It greatly reduced the log messages.

@himkt I'm sorry for the delayed response.

> I'm wondering it would be safer to add it because LightGBM 3.2.x is relatively new and users may use it.

This PR only changed the test code, and the users who utilize `lightgbm<3.3` can still use the `LightGBMTuner` and `LightGBMTunerCV`. So, I think we may not need to add the version restriction to `setup.py`.

**Review by himkt — APPROVED** [review]
Thank you @toshihikoyanase for clarifying the dependency policy. So, looks good to me!

**Review by toshihikoyanase — APPROVED** [review]
LGTM! This must improve the CI log. Thank you for your contribution.

@himkt Thank you for your kind ping.

**Pull request merged**
