### PR TITLE
Reduce the warning in `tests/storages_tests/test_heartbeat.py`

### PR DESCRIPTION
**Pull request by sousu4**
## Motivation

#3815 partly resolved.
There were several warnings, so I have addressed one of them.

## Description of the changes

Fix UserWarning in tests/storages_tests/test_heartbeat.py

### CODE REVIEW

**Comment by HideakiImamura** [comment]
Let me slightly change the title for the release note.

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by HideakiImamura** [comment]
@nabenabe0928 Could you review this PR?

**Review by nabenabe0928 — APPROVED** [review]
Looks good to me:)

**Pull request merged**
