### PR TITLE
Multi-objective error messages from `Study` to suggest solutions

### PR DESCRIPTION
**Pull request by hvy**
## Motivation

Some error messages for multi-objective optimization could be improved. They could for instance guide callers to alternative solutions. C.f. https://stackoverflow.com/questions/65833998/best-parameters-of-an-optuna-multi-objective-optimization/65837489#65837489. 

## Description of the changes

Improves multi-objective optimization related error messages.

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
@Crissman @keisuke-umezawa Could you review this PR, please?

**Review by Crissman — APPROVED** [review]

**Review by keisuke-umezawa — APPROVED** [review]
LGTM!

**Comment by keisuke-umezawa** [comment]
@hvy tests-rdbstorage are required now, so you need to rebase it against the current master branch.

**Comment by hvy** [comment]
Thanks for the heads up. Rebased.

**Pull request merged**
