### PR TITLE
Backport #4036 and #4044 to pass tests on `release-v3.0.3` branch.

### PR DESCRIPTION
**Pull request by c-bata**
## Motivation

Backport https://github.com/optuna/optuna/pull/4036 and #4044  for Optuna v3.0.3 release.

### CODE REVIEW

**Comment by c-bata** [comment]
Note that we need to merge this PR before #4041 since tests will be failed with Python 3.7.

**Comment by c-bata** [comment]
The documentation build is failed.

```
/home/docs/project/venv/lib/python3.8/site-packages/optuna/visualization/matplotlib/_parallel_coordinate.py:docstring of optuna.visualization.matplotlib._parallel_coordinate.plot_parallel_coordinate:12: WARNING: Exception occurred in plotting optuna-visualization-matplotlib-plot_parallel_coordinate-1
 from /home/docs/project/docs/source/reference/visualization/generated/optuna.visualization.matplotlib.plot_parallel_coordinate.rst:
Traceback (most recent call last):
  File "/home/docs/project/venv/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 515, in _run_code
    exec(code, ns)
  File "<string>", line 13, in <module>
  File "/home/docs/project/venv/lib/python3.8/site-packages/optuna/_experimental.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/home/docs/project/venv/lib/python3.8/site-packages/optuna/visualization/matplotlib/_parallel_coordinate.py", line 80, in plot_parallel_coordinate
    return _get_parallel_coordinate_plot(info)
  File "/home/docs/project/venv/lib/python3.8/site-packages/optuna/visualization/matplotlib/_parallel_coordinate.py", line 125, in _get_parallel_coordinate_plot
    axcb = fig.colorbar(lc, pad=0.1)
  File "/home/docs/project/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 1256, in colorbar
    raise ValueError(
ValueError: Unable to determine Axes to steal space for Colorbar. Either provide the *cax* argument to use as the Axes for the Colorbar, provide the *ax* argument to steal space from it, or add *mappable* to an Axes.
looking for now-outdated files... none found
```

**Comment by c-bata** [comment]
We plan to release v3.0.3 next Tuesday.

**Review by contramundum53 — APPROVED** [review]
LGTM!

**Pull request merged**
