### PR TITLE
Turn off rdb tests on circleci.

### PR DESCRIPTION
**Pull request by keisuke-umezawa**
## Motivation

As we started to check rdb tests by github action https://github.com/optuna/optuna/pull/2200, we do not need to check them by circleci.

### CODE REVIEW

**Review by hvy — APPROVED** [review]
LGTM!

**Comment by hvy** [comment]
Could you just merge the latest master to fix the unrelated CI failure?

**Comment by hvy** [comment]
@crcrpar, could you perhaps review this change?

**Comment by crcrpar** [comment]
I'd like you to update CONTRIBUTING.md as well.

https://github.com/optuna/optuna/pull/2200#issuecomment-760589532

**Comment by keisuke-umezawa** [comment]
@crcrpar I updated the contribution guide. Please review it.

**Review by crcrpar — COMMENTED** [review]
If we don't mention how to verify locally with CirclCI CLI at all, we should remove Continuous Integration section from this guide as the information is not helpful.
Otherwise, we'd better mention that we can verify the documentation build with CircleCI CLI (not verified this works well as I haven't used it for long).

Either is fine.

**Review by hvy — APPROVED** [review]
LGTM!

I'm pretty neutral to the current way CI is mentioned in `CONTRIBUTING.md`. This section could be helpful though for contributors is we elaborate on how the CI is used in more detail so that they know what's expected for a merge.

**Comment by keisuke-umezawa** [comment]
@crcrpar I would like to keep `Continuous Integration` section because it explain our CI environment  contributors. Also, in the future (or now), we can add how to verify tests locally with some tool.

**Comment by keisuke-umezawa** [comment]
As a follow up PR, I want to add local verification method using [act](https://github.com/nektos/act). What do you think of it?

e.g. we can use it for `checks`.
```
$ act -j checks
...
[Checks/checks]   ✅  Success - Install                                                                               
[Checks/checks] ⭐  Run black                                                                                         
| All done! ✨ 🍰 ✨                                                                                                  
| 309 files would be left unchanged.                                                                                  
[Checks/checks]   ✅  Success - black                                                                                 
[Checks/checks] ⭐  Run flake8                                                                                        
[Checks/checks]   ✅  Success - flake8                                                                                
[Checks/checks] ⭐  Run isort                                                                                         
| Skipped 17 files                                                                                                    
[Checks/checks]   ✅  Success - isort                                                                                 
[Checks/checks] ⭐  Run mypy                               
| Success: no issues found in 240 source files                                                                        
[Checks/checks]   ✅  Success - mypy                                                                                  
[Checks/checks] ⭐  Run blackdoc                                                                                      
| All done! ✨ 🍰 ✨                                                                                                  
| 312 files would be left unchanged.                                                                                  
[Checks/checks]   ✅  Success - blackdoc 
```

**Review by crcrpar — APPROVED** [review]
okay, understood. thank you for your explanation.

**Pull request merged**
