### PR TITLE
Expand the type of `callbacks` in optimize to `Iterable`

### PR DESCRIPTION
**Pull request by kz4killua**
## Motivation

This is an update for issue #5509. 

## Description of the changes

The type of `callbacks` in `optimize` has been changed from `list` to `Iterable`. 

All CI checks pass successfully.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@eukaryo @nabenabe0928 Could you review this PR?

**Comment by nabenabe0928** [comment]
This PR relates to the following PR, but as this PR has not seen any response in the last days, I will review this PR:
- https://github.com/optuna/optuna/pull/5516

**Review by nabenabe0928 — APPROVED** [review]
Thank you for the PR, LGTM!
The followup of this PR is to add a unittest using a non-list iterator.

**Comment by kz4killua** [comment]
@nabenabe0928 Sure. I can add a unittest. Would you like me to do that in the same PR? Or separately?

**Comment by nabenabe0928** [comment]
@kz4killua Thank you for the handsup, I prefer another PR for the followup:)

**Comment by nabenabe0928** [comment]
@kz4killua We discussed internally and decided to not add the unittest, sorry for the confusion!
But this PR will be merged without any problems:)

**Comment by kz4killua** [comment]
> @kz4killua We discussed internally and decided to not add the unittest, sorry for the confusion! But this PR will be merged without any problems:)

@nabenabe0928 

Got it! I already made a PR lol. But no worries. Do I just close it?

**Review by eukaryo — APPROVED** [review]
LGTM! I also think it is not necessary to additing unittests for this change.

**Pull request merged**
