### PR TITLE
Added Cached Storage to RDBStorage

### LINKED ISSUE #5035: Bring `_CachedStorage` into `RDBStorage`
### Motivation

`_CachedStorage` is only used from `RDBStorage`. It can be moved into `RDBStorage`.

### Suggestion

Move `_CachedStorage` (https://github.com/optuna/optuna/blob/3fcbf8839c760916cc0cf38fb545f526d5efe85d/optuna/storages/_cached_storage.py#L38) into `RDBStorage`.

### Additional context (optional)

_No response_

### PR DESCRIPTION
**Pull request by jot-s-bindra**
## Motivation

Fix #5035 
## Description of the changes

Moved CachedStorage to RDBStorage 
Removed CachedStorage File
Changed init.py,Storage.py,pytorch_lightning.py,test_cached_storage.py

### CODE REVIEW

**Comment by jot-s-bindra** [comment]
@contramundum53 can you please review this PR?

**Comment by HideakiImamura** [comment]
Sure. By the way, I haven't fully confirmed the changes or the motivation of this PR yet, but it seems that the changes in this PR are considerably larger than expected. Is this the right direction for the changes? @contramundum53

**Comment by jot-s-bindra** [comment]
1. I moved the `_CachedStorage` class inside the `RDBStorage` class within the `storage.py` file in the `_rdb` package.
2. As `_CachedStorage` was dependent on the `studyinfo` class, I also moved the `studyinfo` class into the `storage.py` file.
3. This relocation effectively resulted in the complete transfer of the `_cached_storage.py` file to `storage.py`.
4. I updated other files that had dependencies on the `CachedStorage` class to point to its new location in `_rdb/storage.py`.

**Comment by contramundum53** [comment]
Thanks for your contribution!
Sorry, we are having some discussions about this PR and the issue #5035 among the core develop members right now. The core dev members are concerned that putting `_CachedStorage` class inside `RDBStorage` resulted in a much longer `_rdb.py` file and may have resulted in a worse overall readability, so I think we might need to change the direction.
We are continuing our discussion, and will come back in a while.
Again, thanks for all your effort!

**Pull request closed without merging**
