### PR TITLE
Add the TPE tutorial paper to the doc-string

### PR DESCRIPTION
**Pull request by nabenabe0928**
## Motivation

As [the TPE paper](https://arxiv.org/abs/2304.11127) describes the TPE algorithm in Optuna in detail, I added the paper in the reference for more completeness.

## Description of the changes

I added the paper [`Tree-Structured Parzen Estimator: Understanding Its Algorithm Components and Their Roles for Better Empirical Performance`](https://arxiv.org/abs/2304.11127) to the doc-string.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
Could you resolve the conflicts?

**Comment by HideakiImamura** [comment]
@Alnusjaponica Could you review this PR?

**Review by Alnusjaponica — COMMENTED** [review]
The change itself LGTM. 
BTW, is this paper is under review?

**Review by Alnusjaponica — APPROVED** [review]

**Comment by Alnusjaponica** [comment]
Sorry for the confusion.
Please
- resolve the conflict and
- do not forget to properly update the link when the paper is approved to the journal or conference

**Review by Alnusjaponica — APPROVED** [review]
LGTM. 
@HideakiImamura Could you take another look?

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
