### PR TITLE
Remove tests on TypeError

### PR DESCRIPTION
**Pull request by contramundum53**
## Motivation
According to the new test policy, it should not be tested whether the functions raise `TypeError` on inputs with invalid types. 

## Description of the changes
Remove tests that checks the behavior on invalid input types. I searched for tests checking whether `TypeError` is raised, and removed those that I thought met the criteria.

### CODE REVIEW

**Comment by c-bata** [comment]
@not522 Could you review this PR?

**Review by c-bata — APPROVED** [review]
LGTM!

**Comment by contramundum53** [comment]
I reverted the tests for common objects, i.e., samplers, trials, and study.
PTAL. @not522

**Comment by HideakiImamura** [comment]
@contramundum53 Could you resolve a conflict?

**Review by HideakiImamura — APPROVED** [review]
Thanks, LGTM! I will merge this PR if the conflict is resolved.

**Comment by contramundum53** [comment]
Fixed.

**Pull request merged**
