### PR TITLE
Daily CI of `Checks`

### PR DESCRIPTION
**Pull request by hvy**
## Motivation

`Checks` CI workflow can start to fail due to updates of depending libraries.

## Description of the changes

Runs `Checks` daily.

### CODE REVIEW

**Comment by hvy** [comment]
Should be rebased after https://github.com/optuna/optuna/pull/2767.

**Comment by hvy** [comment]
@Crissman, @keisuke-umezawa could you review this PR? Please let me know if you're busy and I can reassign.

**Comment by Crissman** [comment]
So, would this change PRs, so that they wouldn't run the `checks.yml` workflow? That's an important workflow for me in confiming my PRs are ok. 😅

**Comment by hvy** [comment]
Ah, it will still run in PRs, as in this PR for example. It's meant to _add_ a trigger (so that it becomes similar to e.g. https://github.com/optuna/optuna/blob/master/.github/workflows/tests.yml).

**Review by Crissman — APPROVED** [review]
LGTM. Thanks!

**Review by keisuke-umezawa — APPROVED** [review]

**Pull request merged**
