### PR TITLE
[WIP] Add simple gaussian process based sampler.

### PR DESCRIPTION
**Pull request by VladSkripniuk**
This is my initial attempt on implementing simple Bayesian Optimization based on Gaussian Process for GSoC 2020. I'll sincerely appreciate your feedback.

I ran the following code for comparison with ```optuna.samplers.tpe.TPESampler```.
```
import numpy as np
from matplotlib import pyplot as plt
from scipy.special import sinc
from sklearn.gaussian_process import GaussianProcessRegressor

import optuna
from optuna.samplers.gpbo import GPBO
from optuna.samplers.tpe import TPESampler

def f(x):
    x = x * 10
    x = x - 2
    return sinc(x) + 0.5*sinc(x-3)

X = np.asarray(np.arange(0, 1, 0.001))
y = f(X)

plt.plot(X, y)
plt.ylim(-2,2)
plt.savefig('debug/original.jpg')

def objective(trial):
    x = trial.suggest_uniform('x', 0, 1)

    return f(x)

sampler = GPBO()
study = optuna.create_study(sampler=sampler, direction='minimize')
study.optimize(objective, n_trials=30)

sampler = TPESampler()
study = optuna.create_study(sampler=sampler, direction='minimize')
study.optimize(objective, n_trials=30)
```
```optuna.samplers.gpbo.GPBO``` achieves score ```-0.319180173``` and ```optuna.samplers.tpe.TPESampler``` - ```-0.319178161```.

Objective function looks as follows
image
and here is the progress of GPBO
myimage

### CODE REVIEW

**Comment by Crissman** [comment]
Thanks for the PR! We're looking forward to your application for GSoC.

We're discussing this PR internally and will get back to you soon.

**Comment by g-votte** [comment]
@VladSkripniuk 
Thanks for your sharing the idea! I think this is a good starting point to discuss the new sampler.

If we'll go with this implementation, I think one of action items is to get rid of the dependency to sklearn, since our target is to provide a GP-BO sampler without heavy dependencies. 

Also, we'd need the following discussion:
- how to support non-uniform distributions;
- how to support customizable kernels and acquisition functions.

If you have any idea, we'd very much like to discuss some specific implementation plans.

**Comment by VladSkripniuk** [comment]
@Crissman and @g-votte thank you for getting back to me!

After reading a number of papers, including the ones mentioned on wiki, I think ["Bayesian Optimization for Categorical and Category-Specific Continuous Inputs"](https://arxiv.org/pdf/1911.12473.pdf) is the most interesting for me. Proposed Bandit-BO method shows superior performance on several problems with continuous and categorical variables. Authors deal with categorical variables by training separate GPs for each category. Let me know if this paper is relevant for optuna.

To support non-uniform distributions we can create a function similar to [`optuna.samplers.tpe.TPESampler._sample_numerical`](https://github.com/optuna/optuna/blob/3075a1cf6648b3a8f061f904177734a08bb3a3c3/optuna/samplers/tpe/sampler.py#L226). Integer parameters will be supported by rounding and loguniform distributed parameters will be supported by applying log. Categorical parameters are handled by the method proposed in the paper.

I plan to pass customizable kernels and acquisition functions as an argument in the `__init__` method of the new sampler.

I'm working on the proposal, which I wanted to send to optuna@preferred.jp to get some feedback and discuss schedule of deliverables.

**Comment by g-votte** [comment]
Closing the PR, since our motivation is to provide a sampler without heavy dependencies. 

However, I think this sklearn wrapper is a good example for ppl to implement a user-defined sampler.

Thanks a lot for your proposal!

**Pull request closed without merging**
