### PR TITLE
Implement `plot_param_importances` and `_get_param_importance_plot` with Matplotlib backend.

### PR DESCRIPTION
**Pull request by ytknzw**
This PR proposes to implement a ``matplotlib`` backend for plotting parameter importance based on PR #1756 .

## Motivation
To provide another visualization option for users, who have only ``plotly`` now.
See issue #1539 and PR #1707 for the original motivation.

## Description of the changes
Create  ``optuna.visualization.matplotlib._param_importances.plot_param_importances``, ``optuna.visualization.matplotlib._param_importances._get_param_importance_plot``, ``optuna.visualization.matplotlib._param_importances._get_distribution``, ``optuna.visualization.matplotlib._param_importances._get_color``.

### CODE REVIEW

**Review by crcrpar — COMMENTED** [review]
Sorry for having kept you waiting so long.

Could you improve the position of the legend by using the `loc` argument of `ax.legend`?
image

**Comment by ytknzw** [comment]
Thank you for your review and suggestion!
Added `loc="lower right"` to `ax.legend`.

**Review by himkt — APPROVED** [review]
Thank you for your continuous contribution!
This PR looks good to me.



There is one point I'm wondering if we can improve: changing a way to distinguish distributions of hyperparameters. I think it would be helpful to use colors or shapes that are easy to distinguish for those who have difficulty distinguishing colors. ([https://jfly.uni-koeln.de/color/](https://jfly.uni-koeln.de/color/)).
We may work on this in follow-up PR.

**Comment by himkt** [comment]
@crcrpar I think this PR could be merged. Could you please take a look again?

**Comment by ytknzw** [comment]
@himkt Thank you for your review and suggestion!

> There is one point I'm wondering if we can improve: changing a way to distinguish distributions of hyperparameters. I think it would be helpful to use colors or shapes that are easy to distinguish for those who have difficulty distinguishing colors. (https://jfly.uni-koeln.de/color/).
> We may work on this in follow-up PR.

Yes, I'll work on it including the Plotly backend.

**Review by crcrpar — APPROVED** [review]

**Comment by crcrpar** [comment]
Sorry, requesting a review is my mistake.

**Pull request merged**
