### PR TITLE
add getstate and setstate to redis storage

### PR DESCRIPTION
**Pull request by shu65**
## Motivation

This PR solves the redis storage part of this issue https://github.com/optuna/optuna/issues/4087
This PR should be merged after https://github.com/optuna/optuna/pull/4130

## Description of the changes

This PR adds __setstate__ and __getstate__ to RedisStorage

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@shu65 Is this PR ready for review? If so, could you remove the draft?

**Comment by shu65** [comment]
Yes, this PR ready for review. I removed the draft.

**Review by HideakiImamura — APPROVED** [review]
Looks very good.

**Review by c-bata — APPROVED** [review]
Thank you for the pull request. Looks great to me!

**Pull request merged**
