### PR TITLE
delete fragile heartbeat test

### PR DESCRIPTION
**Pull request by gen740**
## Motivation
On MacOS, `test_record_heartbeat` often failed.
This is because [`Event.wait()`](https://github.com/optuna/optuna/blob/729ccbfc5775b0692a65a1a601fb69fa4b481aa7/optuna/storages/_heartbeat.py#L132) wake-up is sometimes delayed in the ci environment.

It would be enough to check `record_heartbeat` on  [`test_fail_stale_trials`](https://github.com/optuna/optuna/blob/729ccbfc5775b0692a65a1a601fb69fa4b481aa7/tests/storages_tests/test_heartbeat.py#L196)
So, delete fragile `test_record_heartbeat`.

## Description of the changes
- Delete the `test_record_heartbeat`.

### CODE REVIEW

**Comment by cross32768** [comment]
@gen740 Some CIs looks to fail because recently master branch was broken (already fixed). Could you merge master?

**Comment by cross32768** [comment]
@knshnb Could you review this PR?

**Review by c-bata — APPROVED** [review]
LGTM.

**Review by cross32768 — APPROVED** [review]
LGTM!

**Pull request merged**
