### PR TITLE
Add import check to GRPC modules

### PR DESCRIPTION
**Pull request by nabenabe0928**
## Motivation

As the import error in gRPC modules is not really friendly, this PR adds import check.

## Description of the changes

- Add import check to each module

### CODE REVIEW

**Comment by nabenabe0928** [comment]
@not522 @y0z Could you review this PR?

**Review by y0z — APPROVED** [review]
LGTM

**Comment by nabenabe0928** [comment]
@gen740 could you review this PR?

**Review by gen740 — APPROVED** [review]
LGTM!

**Pull request merged**
