### PR TITLE
Fix random number generator of `NSGAIIChildGenerationStrategy`

### PR DESCRIPTION
**Pull request by not522**
## Motivation
The random number generator of `NSGAIIChildGenerationStrategy` is not correctly handled in `reseed_rng`. This PR fixes this bug by making it common with the sampler's RNG.

## Description of the changes
Change the argument of `NSGAIIChildGenerationStrategy` to fix RNG handling.

### CODE REVIEW

**Comment by not522** [comment]
@HideakiImamura @Alnusjaponica Could you review this PR?

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Review by Alnusjaponica — COMMENTED** [review]
The change itself looks good to me.
As we discussed offline, we are going to merge https://github.com/optuna/optuna/pull/5027 first, therefore please resolve conflicts after the update.

**Comment by Alnusjaponica** [comment]
Now that https://github.com/optuna/optuna/pull/5027 has been merged. Could you resolve the conflicts?

**Review by Alnusjaponica — APPROVED** [review]
LGTM

**Pull request merged**
