### PR TITLE
Add tox to dependencies for developers

### PR DESCRIPTION
**Pull request by himkt**
I opened this PR as I just noticed `tox` doesn't appear in `setup.py`.

@c-bata 
What do you think about adding the new package to dependencies for checking?
If you had something intention for not including this change in your PR (#2024), I'd like your opinion.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@c-bata Let me assign you to this PR. I hope you will take a look at it when you have time.

**Comment by crcrpar** [comment]
Personally, adding tox only to checking does not sound good because (a) the current tox.ini also supports tests including integration ones, and (b) we should first clarify a little bit more about how we expect users to utilize tox.ini.

**Comment by c-bata** [comment]
Thank you for mentioning me.

As @crcrpar commented, the initial impression is that we should not add `tox` to checking section. It supports not only checks but also unit tests and integration tests. It seems that there are no appropriate section in extra_requires to add tox.

How about updating CONTRIBUTING.md like the following?

https://github.com/optuna/optuna/issues/2010#issuecomment-728668093

**Comment by himkt** [comment]
@crcrpar @c-bata Thank you for the comments and clarifications!

> the current tox.ini also supports tests including integration ones

It makes sense. Let's make an update to CONTRIBUTING.md. :+1:

**Pull request closed without merging**
