### PR TITLE
Update sklearn.py

### PR DESCRIPTION
**Pull request by Garve**
Added `classifier` keyword to make it scikit-learn 1.0 compatible

### CODE REVIEW

**Review by nzw0301 — APPROVED** [review]
Hi, thank you for sending PR! 

The current CI has been done with scikit-learn < 1.0.0 due to scikti-optimize's incompatibility by https://github.com/optuna/optuna/pull/2953. So this PR does not break backward compatibility.

**Comment by Garve** [comment]
Heya!

Perfect :)

Best
Robert

**Comment by Garve** [comment]
Oops, closed to early

**Comment by hvy** [comment]
@Garve , thanks a lot for the PR, and thanks @nzw0301 for the prompt review! @Crissman could you jump in as a second reviewer? (We in general assign two reviewers to each PR).

**Review by Crissman — APPROVED** [review]
Thanks for the PR! LGTM.

**Pull request merged**
