### PR TITLE
Reorganize a journal storage module structure

### PR DESCRIPTION
**Pull request by c-bata**
## Motivation

Follow-up #5544.

1. `JournalFileBackend` is defined in `storages/journal/_backend.py` and `JournalRedisBackend` is defined in `storages/journal/_redis.py`. This inconsistency needs to be addressed.
2. In https://github.com/optuna/optuna/pull/5546, `JournalFileSymlinkLock` and `JournalFileOpenLock` were remoevd from `optuna.storages.__all__`. This resulted in breaking changes for users who use `from optuna.storages import *`. I have reverted this change and have removed the `test_invalid_journal_related_non_storage_class_import` test method.
3. It's unnecessary to re-define `__init__()` methods (e.g. https://github.com/optuna/optuna/pull/5555/files#diff-12f2f1379b008fc77aaad03fa82bf6e2bfd86f56838851a0ef3c84e9051498c6L71-L72) for deprecated classes.
4. It's also unnecessary to set docstrings in deprecated classes. I have removed them to reduce maintenance costs.
5. `optuna.storages.JournalFileOpenLock` and `optuna.storages.JournalFileSymlinkLock` are defined in `optuna/storages/__init__.py`. I have relocated these two deprecated classes into `storages/journal/_file.py`.
6. The `BaseJournalFileLock` class is currently defined in `storages/journal/_base.py`. I believe it should be defined in `storages/journal/_file.py` as this base class is not used outside of `JournalFileBackend`.

## Description of the changes

This PR addresses the above feedbacks.

### CODE REVIEW

**Review by eukaryo — APPROVED** [review]
LGTM.

**Comment by eukaryo** [comment]
@not522 Could you review this PR?

**Review by not522 — APPROVED** [review]
LGTM!

**Comment by eukaryo** [comment]
I have tested the following two python files with `$ pytest`, and confirmed that no error occured.
```
from typing import Any

import pytest

from optuna.storages import *  # NOQA
from optuna.testing.tempfile_pool import NamedTemporaryFilePool


def test_occur_warning_for_deprecated_class_with_import_asterisk() -> None:
    with pytest.warns(FutureWarning):
        JournalFileSymlinkLock("a")  # NOQA
    with pytest.warns(FutureWarning):
        JournalFileOpenLock("a")  # NOQA
    with NamedTemporaryFilePool() as file:
        with pytest.warns(FutureWarning):
            JournalFileStorage(file.name)  # NOQA
    with pytest.warns(FutureWarning):
        JournalRedisStorage("redis://localhost")  # NOQA

    class _CustomJournalBackendInheritingDeprecatedClass(BaseJournalLogStorage):  # NOQA
        def read_logs(self, log_number_from: int) -> list[dict[str, Any]]:
            return [{"": ""}]

        def append_logs(self, logs: list[dict[str, Any]]) -> None:
            return

    with pytest.warns(FutureWarning):
        _CustomJournalBackendInheritingDeprecatedClass()

```
```
from typing import Any

import pytest

from optuna.storages.journal import *  # NOQA
from optuna.testing.tempfile_pool import NamedTemporaryFilePool


def test_raise_error_for_deprecated_class_with_import_asterisk() -> None:
    with NamedTemporaryFilePool() as file:
        with pytest.raises(NameError):
            JournalFileStorage(file.name)  # type: ignore[name-defined]  # NOQA
    with pytest.raises(NameError):
        JournalRedisStorage("redis://localhost")  # type: ignore[name-defined]  # NOQA
    with pytest.raises(NameError):

        class _NameErrorClass(BaseJournalLogStorage):  # type: ignore[name-defined]  # NOQA
            def read_logs(self, log_number_from: int) -> list[dict[str, Any]]:
                return [{"": ""}]

            def append_logs(self, logs: list[dict[str, Any]]) -> None:
                return
```
I have concluded that the code works as intended.

**Pull request merged**
