### PR TITLE
BUG: Changed interpolation type to make numeric range consistant with plotly

### LINKED ISSUE #2595: The objective range of Matplotlib contour plot has a different numerical range from Plotly backend
## Expected behavior

The range of objective  in `optuna.visualization.matplotlib.plot_contour` should have a similar range to `optuna.visualization.plot_contour`.

## Environment

- Optuna version: 2.7.0
- Python version: 3.8.8
- OS: Mac
- (Optional) Other libraries and their versions:
    - matplotlib: 3.3.4
    - Plotly: 4.11.0

## Error messages, stack traces, or logs
The matplotlib range is from `-60 000` to `360 000` as in the following figure.

download (2)

On the other hand, Plotly's range is from `0` to `9 000`. That is supposed to be true.

newplot (2)

## Steps to reproduce

1. Please run a following example code blocks

## Reproducible examples (optional)

```python
import optuna


def objective(trial):
    x = trial.suggest_uniform('x', -100, 100)
    y = trial.suggest_categorical('y', list(range(-10, 10)))
    z = trial.suggest_uniform('z', -100, 100)
    return x ** 2 + y - z

study = optuna.create_study(sampler=optuna.samplers.TPESampler(seed=7))
study.optimize(objective, n_trials=200)

optuna.visualization.matplotlib.plot_contour(study, params=['y', 'z'])
optuna.visualization.plot_contour(study, params=['y', 'z']) # plotly
```

### PR DESCRIPTION
**Pull request by 01-vyom**
## Motivation

The range of objective in `optuna.visualization.matplotlib.plot_contour` should have a similar range to `optuna.visualization.plot_contour`. 

## Description of the changes

I read the provided [link](https://matplotlib.org/stable/gallery/images_contours_and_fields/irregulardatagrid.html) for interpolation of irregular space data and tried the [CubicInterpolation](https://matplotlib.org/stable/api/tri_api.html#matplotlib.tri.CubicTriInterpolator) code [interpolating z], still got the same results (incorrect numeric range).  The [Linear interpolation](https://matplotlib.org/stable/api/tri_api.html#matplotlib.tri.LinearTriInterpolator) and the option `linear` in the `griddata function` work and corrects the numeric range as well, in the same way, so I went with linear interpolation. 

Before_Cubic_Interpolation:
Before_Cubic

After_Linear_Interpolation:
After_Linear

Plotly Results:
plotly

As for the colour scale, I have addressed that issue in this PR: #2711 

Final Results after colour scale and interpolation correction after merging both the PRs:
Final_Result

closes #2595

### CODE REVIEW

**Review by nzw0301 — APPROVED** [review]
Thank you for giving comprehensive examples. Looks great to me!

**Comment by Crissman** [comment]
@c-bata Can you give your thoughts on this?

**Comment by c-bata** [comment]
@Crissman Could you unassign me? I need to work on the review of optuna-dashboard project for a while.

**Comment by hvy** [comment]
Probably got slipped away, I just unassigned you @c-bata. And thanks for checking.

**Comment by hvy** [comment]
I quickly went through the previous discussions and it basically sounds good to me but @himkt could you double check?

**Review by himkt — APPROVED** [review]
Thank you for tackling the issue. Let me approve.
I confirmed the range of objective values is corrected.
(Although we may still have to sophisticate the interpolation algorithm, it is another point.)

For further development, I think there is room to improve `xrange` and `yrange` of the plot.
The data point near `(y, z) = (-10, -100)` appears in the plotly's output but not in matplotlib's.

matplotlib | plotly
-- | --
 |

**Comment by ytknzw** [comment]
@01-vyom Thank you for improving my implementation! LGTM!

@himkt The point (-10, -100) is at the very left bottom corner of the plot. It would be due to the difference between interpolation algorithms of matplotlib and ploty.

**Pull request merged**
