### PR TITLE
Simplify annotation storages

### PR DESCRIPTION
**Pull request by RektPunk**
## Motivation
Related to https://github.com/optuna/optuna/issues/4508

## Description of the changes
I removed the calls to the typing module except for Any, Type

### CODE REVIEW

**Comment by nabenabe0928** [comment]
@eukaryo
Could you review this PR?

**Review by nabenabe0928 — APPROVED** [review]
Thank you for the PR, LGTM!

NOTE: It would be easier for us to merge a PR if each PR is split in the minimal size.
For example, you could submit 5 different PRs for these changes and then each of them will be merged quicker, which could be beneficial for you as well, I guess.

**Comment by RektPunk** [comment]
Thanks for the note. I'll keep that in mind :)

**Review by eukaryo — APPROVED** [review]
LGTM!

**Pull request merged**
