### PR TITLE
Remove `IntersectionSearchSpace` in `optuna.terminator` module

### PR DESCRIPTION
**Pull request by cross32768**
## Motivation
Current `optuna.terminator` module has their own `IntersectionSearchSpace` and its redundant to the original one in `optuna.search_space` . This PR removes `IntersectionSearchSpace` in `optuna.terminator` and change to use `optuna.search_space.intersection_search_space` instead.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@contramundum53 @gen740 Could you review this PR?

**Review by contramundum53 — APPROVED** [review]
Do we still need the option `ordered_dict` given all `dicts` are ordered since Python 3.7?
Otherwise, LGTM.

**Comment by cross32768** [comment]
> Do we still need the option `ordered_dict` given all `dicts` are ordered since Python 3.7? Otherwise, LGTM.

Yes, we can remove this option as explained in https://github.com/optuna/optuna/issues/4592, but I think it can be done by the follow-up PR.

**Review by gen740 — APPROVED** [review]
LGTM!

**Comment by cross32768** [comment]
@contramundum53 Could you merge this PR? (already has 2 approvals)

**Pull request merged**
