### PR TITLE
Refactor `MLflowCallback`

### PR DESCRIPTION
**Pull request by xadrianzetx**
## Motivation
This PR is a foundation to further improvements of `MLflowCallback`, as discussed in #2788. Various code and docstring quality of life improvements are introduced as per [#2670 TODO list](https://github.com/optuna/optuna/pull/2670#pullrequestreview-682465454). 

## Description of the changes
* `_log_params` now accepts dictionary of trial params, instead of entire `Trial` instance.
* `TrialState` and `StudyDirection` attributes are used when setting `state` and `direction` tags.
* Type hinting for `metric_name` is fixed.
* Various fixes in docstrings are introduced.

### CODE REVIEW

**Comment by xadrianzetx** [comment]
https://github.com/optuna/optuna/blob/fe7887d0453219114300bbde083c3f39e2921d0c/optuna/integration/mlflow.py#L233-L241

Issue mentioned in the comment is still open, so I did not address this one. Alternatively, we could try and find another way to log user attributes, to avoid this problem altogether. Please let me know what you guys think about it.

**Review by himkt — COMMENTED** [review]
Thank you @xadrianzetx! Looks solid.

I found `MLflow` and `MLFlow` both appear in the code.
`MLflow` looks canonical, so could you please replace `MLFlow` with `MLflow`?

**Comment by nzw0301** [comment]
In terms of truncation of a long tag value, we can use this logic in `visualization/_parallel_coordinate.py` for consistency:

https://github.com/optuna/optuna/blob/7ef7bd7f27898133483d238cf627199ce1249439/optuna/visualization/_parallel_coordinate.py#L152

More concretely, 
```python
     if len(value) > mlflow.utils.validation.MAX_TAG_VAL_LENGTH: 
         tags[key] = "{}...".format(value[:mlflow.utils.validation.MAX_TAG_VAL_LENGTH-3])
```

**Review by nzw0301 — APPROVED** [review]
Thanks! LGTM!

**Comment by HideakiImamura** [comment]
@himkt Let me assign you since you have already reviewed this PR.

**Review by himkt — APPROVED** [review]
Sorry for the late, LGTM. Thanks, @xadrianzetx!

**Pull request merged**
