### PR TITLE
Unify the implementation of `_create_frozen_trial()` under `testing` module

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Resolve this todo comment and unify the implementation of the same name function.
https://github.com/optuna/optuna/blob/d430a23d36489e19c0d8306be80486b922da4807/tests/samplers_tests/test_nsgaii.py#L578

## Description of the changes
Implement `testing._create_frozen_trial()`, which behaves exactly the same as `test_cma._create_frozen_trial()` and `test_nsgaii._create_frozen_trial()` except the order of the positional arguments, and use it instead of `_create_frozen_trial()` in each test module.

### CODE REVIEW

**Comment by nabenabe0928** [comment]
Could you review this? @HideakiImamura @contramundum53

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by Alnusjaponica** [comment]
@HideakiImamura Thanks for your review.
@contramundum53 Please take another look.

**Review by contramundum53 — APPROVED** [review]
LGTM!

**Pull request merged**
