### PR TITLE
Add figure title to contour plot

### LINKED ISSUE #1176: Show title in figure for contour plot.
I noticed `optuna.visualization.plot_contour` show a plot without its title.

Screen Shot 2020-04-28 at 10 49 53

I think it's better to show a title to be consistent with other plot features such as `optuna.visualization.plot_optimization_history` and `optuna.visualization.plot_slice`.

We can reproduce this behavior in the [official quickstart](https://colab.research.google.com/github/optuna/optuna/blob/master/examples/quickstart.ipynb)

## Expected behavior

Show title of a figure in the contour plot.

## Environment

- Optuna version: 1.3.0
- Python version: 3.6.9
- OS: Ubuntu 18.04.3 LTS

## Steps to reproduce

Run notebook on [Google Colab](https://colab.research.google.com/github/optuna/optuna/blob/master/examples/quickstart.ipynb).

### PR DESCRIPTION
**Pull request by harupy**
## Motivation

Resolves #1176 

## Description of the changes

- Add a figure title to the contour plot.
- Update `plot_contour.html`.

### CODE REVIEW

**Comment by harupy** [comment]
Screen Shot 2020-04-28 at 21 03 16

https://38688-122299416-gh.circle-artifacts.com/0/docs/build/html/reference/visualization.html#optuna.visualization.plot_contour

**Comment by c-bata** [comment]
Hi, thank you for your pull request! Actually, I once added a similar argument to call `update_layout()` at #704. But it was reverted and made plot functions just return Plotly's figure object for flexibility.

The same discussion seems to be applied to this pull request. What do you think?
cc: @himkt  @toshihikoyanase

**Comment by harupy** [comment]
@c-bata Thanks for the comment! This commit https://github.com/optuna/optuna/pull/704/commits/463a52d0e2662e7177bda52420b64145af6b6b2c?

**Comment by toshihikoyanase** [comment]
@c-bata Thank you for your comment.
This PR uses the `update_layout` function, but I think it applies a layout generated inside the `_get_contour_plot` method, not layouts given by users. So, I think the situation is not the same as https://github.com/optuna/optuna/pull/704. Please let me know if I have misunderstood your comment.

**Comment by c-bata** [comment]
@toshihikoyanase Ah, you are right.

**Pull request merged**
