### PR TITLE
Apply `black==20.8b1`

### PR DESCRIPTION
**Pull request by toshihikoyanase**
## Motivation
[`black`](https://pypi.org/project/black/#history) v20.8b1 has been released today, and it requires the style update of the code in the `master` branch.

## Description of the changes
This PR simply apply `black==20.8b1` to the code. Please let me know if we should use the previous version as a workaround.

### CODE REVIEW

**Review by hvy — COMMENTED** [review]
Thanks for your swift action. This is not a strong opinion but the magic trailing commas were seemingly unintended. So it might be cleaner to remove them instead of telling `black` to break there. What do you think?

**Comment by toshihikoyanase** [comment]
@hvy Thank you for pointing it out. I was not aware of that. I'll remove the trailing commas to minimize the changes.

**Review by HideakiImamura — APPROVED** [review]
Thanks for the quick fix! LGTM!

**Review by hvy — APPROVED** [review]
Nice that it also catches bad indentations. Thanks, LGTM!

**Pull request merged**
