### PR TITLE
Make `ObjectiveFuncType` available externally

### PR DESCRIPTION
**Pull request by nabenabe0928**
## Motivation

As `ObjectiveFuncType` is used in other modules such as `optuna-integration` and `optuna-examples`, and it is useful for typing anyways, I will make it available again externally.

## Description of the changes

`ObjectiveFuncType` was made available only for type checking in
- https://github.com/optuna/optuna/pull/5391
and I will make it available again.

### CODE REVIEW

**Comment by nabenabe0928** [comment]
@eukaryo @not522
Could you review this PR?

**Review by eukaryo — APPROVED** [review]
LGTM as a hotfix. For optuna-examples and integration, it might be better to make the same modifications as in the PR https://github.com/optuna/optuna/pull/5391 later. (Maybe it is appropriate for good-first issues)

**Comment by c-bata** [comment]
@nabenabe0928 This is not a strong opinion, however, I suggest that we consider updating the code in `optuna-integration` as shown below. This is because ObjectiveFuncType is needed only when checking types.

```diff
-from optuna.study.study import ObjectiveFuncType
+from typing import TYPE_CHECKING
+
+if TYPE_CHECKING:
+    from optuna.study.study import ObjectiveFuncType
```

https://github.com/search?q=repo%3Aoptuna%2Foptuna-integration%20ObjectiveFuncType&type=code

**Review by c-bata — APPROVED** [review]
I've understood now that this PR simply reverts the unintended change introduced in #5391, which has not yet been released. LGTM!

**Pull request merged**
