### PR TITLE
Add a version constraint to `fakeredis`

### LINKED ISSUE #5305: Redis after Mar 10 2024 causes an error
### Expected behavior

This PR hotfixed the error.
- https://github.com/optuna/optuna/pull/5304

### Error messages, stack traces, or logs

Please check the log
- https://github.com/optuna/optuna/actions/runs/8225378999/job/22490338938#step:10:6498

### Steps to reproduce

Please check via CI.

### PR DESCRIPTION
**Pull request by c-bata**
## Motivation

Fixes #5305 
Refs #5304

## Description of the changes

Avoid to use `fakeredis==2.21.2`. Perhaps, the problem will be resolved by https://github.com/cunla/fakeredis-py/pull/303.

### CODE REVIEW

**Comment by c-bata** [comment]
@nabenabe0928 Could you review this PR?

**Review by nabenabe0928 — COMMENTED** [review]
Thank you for the PR!
I have a question, but what about making the version constraint `!=` rather than `<`?

As this PR has an overlap with the previous PR, I will close the previous PR.
- https://github.com/optuna/optuna/pull/5304

**Comment by nabenabe0928** [comment]
@y0z Could you review this PR?

**Comment by c-bata** [comment]
> I have a question, but what about making the version constraint != rather than <?

This is just to avoid the CI breaking again with `fakeredis==2.21.3`. There's no guarantee that this issue will be resolved in the next fakeredis release.

**Review by nabenabe0928 — APPROVED** [review]
LGTM!
@y0z As this PR is urgent, I will merge this PR with only one approval!

**Pull request merged**
