### PR TITLE
Move examples to sub directories

### PR DESCRIPTION
**Pull request by toshihikoyanase**
## Motivation
A successive work of #2302 and #2458. Some examples for ML libraries are in the root directory of examples. I'd like to create sub directories for them.

## Description of the changes

- catboost_simple.py --> catboost/catboost_simple.py
- dask_ml_simple.py --> dask_ml/dask_ml_simple.py
- haiku_simple.py --> haiku/haiku_simple.py
- ray-joblib.py --> ray/ray-joblib.py
- skimage_lbp_simple.py --> skimage/skimage_lbp_simple.py
- tensorboard_simple.py --> tensorboard/tensorboard_simple.py

### CODE REVIEW

**Review by HideakiImamura — COMMENTED** [review]
Thanks for the PR. Almost LGTM!

Could you also fix the followings?
- `catalyst_simple.py` in `README.md` (L95)
- `catboost_simple.py` in `README.md` (L96)

**Comment by toshihikoyanase** [comment]
@HideakiImamura Thank you for your careful review. I updated `README.md` in the root dir.

**Review by keisuke-umezawa — APPROVED** [review]
LGTM! Thanks.

**Comment by toshihikoyanase** [comment]
@keisuke-umezawa @HideakiImamura As mentioned in #2654, I'd like to close this PR and create a new repository for the Optuna examples. Thank you for your reviews.

**Pull request closed without merging**
