### PR TITLE
Support Python 3.11

### PR DESCRIPTION
**Pull request by not522**
## Motivation
Support Python 3.11 #3964 
The stable version of Python 3.11 has not yet been released. This PR is for checking if there is any code that needs to be fixed.

## Description of the changes
- Add 3.11 for CI matrix
- Use 3.11 in speed benchmark
- Add 3.11 badge

### CODE REVIEW

**Comment by not522** [comment]
I'm waiting for these issues to be resolved.

- For `fakeredis` https://github.com/scoder/lupa/issues/222
- For `shap` https://github.com/numba/numba/issues/8304

I expect Optuna's CI can pass without the updates, but they will make the change of this PR smaller.

**Comment by not522** [comment]
All the tests are passed! This PR is ready for review now.
I decided not to add 3.11 to the integration tests in this PR.

**Comment by c-bata** [comment]
Let me merge this PR with 1 approval.

**Review by c-bata — COMMENTED** [review]
LGTM!

**Review by c-bata — APPROVED** [review]

**Pull request merged**
