### PR TITLE
Fix Binh and Korn function in MO example

### PR DESCRIPTION
**Pull request by hvy**
## Motivation

See description below.
 
## Description of the changes

Fixes the Bing and Korn function in one of our MO examples. C.f. [Wikipedia]( https://en.wikipedia.org/wiki/Test_functions_for_optimization#Test_functions_for_multi-objective_optimization).

### CODE REVIEW

**Comment by sile** [comment]
Thank you for catching and fixing the bug!
I think that we need to fix [the example code of `optuna.multi_objective.visualization.plot_pareto_front()`](https://github.com/optuna/optuna/blob/master/optuna/multi_objective/visualization/_pareto_front.py#L35) too.

**Review by toshihikoyanase — APPROVED** [review]
Good catch! It is identical to the equation in the original paper by Binh and Korn.

image

**Comment by hvy** [comment]
> Thank you for catching and fixing the bug!
I think that we need to fix the example code of optuna.multi_objective.visualization.plot_pareto_front() too. 

Should be fixed now as well. PTAL.

**Review by sile — APPROVED** [review]
Thanks!
Let me merge this PR once CI passes.

**Pull request merged**
