### PR TITLE
[DO NOT MERGE] Apply black

### PR DESCRIPTION
**Pull request by keisuke-umezawa**

### CODE REVIEW

**Comment by crcrpar** [comment]
Conversion from single quotes to double quotes...

**Comment by keisuke-umezawa** [comment]
c.f. https://github.com/psf/black/issues/118#issuecomment-393298377

**Comment by hvy** [comment]
I personally am all in for single quotes, probably biased from developing Chainer. However, a consistent style with either is better as I see it. The huge discussion on black's repository this was rather painful to read.

**Comment by keisuke-umezawa** [comment]
I will create PRs for applying black to all files with following conditions:

- w/ string format
- w/o string format

**Pull request closed without merging**
