### PR TITLE
Remove XGBoost integration

### PR DESCRIPTION
**Pull request by buruzaemon**
## Motivation

- For addressing the XGBoost module migration portion of #4484 , this removes the XGBoost portion which will be migrated to optuna_integration.

## Description of the changes

- Removed unnecessary files and references to XGBoost.

## REQUEST

- Please merge related PR [Add XGBoost integration #65](https://github.com/optuna/optuna-integration/pull/65) before merging this PR.

### CODE REVIEW

**Comment by nabenabe0928** [comment]
@y0z Could you review this PR?

**Comment by y0z** [comment]
I find that removing `XGBoost` causes the following [documentation generation error](https://github.com/optuna/optuna/actions/runs/7736081659/job/21092834151?pr=5218).
```sh
make: *** [Makefile:20: html] Error 2
generating gallery for tutorial/10_key_features... [ 60%] 003_efficient_optimization_algorithms.py
Error: Process completed with exit code 2.
```

To avoid this error, could you please change to use [LightGBMPruningCallback](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.LightGBMPruningCallback.html#optuna.integration.LightGBMPruningCallback) instead of `XGBoostPruningCallback` in [the tutorial code](
https://github.com/optuna/optuna/blob/master/tutorial/10_key_features/003_efficient_optimization_algorithms.py#L174-L187) ? An example is [here](https://github.com/optuna/optuna-examples/blob/main/lightgbm/lightgbm_integration.py).

**Comment by buruzaemon** [comment]
Thank you @y0z for the review and comment. I will look into fixing this bit with the documentation generation as you pointed out.

**Comment by nabenabe0928** [comment]
@buruzaemon 

Currently, the bottom of `tutorial/10_key_features/003_efficient_optimization_algorithms.py` looks like below:

```python
###################################################################################################
# Integration Modules for Pruning
# -------------------------------
# To implement pruning mechanism in much simpler forms, Optuna provides integration modules for the following libraries.
#
# For the complete list of Optuna's integration modules, see :mod:`~optuna.integration`.
#
# For example, :class:`~optuna.integration.LightGBMPruningCallback` introduces pruning without directly changing the logic of training iteration.
# (See also `example <https://github.com/optuna/optuna-examples/blob/main/lightgbm/lightgbm_integration.py>`_ for the entire script.)
#
# .. code-block:: python
#
#         pruning_callback = optuna.integration.LightGBMPruningCallback(trial, 'validation-error')
#         bst = lgb.train(param, dtrain, num_boost_round, valid_sets=[dvalid], valid_names="validation", callbacks=[pruning_callback])

```

I would like you to change it like:

```python
###################################################################################################
# Integration Modules for Pruning
# -------------------------------
# To implement pruning mechanism in much simpler forms, Optuna provides integration modules for the following libraries.
#
# For the complete list of Optuna's integration modules, see :mod:`~optuna.integration`.
#
# For example, :class:`~optuna.integration.XGBoostPruningCallback` introduces pruning without directly changing the logic of training iteration.
# (See also `example <https://github.com/optuna/optuna-examples/tree/main/xgboost/xgboost_integration.py>`_ for the entire script.)
#
# .. code-block:: python
#
#         pruning_callback = optuna.integration.XGBoostPruningCallback(trial, 'validation-error')
#         bst = xgb.train(param, dtrain, evals=[(dvalid, 'validation')], callbacks=[pruning_callback])


```

**Review by nabenabe0928 — CHANGES_REQUESTED** [review]
Please address this comment.
https://github.com/optuna/optuna/pull/5218#issuecomment-1931407256

**Comment by buruzaemon** [comment]
> Please address this comment. [#5218 (comment)](https://github.com/optuna/optuna/pull/5218#issuecomment-1931407256)

Thank you for providing the desired changes. Edits completed, ptal.

**Review by nabenabe0928 — APPROVED** [review]
Thank you for your work:)
LGTM!

**Review by y0z — APPROVED** [review]
Thank you for your contribution.
LGTM 🎉

**Comment by nabenabe0928** [comment]
@buruzaemon Could you leave a comment on https://github.com/optuna/optuna/pull/5238 so that I can include you as a contributor of this PR?

**Pull request closed without merging**
