### PR TITLE
Add sep-CMA-ES in `parametrize_sampler`

### PR DESCRIPTION
**Pull request by c-bata**
## Motivation

As a Multivariate TPE is tested on `test_samplers`, perhaps sep-CMA-ES and CMA-ES with Margin, which is ongoing work at #4016, should also be tested there.

## Description of the changes

Add sep-CMA-ES sampler in `parametrize_sampler`.

### CODE REVIEW

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by toshihikoyanase** [comment]
@knshnb Could you join the review, please?

**Comment by toshihikoyanase** [comment]
Let me change the label from `enhancement` to `test` since this PR only updates a unit test.

**Comment by c-bata** [comment]
> Let me change the label from `enhancement` to `test` since this PR only updates a unit test.

Thanks :bow:

**Comment by knshnb** [comment]
Good catch! A nit, but how about adding sep-CMA-ES also to `sampler_class_with_seed` and `test_sampler_reseed_rng`?

**Comment by c-bata** [comment]
Sounds good 👍  I've pushed 5fe9ac9. PTAL.

**Review by knshnb — APPROVED** [review]
LGTM.

**Pull request merged**
