### PR TITLE
Fix plotly figure iframe paths

### PR DESCRIPTION
**Pull request by harupy**
## Motivation

The latest doc fails to display the plotly figures:

Screen Shot 2020-10-06 at 20 15 36

https://optuna.readthedocs.io/en/v2.2.0/reference/visualization/generated/optuna.visualization.plot_contour.html

### CODE REVIEW

**Comment by harupy** [comment]
The issue has been fixed:

https://60222-122299416-gh.circle-artifacts.com/0/docs/build/html/reference/visualization/generated/optuna.visualization.plot_contour.html#optuna.visualization.plot_contour

**Comment by harupy** [comment]
Before, the pages for the plotting functions were located under `https://optuna.readthedocs.io/en/v2.x.x/reference/generated`, but https://github.com/optuna/optuna/pull/1847 moved these pages under `https://optuna.readthedocs.io/en/v2.x.x/reference/visualization/generated`.

**Review by hvy — APPROVED** [review]
You're absolutely right, thanks a lot. LGTM!

**Review by HideakiImamura — APPROVED** [review]
Thanks for the good catch! SGTM!

**Pull request merged**
