### PR TITLE
Fix a TPE implementation on DiscreteUniformDistribution

### PR DESCRIPTION
**Pull request by c-bata**
I executed an example which is used at #916.

```python
import optuna
import pprint


def objective(trial):
    x = trial.suggest_discrete_uniform('x', -10, 10, q=2.0)
    y = trial.suggest_discrete_uniform('y', -10, 10, q=2.0)
    return (x-8)**2 + (y+8)**2


if __name__ == '__main__':
    study = optuna.create_study(sampler=optuna.samplers.TPESampler(seed=0))
    study.optimize(objective, n_trials=40)
    pprint.pprint([t.params for t in study.trials])
    print('Best value: {} (params: {})\n'.format(study.best_value, study.best_params))
```

The best trials is `Best value: 0.0 (params: {'x': 8.0, 'y': -8.0})`.

<details>

<summary>execution log</summary>

```console
$ python examples/quadratic_simple.py 
[I 2020-02-12 12:51:39,173] Finished trial#0 resulted in value: 180.0. Current best value is 180.0 with parameters: {'x': 2.0, 'y': 4.0}.
[I 2020-02-12 12:51:39,196] Finished trial#1 resulted in value: 100.0. Current best value is 100.0 with parameters: {'x': 2.0, 'y': 0.0}.
[I 2020-02-12 12:51:39,219] Finished trial#2 resulted in value: 244.0. Current best value is 100.0 with parameters: {'x': 2.0, 'y': 0.0}.
[I 2020-02-12 12:51:39,241] Finished trial#3 resulted in value: 356.0. Current best value is 100.0 with parameters: {'x': 2.0, 'y': 0.0}.
[I 2020-02-12 12:51:39,264] Finished trial#4 resulted in value: 40.0. Current best value is 40.0 with parameters: {'x': 10.0, 'y': -2.0}.
[I 2020-02-12 12:51:39,288] Finished trial#5 resulted in value: 68.0. Current best value is 40.0 with parameters: {'x': 10.0, 'y': -2.0}.
[I 2020-02-12 12:51:39,312] Finished trial#6 resulted in value: 360.0. Current best value is 40.0 with parameters: {'x': 10.0, 'y': -2.0}.
[I 2020-02-12 12:51:39,335] Finished trial#7 resulted in value: 328.0. Current best value is 40.0 with parameters: {'x': 10.0, 'y': -2.0}.
[I 2020-02-12 12:51:39,358] Finished trial#8 resulted in value: 580.0. Current best value is 40.0 with parameters: {'x': 10.0, 'y': -2.0}.
[I 2020-02-12 12:51:39,381] Finished trial#9 resulted in value: 260.0. Current best value is 40.0 with parameters: {'x': 10.0, 'y': -2.0}.
[I 2020-02-12 12:51:39,408] Finished trial#10 resulted in value: 4.0. Current best value is 4.0 with parameters: {'x': 10.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,435] Finished trial#11 resulted in value: 8.0. Current best value is 4.0 with parameters: {'x': 10.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,462] Finished trial#12 resulted in value: 8.0. Current best value is 4.0 with parameters: {'x': 10.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,491] Finished trial#13 resulted in value: 4.0. Current best value is 4.0 with parameters: {'x': 10.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,518] Finished trial#14 resulted in value: 8.0. Current best value is 4.0 with parameters: {'x': 10.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,548] Finished trial#15 resulted in value: 4.0. Current best value is 4.0 with parameters: {'x': 10.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,575] Finished trial#16 resulted in value: 200.0. Current best value is 4.0 with parameters: {'x': 10.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,603] Finished trial#17 resulted in value: 20.0. Current best value is 4.0 with parameters: {'x': 10.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,630] Finished trial#18 resulted in value: 16.0. Current best value is 4.0 with parameters: {'x': 10.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,658] Finished trial#19 resulted in value: 20.0. Current best value is 4.0 with parameters: {'x': 10.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,686] Finished trial#20 resulted in value: 36.0. Current best value is 4.0 with parameters: {'x': 10.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,713] Finished trial#21 resulted in value: 0.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,740] Finished trial#22 resulted in value: 0.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,767] Finished trial#23 resulted in value: 16.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,795] Finished trial#24 resulted in value: 0.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,822] Finished trial#25 resulted in value: 16.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,852] Finished trial#26 resulted in value: 68.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,881] Finished trial#27 resulted in value: 0.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,909] Finished trial#28 resulted in value: 20.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,938] Finished trial#29 resulted in value: 160.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,967] Finished trial#30 resulted in value: 100.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:39,995] Finished trial#31 resulted in value: 0.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:40,024] Finished trial#32 resulted in value: 4.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:40,054] Finished trial#33 resulted in value: 4.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:40,082] Finished trial#34 resulted in value: 36.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:40,111] Finished trial#35 resulted in value: 104.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:40,139] Finished trial#36 resulted in value: 20.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:40,168] Finished trial#37 resulted in value: 148.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:40,196] Finished trial#38 resulted in value: 40.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[I 2020-02-12 12:51:40,224] Finished trial#39 resulted in value: 36.0. Current best value is 0.0 with parameters: {'x': 8.0, 'y': -8.0}.
[{'x': 2.0, 'y': 4.0},
 {'x': 2.0, 'y': 0.0},
 {'x': -2.0, 'y': 4.0},
 {'x': -2.0, 'y': 8.0},
 {'x': 10.0, 'y': -2.0},
 {'x': 6.0, 'y': 0.0},
 {'x': 2.0, 'y': 10.0},
 {'x': -10.0, 'y': -10.0},
 {'x': -10.0, 'y': 8.0},
 {'x': 6.0, 'y': 8.0},
 {'x': 10.0, 'y': -8.0},
 {'x': 10.0, 'y': -10.0},
 {'x': 10.0, 'y': -10.0},
 {'x': 8.0, 'y': -6.0},
 {'x': 6.0, 'y': -6.0},
 {'x': 8.0, 'y': -6.0},
 {'x': -6.0, 'y': -6.0},
 {'x': 6.0, 'y': -4.0},
 {'x': 8.0, 'y': -4.0},
 {'x': 4.0, 'y': -6.0},
 {'x': 8.0, 'y': -2.0},
 {'x': 8.0, 'y': -8.0},
 {'x': 8.0, 'y': -8.0},
 {'x': 4.0, 'y': -8.0},
 {'x': 8.0, 'y': -8.0},
 {'x': 4.0, 'y': -8.0},
 {'x': 0.0, 'y': -10.0},
 {'x': 8.0, 'y': -8.0},
 {'x': 10.0, 'y': -4.0},
 {'x': 4.0, 'y': 4.0},
 {'x': 0.0, 'y': -2.0},
 {'x': 8.0, 'y': -8.0},
 {'x': 6.0, 'y': -8.0},
 {'x': 8.0, 'y': -10.0},
 {'x': 2.0, 'y': -8.0},
 {'x': 10.0, 'y': 2.0},
 {'x': 6.0, 'y': -4.0},
 {'x': -4.0, 'y': -10.0},
 {'x': 2.0, 'y': -6.0},
 {'x': 8.0, 'y': -2.0}]
Best value: 0.0 (params: {'x': 8.0, 'y': -8.0})
```

</details>

### CODE REVIEW

**Comment by c-bata** [comment]
## Performance of UniformDistribution

```go
package main

import (
	"log"
	"math"

	"github.com/c-bata/goptuna"
	"github.com/c-bata/goptuna/tpe"
)

func objective(trial goptuna.Trial) (float64, error) {
	x1, _ := trial.SuggestUniform("x1", -10, 10)
	x2, _ := trial.SuggestUniform("x2", -10, 10)
	return math.Pow(x1-8, 2) + math.Pow(x2+8, 2), nil
}

func main() {
	study, err := goptuna.CreateStudy(
		"goptuna-example",
		goptuna.StudyOptionSampler(tpe.NewSampler()),
	)
	if err != nil {
		log.Fatal("failed to create study:", err)
	}

	if err = study.Optimize(objective, 40); err != nil {
		log.Fatal("failed to optimize:", err)
	}

	v, _ := study.GetBestValue()
	params, _ := study.GetBestParams()
	log.Printf("Best evaluation=%f (x1=%f, x2=%f)",
		v, params["x1"].(float64), params["x2"].(float64))
}
```

```
$ go run _examples/simple_tpe/main.go 
2020/02/13 12:17:42 [INFO] Trial finished: trialID=0 state=Complete evaluation=9.223027
2020/02/13 12:17:42 [INFO] Trial finished: trialID=1 state=Complete evaluation=24.656732
2020/02/13 12:17:42 [INFO] Trial finished: trialID=2 state=Complete evaluation=127.746487
2020/02/13 12:17:42 [INFO] Trial finished: trialID=3 state=Complete evaluation=323.614768
2020/02/13 12:17:42 [INFO] Trial finished: trialID=4 state=Complete evaluation=1.817853
2020/02/13 12:17:42 [INFO] Trial finished: trialID=5 state=Complete evaluation=407.200818
2020/02/13 12:17:42 [INFO] Trial finished: trialID=6 state=Complete evaluation=12.986887
2020/02/13 12:17:42 [INFO] Trial finished: trialID=7 state=Complete evaluation=43.297801
2020/02/13 12:17:42 [INFO] Trial finished: trialID=8 state=Complete evaluation=9.008394
2020/02/13 12:17:42 [INFO] Trial finished: trialID=9 state=Complete evaluation=200.761534
2020/02/13 12:17:42 [INFO] Trial finished: trialID=10 state=Complete evaluation=417.569423
2020/02/13 12:17:42 [INFO] Trial finished: trialID=11 state=Complete evaluation=21.593410
2020/02/13 12:17:42 [INFO] Trial finished: trialID=12 state=Complete evaluation=1.534044
2020/02/13 12:17:42 [INFO] Trial finished: trialID=13 state=Complete evaluation=333.435460
2020/02/13 12:17:42 [INFO] Trial finished: trialID=14 state=Complete evaluation=25.301582
2020/02/13 12:17:42 [INFO] Trial finished: trialID=15 state=Complete evaluation=101.474880
2020/02/13 12:17:42 [INFO] Trial finished: trialID=16 state=Complete evaluation=55.456304
2020/02/13 12:17:42 [INFO] Trial finished: trialID=17 state=Complete evaluation=124.467824
2020/02/13 12:17:42 [INFO] Trial finished: trialID=18 state=Complete evaluation=90.639886
2020/02/13 12:17:42 [INFO] Trial finished: trialID=19 state=Complete evaluation=118.767107
2020/02/13 12:17:42 [INFO] Trial finished: trialID=20 state=Complete evaluation=1.600451
2020/02/13 12:17:42 [INFO] Trial finished: trialID=21 state=Complete evaluation=1.773377
2020/02/13 12:17:42 [INFO] Trial finished: trialID=22 state=Complete evaluation=126.694023
2020/02/13 12:17:42 [INFO] Trial finished: trialID=23 state=Complete evaluation=4.721740
2020/02/13 12:17:42 [INFO] Trial finished: trialID=24 state=Complete evaluation=6.182422
2020/02/13 12:17:42 [INFO] Trial finished: trialID=25 state=Complete evaluation=38.492587
2020/02/13 12:17:42 [INFO] Trial finished: trialID=26 state=Complete evaluation=7.623810
2020/02/13 12:17:42 [INFO] Trial finished: trialID=27 state=Complete evaluation=223.993600
2020/02/13 12:17:42 [INFO] Trial finished: trialID=28 state=Complete evaluation=0.568968
2020/02/13 12:17:42 [INFO] Trial finished: trialID=29 state=Complete evaluation=276.997937
2020/02/13 12:17:42 [INFO] Trial finished: trialID=30 state=Complete evaluation=18.515531
2020/02/13 12:17:42 [INFO] Trial finished: trialID=31 state=Complete evaluation=21.478312
2020/02/13 12:17:42 [INFO] Trial finished: trialID=32 state=Complete evaluation=0.725291
2020/02/13 12:17:42 [INFO] Trial finished: trialID=33 state=Complete evaluation=8.164464
2020/02/13 12:17:42 [INFO] Trial finished: trialID=34 state=Complete evaluation=117.068747
2020/02/13 12:17:42 [INFO] Trial finished: trialID=35 state=Complete evaluation=5.294887
2020/02/13 12:17:42 [INFO] Trial finished: trialID=36 state=Complete evaluation=10.993927
2020/02/13 12:17:42 [INFO] Trial finished: trialID=37 state=Complete evaluation=117.457269
2020/02/13 12:17:42 [INFO] Trial finished: trialID=38 state=Complete evaluation=116.157249
2020/02/13 12:17:42 [INFO] Trial finished: trialID=39 state=Complete evaluation=72.778621
2020/02/13 12:17:42 Best evaluation=0.568968 (x1=7.343916, x2=-7.627814)
```

**Comment by c-bata** [comment]
By the way, I couldn't understand the reason why the values are shifted to `[0, r]`. The following implementation also performs well as I expected.

```python
    def _sample_discrete_uniform(self, distribution, below, above):
        # type:(distributions.DiscreteUniformDistribution, np.ndarray, np.ndarray) -> float

        q = distribution.q
        low = distribution.low - 0.5 * q
        high = distribution.high + 0.5 * q
        best_sample = self._sample_numerical(low, high, below, above, q=q)
        return min(max(best_sample, distribution.low), distribution.high)
```

**Comment by toshihikoyanase** [comment]
@c-bata 

> By the way, I couldn't understand the reason why the values are shifted to [0, r].

It was introduced by https://github.com/optuna/optuna/pull/321. The TPESampler in v0.8.0 actually employed the implementation you mentioned:

But, the behavior was not intuitive in some cases. For example, `trial.suggest_discrete_uniform('x', 64, 1312, 160)` will return following values:

```
v0.8.0
64, 160, 320, ..., 1280, 1312

v0.9.0
64, 224, 384, ..., 1024, 1184
```

The returned values of v0.8.0 are not equally arranged while those of v0.9.0 are arranged equally.

**Comment by c-bata** [comment]
I see! Thank you for your explanation.

**Pull request merged**
