### PR TITLE
Remove version constraint of `setuptools`

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

`setuptools` 60.5.0 has been released, https://github.com/pypa/setuptools/releases/tag/v60.5.0. 

## Description of the changes

Undo the version constraints introduced by https://github.com/optuna/optuna/pull/3207

### CODE REVIEW

**Comment by hvy** [comment]
Nice. Curious but do you know in what sense the previous failure was fixed with this recent release? I first though that we'd have to wait for mpi4py.

**Comment by nzw0301** [comment]
The previous failure was due to undefined `get_versions` in `setuptools` for `cygwin`, https://github.com/mpi4py/mpi4py/issues/157. New `setutools` restores `get_versions` attrubute by [this PR](https://github.com/pypa/setuptools/pull/2987/files#diff-379cbf81eb666c24bdd780d16a9db7ce56d84a0740149641b9942524e25790d8R358). https://github.com/pypa/setuptools/issues/2969#issuecomment-1002626007 might be a relevant comment.

**Comment by toshihikoyanase** [comment]
@HideakiImamura Could you review this PR? This PR will revert the change of your PR #3207.

**Review by HideakiImamura — APPROVED** [review]
LGTM!

**Pull request merged**
