### PR TITLE
Add an external project in Optuna examples

### LINKED ISSUE #1877: Proposal to add optuna example for materials science
## Motivation
I am working on ML application in materials science and recently published a paper which utilize Optuna as a black-box problem solver:
Automated crystal structure analysis based on blackbox optimisation
https://www.nature.com/articles/s41524-020-0330-9

I think it is interesting if a non-ML example is added to Optuna example because it will demonstrate the capability of Optuna for various problems.

## Description
If you are interested in this proposal, I will prepare an example notebook (.ipynb) based on our existing code and send a pull request.
Our repo is here:
https://github.com/quantumbeam/BBO-Rietveld
https://github.com/quantumbeam/BBO-Rietveld/blob/master/1_Y2O3.ipynb

Probably, I should add some comments to make it easy to understand for non-specialists.

## Appendix
Commentary articles on this paper (Japanese)
https://academist-cf.com/journal/?p=13774

### PR DESCRIPTION
**Pull request by resnant**
Close #1877 
## Motivation

To demonstrate that Optuna can be applied to various black box optimization problems, not just hyperparameter tuning in machine learning.

## Description of the changes

I added our project repo in `optuna/example/README.md` under "External projects using Optuna".

### CODE REVIEW

**Review by hvy — APPROVED** [review]
LGTM! 

Thanks for sharing your very interesting use case. It seems like you're taking advantage of the define-by-run/eager search space definition as well. I noticed that you're using Optuna 0.14. You might see speed improvements and new features such as hyperparameter importance if you try updating to later versions.

This is by the way a nit but the projects are actually sorted lexicographically so you could place this line after "Allegro Trains".

**Comment by resnant** [comment]
Hi @hvy , 
Thank you for the prompt review.
Following your comment, I will place the line after  "Allegro Trains" and update this PR.

**Review by hvy — APPROVED** [review]
LGTM!

**Review by HideakiImamura — APPROVED** [review]
LGTM!

**Comment by resnant** [comment]
I don't know why, but CircleCI seems to be stuck.
Do you have any suggestions to solve this?

**Comment by HideakiImamura** [comment]
Hmm... I'm not sure why the CI is stuck, but I know that the same phenomenon occurred in other PR (https://github.com/optuna/optuna/pull/1832). In the previous PR, we re-created the PR. 

However, we currently plan to migrate CI from CircleCI to GitHub actions. After completing this migration, if you merge the master branch, this problem will be resolved. So, could you wait for the migration? I will notify you if the migration is completed.

**Comment by resnant** [comment]
OK, since the change is minor, I don't hurry to merge this PR.
I will merge the latest master branch into my working branch when the migration completed.

**Comment by HideakiImamura** [comment]
Hi @resnant! The migration has been completed. Could you merge the master branch?

**Comment by HideakiImamura** [comment]
@resnant Thanks for your swift action! Let me merge this PR.

**Comment by resnant** [comment]
Thanks!

**Pull request merged**
