### PR TITLE
Remove redundant loop in `_get_rank_subplot_info`

### PR DESCRIPTION
**Pull request by RektPunk**
## Motivation
Making faster by removing wasted for-loop.

## Description of the changes
Combine the loops into one loop for trial.

### CODE REVIEW

**Comment by c-bata** [comment]
Let me update the PR description since this PR is not related to #5409.

**Comment by c-bata** [comment]
@RektPunk Since the motivation of this PR is to improve speed, could you prepare a microbenchmark script and share the results with us? Please note that the microbenchmark script should not be pushed to the Optuna repository, but instead, please share it through the comments of this PR or via Gist.

**Comment by RektPunk** [comment]
You're right @c-bata, it's not a significant difference though, but you can see the difference in the script below.
<details>

```python

import numpy as np
from datetime import datetime
import optuna

def sphere(trial: optuna.Trial) -> float:
    X = np.asarray([trial.suggest_float(f"x{i}", -5, 5) for i in range(10)])
    return np.sum(X ** 2)


study = optuna.create_study()
study.optimize(sphere, n_trials=1000)

trials = study.get_trials(deepcopy=False, states=(1,))
params = {"x0", "x1"}
target_values = np.array([trial.value for trial in trials])
colors = np.array([(204, 204, 204) for _ in range(1000)])

before = datetime.now()
x_param = "x1"
y_param = "x2"

infeasible_trial_ids = []
for i in range(len(trials)):
    constraints = trials[i].system_attrs.get("constraints")
    if constraints is not None and any([x > 0.0 for x in constraints]):
        infeasible_trial_ids.append(i)

colors[infeasible_trial_ids] = (204, 204, 204)  # equal to "#CCCCCC"

filtered_ids = [
    i
    for i in range(len(trials))
    if x_param in trials[i].params and y_param in trials[i].params
]
filtered_trials = [trials[i] for i in filtered_ids]
xs = [trial.params[x_param] for trial in filtered_trials]
ys = [trial.params[y_param] for trial in filtered_trials]
zs = target_values[filtered_ids]
colors = colors[filtered_ids]
after = datetime.now()
print((after - before).total_seconds())

before = datetime.now()
x_param = "x1"
y_param = "x2"
infeasible_trial_ids = []
filtered_ids = []
for idx, trial in enumerate(trials):
    constraints = trial.system_attrs.get("constraints")
    if constraints is not None and any([x > 0.0 for x in constraints]):
        infeasible_trial_ids.append(idx)

    if x_param in trial.params and y_param in trial.params:
        filtered_ids.append(idx)

filtered_trials = [trials[i] for i in filtered_ids]
xs = [trial.params[x_param] for trial in filtered_trials]
ys = [trial.params[y_param] for trial in filtered_trials]
zs = target_values[filtered_ids]
colors[infeasible_trial_ids] = (204, 204, 204)
colors = colors[filtered_ids]
after = datetime.now()
print((after - before).total_seconds())
```
result >
```cmd
0.002047
0.001205
```
</details>

**Review by eukaryo — APPROVED** [review]
LGTM.

**Review by c-bata — APPROVED** [review]
Thank you for sharing the microbenchmark results! I modified your script to compare the speed of `_get_rank_info()` functions.

```python
import numpy as np
from datetime import datetime
import optuna
import time
from optuna.visualization._rank import _get_rank_info

def sphere(trial: optuna.Trial) -> float:
    X = np.asarray([trial.suggest_float(f"x{i}", -5, 5) for i in range(10)])
    return np.sum(X ** 2)

study = optuna.create_study(sampler=optuna.samplers.RandomSampler(seed=1))
study.optimize(sphere, n_trials=10000)

elapsed = []
for i in range(10):
    start = time.time()
    _get_rank_info(study, None, None, "Objective Value")
    elapsed.append(time.time() - start)

print(f"Elapsed: {np.mean(elapsed):.4f} seconds (+/- {np.std(elapsed):.4f})")
```

`master`

- 1000 trials: 0.2344 seconds (+/- 0.0037)
- 10000 trials: 3.0675 seconds (+/- 0.0230)

`RektPunk:refactor-rank-subplot-info`

- 1000 trials: 0.2258 seconds (+/- 0.0016)
- 10000 trials: 3.0951 seconds (+/- 0.0426)

From the above results, I cannot see the performance improvements on this PR since it takes longer than `master` branch when I increased trials to 10000. According to the output of cProfile, we need to make `_get_axis_info` function (including`_is_logscale` and `is_numerical` functions) faster as reported at #5409.

https://gist.github.com/c-bata/6e6d829aa2062feda761a1d66fe308a5#file-cprofile_get_rank_info-py

But anyway, I think this PR is acceptable as a refactoring. It's slightly reduces the number of lines of code and code looks easier to read than using list comprehensions.

LGTM.

**Pull request merged**
