### PR TITLE
Use `study.ask()` in tests instead of `create_new_trial` (#5804)

### PR DESCRIPTION
**Pull request by unKnownNG**
## Motivation
The method `create_new_trial` has been replaced by `study.ask()` in the relevant tests to unify the backend logic and simplify the trial creation process. 

## Description of the changes
The lines of code from `Trial(study, study._storage.create_new_trial(study._study_id))` have been changed to `study.ask()` as mentioned in the issue #5804

### CODE REVIEW

**Review by not522 — APPROVED** [review]
LGTM!

**Comment by not522** [comment]
@porink0424 Could you review this PR?

**Review by porink0424 — CHANGES_REQUESTED** [review]
`test_trial.py` looks good to me.
As mentioned in #5804, please also address the following as well:
- [pruners_tests/test_percentile.py](https://github.com/optuna/optuna/blob/master/tests/pruners_tests/test_percentile.py)
 - [pruners_tests/test_successive_halving.py](https://github.com/optuna/optuna/blob/master/tests/pruners_tests/test_successive_halving.py)

**Review by porink0424 — APPROVED** [review]
We discussed internally and decided to address the other files in separate PRs, so this PR LGTM 👍

**Pull request merged**
