### PR TITLE
Removed MOTESampler from documentation

### PR DESCRIPTION
**Pull request by Ashhar-24**

### CODE REVIEW

**Comment by HideakiImamura** [comment]
Thank you for your contribution. Let me point out some points.
- You should only fix the document for that issue.
- Please provide the PR description to tell reviewers the details of changes. Specifically, the issue number.

**Comment by Ashhar-24** [comment]
Thank you for your response @HideakiImamura .

- Ok sure, I will make the changes in the "indes.rst file only" and describe the changes I made in my pull request.
- Can you please tell me what is CI and how should I pass that because I'm new to Open source and this is my initial PRs :).

thanks for your cooperation.

**Comment by nzw0301** [comment]
@Ashhar-24 https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration

> how should I pass

An easy way to just update the pull request that is a trigger to run the CI, and see the CI result. I highly recommend reading https://github.com/optuna/optuna/blob/master/CONTRIBUTING.md when you send a pull request.

**Comment by nzw0301** [comment]
The current changes include the MOTPE file removal that makes CI fail, so please revert the file removal and write the issue description clearly first.

**Pull request closed without merging**
