### PR TITLE
Remove all CircleCI config.

### PR DESCRIPTION
**Pull request by toshihikoyanase**
## Motivation

- This repository would migrate CI jobs from CircleCI to GitHub Actions
- #4160 removed the `document` job and the existing job is `visual-regression-test`
- Recently, we do not have many PRs that require visual regression tests, and we'd like to remove it.
- The results are mainly checked by reviewers, and this change will not affect developers.

## Description of the changes

- Remove CircleCI config.

### CODE REVIEW

**Review by c-bata — CHANGES_REQUESTED** [review]
Thank you for the pull request. Should we also remove the following file?
https://github.com/optuna/optuna/blob/master/.github/workflows/circleci-artifacts-link.yml

**Comment by c-bata** [comment]
It looks that the status badge of CircleCI can also be removed.
https://github.com/optuna/optuna#readme

**Comment by toshihikoyanase** [comment]
@c-bata Thank you for your review.

I removed `circleci-artifacts-link.yml` in https://github.com/optuna/optuna/pull/4315/commits/196a95fadc796d6049f17b4d8da8bb58f537f8c6 and the CircleCI budge in https://github.com/optuna/optuna/pull/4315/commits/3d6d4fd1b6bc54245d138d1ed2eb76e52ca565c2.

Also, I found the word `CircleCI` in `CONTRIBUTING.md` and a source file, and removed the corresponding contents in https://github.com/optuna/optuna/pull/4315/commits/fb40c78e5ce0af2bd28f227c0cc4c3628ab0030e and https://github.com/optuna/optuna/pull/4315/commits/e6dc350dc03610e64904316891570f797428df09.

**Review by c-bata — APPROVED** [review]
Good catch! LGTM.

[FYI] I will update the wiki after merged this PR as a follow-up.
https://github.com/optuna/optuna/wiki/Test-Policy#visualization-modules

**Comment by c-bata** [comment]
Let me merge this PR since this PR only updates the CI settings and the source code comment.

**Comment by c-bata** [comment]
I removed the description about visual-regression-tests from the wiki page.
https://github.com/optuna/optuna/wiki/Test-Policy/_compare/9a3e5337a14900700697c8b2c01ee03e41b98ab4...0e08c2b9280e905bd29773e6f15996ca69b7bd1f

**Pull request merged**
