### PR TITLE
Add badge on README that launches starter notebook

### PR DESCRIPTION
**Pull request by harupy**
This PR adds a badge on README that launches a starter notebook on Google Colab.

starter notebook: https://github.com/harupy/optuna/blob/add-starter/examples/quickstart.ipynb

related issue: #727

### CODE REVIEW

**Comment by harupy** [comment]
It looks like this.

Screen Shot 2019-11-27 at 19 31 40

**Comment by harupy** [comment]
@hvy Now the notebook contains all the cell output. Should I remove it to decrease the file size?

**Comment by hvy** [comment]
Thanks a lot for your quick action. As for the cell outputs, this isn't a strong opinion so am open for discussion, but the logging is rather verbose so I'd personally prefer to exclude it. Also considering the file size. Although this only affects the users directly cloning the repository and not those who'll install it via pip as `examples` isn't included.

**Comment by harupy** [comment]
@hvy Thanks for the reply. I'd also prefer to exclude the cell outputs.

**Comment by harupy** [comment]
@hvy Removed the cell outputs.

**Pull request merged**
