### PR TITLE
Fix links on `SuccessiveHalvingPruner` page

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

See #2488
## Description of the changes

Fix the links.

### CODE REVIEW

**Comment by nzw0301** [comment]
If the links should be permanent links, please let me know. I will update the line based on the latest stable version.

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by HideakiImamura** [comment]
@keisuke-umezawa Could you review this PR?

**Review by keisuke-umezawa — APPROVED** [review]

**Comment by nzw0301** [comment]
Thank you for your quick checks!

**Pull request merged**
