### PR TITLE
Remove unnecessary sklearn version condition

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

As in https://github.com/optuna/optuna/blob/ead2e13953915bf4ebb50d5880f069a29bb34ffb/pyproject.toml#L103, sklearn's integration assumes `sklearn>=0.24.2`. However, integration code has  unnecessary condition for this: `sklearn>=0.22`.

## Description of the changes

Remove the condition.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@c-bata @gen740 Could you review this PR?

**Review by gen740 — APPROVED** [review]
LGTM!

**Review by c-bata — APPROVED** [review]
Good catch! LGTM.

**Comment by c-bata** [comment]
After merging this PR, checks-integration became being failed :bow:
https://github.com/optuna/optuna/actions/runs/4130385467/jobs/7137016344

I've just created a follow-up PR on https://github.com/optuna/optuna/pull/4407.

**Pull request merged**
