### PR TITLE
Remove deprecated LightGBM arguments in integration tests

### PR DESCRIPTION
**Pull request by 29Takuya**
## Motivation

Remove deprecated LightGBM arguments in integration tests.
ref: https://github.com/optuna/optuna/issues/3771

## Description of the changes

With referring to https://github.com/optuna/optuna-examples/pull/64, I made the following updates.
- Replaced deprecated arguments with callbacks.
- Specify lightgbm version because the callbacks were introduced at v3.3.0.

I confirmed this issue was resolved in my local environment. (Please see https://github.com/optuna/optuna/issues/3771#issue-1298359702 for comparison)

```
$ pytest tests/integration_tests/test_lightgbm.py tests/integration_tests/lightgbm_tuner_tests
========================================================================== test session starts ===========================================================================
platform darwin -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/shimada/Work/git/optuna, configfile: pyproject.toml
collected 117 items                                                                                                                                                      

tests/integration_tests/test_lightgbm.py ............                                                                                                              [ 10%]
tests/integration_tests/lightgbm_tuner_tests/test_alias.py ..................                                                                                      [ 25%]
tests/integration_tests/lightgbm_tuner_tests/test_optimize.py .......................................................................................              [100%]

============================================================================ warnings summary ============================================================================
tests/integration_tests/test_lightgbm.py: 14 warnings
  /Users/shimada/Work/miniconda3/envs/optuna/lib/python3.8/site-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================== 117 passed, 14 warnings in 275.65s (0:04:35) ==============================================================
```

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@toshihikoyanase Could you review this PR?

**Comment by 29Takuya** [comment]
Now I am investigating the reason why CI test fails. Please be patient 🙏

**Comment by 29Takuya** [comment]
I found the reproducibility test fails here.
https://github.com/optuna/optuna/runs/7245502947?check_suite_focus=true#step:7:12514

```python3

=================================== FAILURES ===================================
___________ TestLightGBMTunerCV.test_tune_best_score_reproducibility ___________
self = <tests.integration_tests.lightgbm_tuner_tests.test_optimize.TestLightGBMTunerCV object at 0x7f0b4cd08e50>
    def test_tune_best_score_reproducibility(self) -> None:
        california = sklearn.datasets.fetch_california_housing()
        X_trainval, X_test, y_trainval, y_test = train_test_split(
            california.data, california.target, random_state=0
        )
        train = lgb.Dataset(X_trainval, y_trainval)
        params = {
            "objective": "regression",
            "metric": "rmse",
            "random_seed": 0,
            "deterministic": True,
            "force_col_wise": True,
            "verbosity": -1,
        }
        tuner_first_try = lgb.LightGBMTunerCV(
            params,
            train,
            callbacks=[early_stopping(3)],
            folds=KFold(n_splits=3),
            optuna_seed=10,
        )
        tuner_first_try.run()
        best_score_first_try = tuner_first_try.best_score
        tuner_second_try = lgb.LightGBMTunerCV(
            params,
            train,
            callbacks=[early_stopping(3)],
            folds=KFold(n_splits=3),
            optuna_seed=10,
        )
        tuner_second_try.run()
        best_score_second_try = tuner_second_try.best_score
>       assert best_score_second_try == best_score_first_try
E       assert 0.4585593547797182 == 0.4606224292281677
tests/integration_tests/lightgbm_tuner_tests/test_optimize.py:1107: AssertionError
```

I wonder why this test passes in my local environment 🤔
I will keep working to fix this problem.

**Comment by 29Takuya** [comment]
Hmmm, it seems replacing `early_stopping_rounds` with `early_stopping` callback induces randomness.
That sounds strange...

**Comment by toshihikoyanase** [comment]
I'm not sure, but the randomness might come from parallelization. How about setting`OMP_NUM_THREADS=1` in `.github/workflows/tests-integration.yml`?
https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html#add-more-computational-resources
https://github.com/optuna/optuna/blob/e8b6922515f8666352f025ccba341afd9d1339ed/.github/workflows/tests-integration.yml#L60-L80

**Comment by toshihikoyanase** [comment]
Ah, the test case set `deterministic=True`, and `OMP_NUM_THREADS` is not related to this issue. Sorry for bothering you.

https://lightgbm.readthedocs.io/en/latest/Parameters.html#deterministic

**Comment by 29Takuya** [comment]
Thank you for the information!

While I said this test passes in my local environment, when I check it again, it raises the same error.
I am sorry for the confusion.

**Comment by 29Takuya** [comment]
Let me re-push each commit one by one to see CI results at each point.

**Comment by nzw0301** [comment]
In the current latest stable of lightgbm, the `early_stopping_rounds` argument and `early_stopping` callback are not the same functionality unintendedly. Specifically, the latter one has a bug, which has been fixed by https://github.com/microsoft/LightGBM/pull/4868. Indeed, the same failed test case for reproducibility has been observed in 
 https://github.com/optuna/optuna/pull/3191 too.

I think we need to wait for the next release of lightgbm that includes the patch to fix the `early_stopping` callback. In addition, we need to update Optuna's code too according to https://github.com/optuna/optuna/issues/3646.

**Comment by 29Takuya** [comment]
@nzw0301 Thank you for letting me know! 

As you mentioned, I found #3191 is almost identical to this PR.
I also agree with your idea that we will replace deprecated arguments with the upcoming release of LightGMB.

I am going to close this PR since it is duplicated with #3191.
Would that be fine with you? @HideakiImamura @toshihikoyanase

**Pull request closed without merging**
