### PR TITLE
Backport of #2717

### PR DESCRIPTION
**Pull request by hvy**
Fix results not reproducible when running AllenNLPExecutor multiple t…

## Motivation

See below.

## Description of the changes

Backport of https://github.com/optuna/optuna/pull/2717 to include bug fix in v2.8.0.

Cc. @himkt

### CODE REVIEW

**Review by himkt — APPROVED** [review]
Thank you for picking up.

**Review by HideakiImamura — APPROVED** [review]
LGTM!

**Comment by hvy** [comment]
Thank you both for the prompt review!

**Comment by hvy** [comment]
Looks like CI is green!

**Pull request merged**
