### PR TITLE
Update sphinx build's `upload-artifact` version

### LINKED ISSUE #5743: Update `actions/upload-artifact` to v4 from v3
### Motivation

As announced by https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/, we have not been able to use `actions/upload-artifact@v3` since 30 November 2024.

### Suggestion

Update the version in https://github.com/optuna/optuna/blob/master/.github/workflows/sphinx-build.yml to v4 and update the workflow if necessary.

### Additional context (optional)

_No response_

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Close #5743. 

## Description of the changes

Update the version to v4.

### CODE REVIEW

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by HideakiImamura** [comment]
@kAIto47802 Could you review this PR?

**Comment by HideakiImamura** [comment]
@nabenabe0928 Could you review this PR?

**Review by nabenabe0928 — APPROVED** [review]
LGTM!

**Pull request merged**
