### PR TITLE
Separate after_trial strategy

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Progress v3.3 task to make `NSGAII Sampler` loose coupled.

## Description of the changes
Add `after_trial_strategy` argument to the constructor if `NSGAIISampler` and `NSGAIIISampler` and separate the after_trial process so that users can customize `after_trial()`.

### CODE REVIEW

**Comment by Alnusjaponica** [comment]
I am going to add test for the change and explanation on the new feature in the document then I make this PR review ready.

**Comment by Alnusjaponica** [comment]
@c-bata 
I updated the PR. Could you assign reviews?

**Comment by c-bata** [comment]
@Alnusjaponica Thank you for the reminder. It looks that some tests are still failing. Is this PR ready for review?

**Comment by Alnusjaponica** [comment]
These failures seem irrelevant to this PR, because I just added code comments since the last update.
I submitted a https://github.com/optuna/optuna/pull/4786 to temporary fix them .

**Comment by c-bata** [comment]
@HideakiImamura @gen740 Could you review this PR? CI statuses will be fixed after merging #4788.

**Comment by Alnusjaponica** [comment]
It seems some test did not run properly. Is it possible to re run them all?

**Review by gen740 — APPROVED** [review]
LGTM!

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
