### PR TITLE
Add GCSArtifactStore

### PR DESCRIPTION
**Pull request by semiexp**
## Motivation

This is an implementation of #4949.

## Description of the changes

Added `GCSArtifactStore`.

### CODE REVIEW

**Comment by contramundum53** [comment]
Could you also test the `remove` function?

**Comment by semiexp** [comment]
Just added `test_remove`

**Review by contramundum53 — APPROVED** [review]
LGTM! Thanks for the PR!

**Comment by contramundum53** [comment]
I checked that the `ArtifactBackend` works.

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
