### PR TITLE
Drop tensorflow constraints

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

TensorFlow and Keras 2.6.0 have been released. Since this release, `tf.keras` uses [`keras-team/keras`](https://github.com/keras-team/keras) instead of the keras under the TensorFlow repo. 

## Description of the changes

Remove the constraints introduced by 

- https://github.com/optuna/optuna/pull/2851
- https://github.com/optuna/optuna/pull/2674
- https://github.com/optuna/optuna/pull/2530

### CODE REVIEW

**Review by himkt — APPROVED** [review]
I confirmed that tests passed with `tensorflow==2.6.0`.

**Comment by nzw0301** [comment]
I realised that https://github.com/optuna/optuna/pull/2672/ also resolves the same issue...

**Comment by hvy** [comment]
Thanks for the heads up. 
Let me close https://github.com/optuna/optuna/pull/2672 which is somewhat stale in favor of this PR.

**Comment by hvy** [comment]
Leaving some notes from a discussion I had with @nzw0301 .

- `import keras` should be avoided and one should instead import keras via `tensorflow`.
- Whether we should keep both `KerasPruningCallback` (currently deprecated) and `TFKerasPruningCallback` has been discussed before and is still an open discussion. It can be discussed outside the scope of this PR however.

**Review by hvy — COMMENTED** [review]
The changes LGTM. However, with these changes, we'll basically start supporting the latest tensorflow with our callbacks. My only concern is that `KerasPruningCallback` may start to break given the above comment in a way that's difficult to fix without reintroducing these version constraints (in which case we'll need to test `KerasPruningCallback` and `TFKerasPruningCallback` against different versions of `keras` and `tensorflow`). What do you think @nzw0301 ?

**Comment by nzw0301** [comment]
Thank you for sharing your perspective and review!

In my understanding, Keras has required TensorFlow explicitly since [Keras v2.4.0](https://github.com/keras-team/keras/releases/tag/2.4.0), which was released in June 2020. So personally, `TFKerasPruningCallback` is supposed to be enough and `KerasPruningCallback` might be removed in the next major version of Optuna (v3.0.0). Before that, we can fix the versions of Keras and TensorFlow 2.6.0 if a newer keras breaks instead of reintroducing tests for multiple keras versions.

**Review by hvy — APPROVED** [review]
Sounds good and LGTM!

**Pull request merged**
