### PR TITLE
Fix `matplotlib.plot_parallel_coordinate` with only one suggested parameter.

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

As discussed in https://github.com/optuna/optuna/issues/2011, `matplotlib.plot_parallel_coordinate` raises the error if a hyper-parameter contains only one unique value.

## Description of the changes

To avoid the zero-divide, if a hyper-parameter contains only one unique value, set a middle value based on objective values.

### CODE REVIEW

**Review by HideakiImamura — COMMENTED** [review]
Thanks for your quick fix and looks reasonable to me. How about adding a test to verify this behavior?

**Comment by HideakiImamura** [comment]
@crcrpar Could you review this PR if you have time? Please feel free to remove the assignment if you are busy.

**Comment by nzw0301** [comment]
@HideakiImamura Thank you for your feedback. I have added the test: 02ccd05.

**Review by crcrpar — APPROVED** [review]

**Review by HideakiImamura — APPROVED** [review]
Thanks for your quick response! LGTM!

**Pull request merged**
