### PR TITLE
Fix `matplotlib.plot_contour` bug

### LINKED ISSUE #3039: Fix labels on the `matplotlib.plot_contour` with more than two params
## Expected behavior

The red circled part should be fixed since the actual range is `(-100, 100)`.

Screenshot 2021-10-25 at 21 26 49

As a reference, plotly's counter plot is as follows:

Screenshot 2021-10-25 at 21 30 10

## Environment

- Optuna version:3.0.0a1.dev
- Python version:3.8.12
- OS:macOS-10.16-x86_64-i386-64bit
- (Optional) Other libraries and their versions:
    - matplotlib                    3.4.2
    - plotly                        5.3.1

## Steps to reproduce

Please run the following code. Note that the plot with two params: `optuna.visualization.matplotlib.plot_contour(study, params=["y", "x"])` is fine.

## Reproducible examples (optional)
```python
import optuna


def objective(trial):
    x = trial.suggest_float("x", -100, 100)
    y = trial.suggest_categorical("y", [-1, 0, 1])
    z = trial.suggest_categorical("z", [-1, 0, 1])    
    return x ** 2 + y - z


sampler = optuna.samplers.TPESampler(seed=10)
study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=30)

optuna.visualization.matplotlib.plot_contour(study)
```

### PR DESCRIPTION
**Pull request by IEP**
Close #3039  about `matplotlib.plot_contour` bug 

## Description

When the top left subplot is being plotted, the `len(zi) == 0` thus
- `ax.set_xlim(x_values_range[0], x_values_range[1])`, and
- `ax.set_ylim(y_values_range[0], y_values_range[1])`
are not executed and resulting the top left subplot doesn't have proper `xlim` and `ylim`

### CODE REVIEW

**Comment by nzw0301** [comment]
I took a benchmark to compare the speed between the master branch and https://github.com/optuna/optuna/pull/3046#issuecomment-954904185, namely, not-skipped using the same code as in https://github.com/optuna/optuna/pull/3046#issuecomment-954572745. 

- Master: 14.2 s ± 620 ms per loop (mean ± std. dev. of 7 runs, 1 loop each) 
- not-skipped: 21.5 s ± 723 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

This difference might not be acceptable...

**Comment by IEP** [comment]
The heavy part that causes significant addition to the execution time is related to

```python
zmap = _create_zmap(x_array, y_array, z_values, xi, yi)
_interpolate_zmap(zmap, contour_point_num)
zi = _create_zmatrix_from_zmap(zmap, contour_point_num)
```

and the condition `x_param != y_param` can be moved to guard this snippet.

Benchmark:
- Original: 9.05 s ± 59.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
- Patch (move condition): 9.03 s ± 178 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by nzw0301** [comment]
@IEP Brilliant! Thank you for the additional update. It looks great to me.

**Review by nzw0301 — APPROVED** [review]

**Comment by nzw0301** [comment]
@Crissman let me merge this PR 🙏🏻

**Pull request merged**
