### PR TITLE
Drop sklearn constraint

### LINKED ISSUE #1785: Review constrain scikit-learn< 0.23
scikit-optimize 0.8.1 has been released which works together with scikit-learn >= 0.23

https://github.com/scikit-optimize/scikit-optimize/releases/tag/v0.8.1

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Fix #1785

### CODE REVIEW

**Comment by nzw0301** [comment]
I will fix the following error of `test_nan_objective_value` in `tests/samplers_tests/test_samplers.py` when `sampler` is `optuna.integration.skopt.SkoptSampler` instance.
```bash
$ pytest tests/samplers_tests/test_samplers.py
================================================================= test session starts =================================================================
platform darwin -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/nzw/PycharmProjects/optuna
collected 87 items

tests/samplers_tests/test_samplers.py .....................................................................................F.                   [100%]

====================================================================== FAILURES =======================================================================
_________________________________________________________ test_nan_objective_value[<lambda>2] _________________________________________________________

sampler_class = <function <lambda> at 0x7fcb9489b8b0>

    @parametrize_sampler
    def test_nan_objective_value(sampler_class: Callable[[], BaseSampler]) -> None:

        study = optuna.create_study(sampler=sampler_class())

        def objective(trial: Trial, base_value: float) -> float:

            return trial.suggest_uniform("x", 0.1, 0.2) + base_value

        # Non NaN objective values.
        for i in range(10, 1, -1):
            print(i, study.sampler)
>           study.optimize(lambda t: objective(t, i), n_trials=1, catch=())

tests/samplers_tests/test_samplers.py:349:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
optuna/study.py:338: in optimize
    self._optimize_sequential(
optuna/study.py:747: in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
optuna/study.py:776: in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
optuna/study.py:795: in _run_trial
    trial = trial_module.Trial(self, trial_id)
optuna/trial/_trial.py:56: in __init__
    self._init_relative_params()
optuna/trial/_trial.py:65: in _init_relative_params
    self.relative_params = self.study.sampler.sample_relative(
optuna/integration/skopt.py:168: in sample_relative
    optimizer.tell(study, complete_trials)
optuna/integration/skopt.py:273: in tell
    self._optimizer.tell(xs, ys)
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/skopt/optimizer/optimizer.py:493: in tell
    return self._tell(x, y, fit=fit)
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/skopt/optimizer/optimizer.py:536: in _tell
    est.fit(self.space.transform(self.Xi), self.yi)
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/skopt/learning/gaussian_process/gpr.py:195: in fit
    super(GaussianProcessRegressor, self).fit(X, y)
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/sklearn/gaussian_process/_gpr.py:232: in fit
    optima = [(self._constrained_optimization(obj_func,
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/sklearn/gaussian_process/_gpr.py:501: in _constrained_optimization
    opt_res = scipy.optimize.minimize(
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/scipy/optimize/_minimize.py:617: in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/scipy/optimize/lbfgsb.py:306: in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/scipy/optimize/optimize.py:261: in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py:76: in __init__
    self._update_fun()
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py:166: in _update_fun
    self._update_fun_impl()
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py:73: in update_fun
    self.f = fun_wrapped(self.x)
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py:70: in fun_wrapped
    return fun(x, *args)
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/scipy/optimize/optimize.py:74: in __call__
    self._compute_if_needed(x, *args)
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/scipy/optimize/optimize.py:68: in _compute_if_needed
    fg = self.fun(x, *args)
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/sklearn/gaussian_process/_gpr.py:224: in obj_func
    lml, grad = self.log_marginal_likelihood(
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/sklearn/gaussian_process/_gpr.py:476: in log_marginal_likelihood
    alpha = cho_solve((L, True), y_train)  # Line 3
../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/scipy/linalg/decomp_cholesky.py:194: in cho_solve
    b1 = asarray_chkfinite(b)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

a = array([[nan]]), dtype = None, order = None

    @set_module('numpy')
    def asarray_chkfinite(a, dtype=None, order=None):
        """Convert the input to an array, checking for NaNs or Infs.

        Parameters
        ----------
        a : array_like
            Input data, in any form that can be converted to an array.  This
            includes lists, lists of tuples, tuples, tuples of tuples, tuples
            of lists and ndarrays.  Success requires no NaNs or Infs.
        dtype : data-type, optional
            By default, the data-type is inferred from the input data.
        order : {'C', 'F'}, optional
             Whether to use row-major (C-style) or
             column-major (Fortran-style) memory representation.
             Defaults to 'C'.

        Returns
        -------
        out : ndarray
            Array interpretation of `a`.  No copy is performed if the input
            is already an ndarray.  If `a` is a subclass of ndarray, a base
            class ndarray is returned.

        Raises
        ------
        ValueError
            Raises ValueError if `a` contains NaN (Not a Number) or Inf (Infinity).

        See Also
        --------
        asarray : Create and array.
        asanyarray : Similar function which passes through subclasses.
        ascontiguousarray : Convert input to a contiguous array.
        asfarray : Convert input to a floating point ndarray.
        asfortranarray : Convert input to an ndarray with column-major
                         memory order.
        fromiter : Create an array from an iterator.
        fromfunction : Construct an array by executing a function on grid
                       positions.

        Examples
        --------
        Convert a list into an array.  If all elements are finite
        ``asarray_chkfinite`` is identical to ``asarray``.

        >>> a = [1, 2]
        >>> np.asarray_chkfinite(a, dtype=float)
        array([1., 2.])

        Raises ValueError if array_like contains Nans or Infs.

        >>> a = [1, 2, np.inf]
        >>> try:
        ...     np.asarray_chkfinite(a)
        ... except ValueError:
        ...     print('ValueError')
        ...
        ValueError

        """
        a = asarray(a, dtype=dtype, order=order)
        if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
>           raise ValueError(
                "array must not contain infs or NaNs")
E           ValueError: array must not contain infs or NaNs

../../.pyenv/versions/miniconda3-latest/envs/optuna/lib/python3.8/site-packages/numpy/lib/function_base.py:485: ValueError
---------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------
[I 2020-10-02 20:40:07,338] A new study created in memory with name: no-name-18f3361c-1857-4259-9b36-1c56b963587b
[I 2020-10-02 20:40:07,338] Trial 0 finished with value: 10.11578536329118 and parameters: {'x': 0.11578536329117885}. Best is trial 0 with value: 10.11578536329118.
================================================================== warnings summary ===================================================================
tests/samplers_tests/test_samplers.py: 16 warnings
  /Users/nzw/PycharmProjects/optuna/optuna/samplers/_tpe/sampler.py:188: ExperimentalWarning: ``multivariate`` option is an experimental feature. The interface can change in the future.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================================================== short test summary info ===============================================================
FAILED tests/samplers_tests/test_samplers.py::test_nan_objective_value[<lambda>2] - ValueError: array must not contain infs or NaNs
===================================================== 1 failed, 86 passed, 16 warnings in 14.53s ======================================================
```

**Comment by toshihikoyanase** [comment]
@nzw0301 Thank you for working on #1785. In fact, it was more difficult than I thought.
I'm not sure but it might be a bug of `scikit-learn>=0.23.0` and `scikit-optimize==0.8.1`. If so, we might need to keep the constraint.

**Comment by nzw0301** [comment]
@toshihikoyanase It's my pleasure. Thank you for your comment. I will look at the bug a little bit more. As you suggested, I close this issue to keep the constraint, if the bug is causes by these packages.

**Comment by nzw0301** [comment]
I guess the error is related to https://github.com/scikit-optimize/scikit-optimize/issues/910.

**Comment by toshihikoyanase** [comment]
Thanks for your further investigation.
To save your time, I think we can revisit this PR after https://github.com/scikit-optimize/scikit-optimize/issues/910 is resolved.

**Comment by nzw0301** [comment]
@toshihikoyanase Thank you for your kind comment. I agree with you.

**Comment by nzw0301** [comment]
Somehow my branch does not sync this pull request anymore. Let me close this PR, and please check the other PR #2634.

**Pull request closed without merging**
