### PR TITLE
Fix BruteForceSampler

### LINKED ISSUE #4771: BruteForceSampler crashes with named hyperparameters out of alphabetical order
### Expected behavior

The `BruteForceSampler` should run regardless of the alphabetical order of `name`s on repeated invocations of `suggest_float(...)`.

### Environment

- Optuna version: 3.2.0
- Python version: 3.10.6
- OS: Linux-5.15.0-71-generic-x86_64-with-glibc2.35
- (Optional) Other libraries and their versions: /

### Error messages, stack traces, or logs

```shell
Traceback (most recent call last):
  File "/home/user/Desktop/minimal-example.py", line 14, in <module>
    study.optimize(objective, n_trials=100)
  File "/home/user/.virtualenvs/tmp/lib/python3.10/site-packages/optuna/study/study.py", line 443, in optimize
    _optimize(
  File "/home/user/.virtualenvs/tmp/lib/python3.10/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/home/user/.virtualenvs/tmp/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/user/.virtualenvs/tmp/lib/python3.10/site-packages/optuna/study/_optimize.py", line 212, in _run_trial
    frozen_trial = _tell_with_warning(
  File "/home/user/.virtualenvs/tmp/lib/python3.10/site-packages/optuna/study/_tell.py", line 174, in _tell_with_warning
    study.sampler.after_trial(study, frozen_trial, state, values)
  File "/home/user/.virtualenvs/tmp/lib/python3.10/site-packages/optuna/samplers/_brute_force.py", line 213, in after_trial
    tree = self._build_tree(
  File "/home/user/.virtualenvs/tmp/lib/python3.10/site-packages/optuna/samplers/_brute_force.py", line 167, in _build_tree
    leaf.set_leaf()
  File "/home/user/.virtualenvs/tmp/lib/python3.10/site-packages/optuna/samplers/_brute_force.py", line 53, in set_leaf
    self.expand(None, [])
  File "/home/user/.virtualenvs/tmp/lib/python3.10/site-packages/optuna/samplers/_brute_force.py", line 46, in expand
    raise ValueError(f"param_name mismatch: {self.param_name} != {param_name}")
```

### Steps to reproduce

```
import optuna
from optuna.samplers import BruteForceSampler


def objective(trial):
    b = trial.suggest_float(name="b", low=0, high=1, step=0.1)  # Line B
    a = trial.suggest_float(name="a", low=0, high=1, step=0.1)  # Line A
    return a * b

study = optuna.create_study(study_name="minimal-example",
                            storage="sqlite:///minimal-example.db",
                            sampler=BruteForceSampler())

study.optimize(objective, n_trials=100)
```

### Additional context (optional)

* The bug is present only when the study is created with the `storage` parameter.
* If lines A and B are switched, then the code runs without errors. Thus the assumption is that the bug has to do with alphabetical order of `name`s of suggested values.

### PR DESCRIPTION
**Pull request by contramundum53**
## Motivation
Fix #4771.

BruteForceSampler currently assumes that the storage retains the order of suggested parameters. This is currently true for all storages except for RDBStorage, but we decided not to add a constraint in storage classes, because it would then be hard to implement a new storage based on key-value stores. Instead, we rewrote BruteForceSampler not to rely on the order of parameters.

The new BruteForceSampler builds a tree from the trial history by successively choosing one "pivot" parameter that has constant distribution in the current branch. Since the candidates for the "pivot" is tried in the order of parameters of a previous trial, the behavior (the probability for choosing each branch) remains exactly the same if the storage actually retains the order.

## Description of the changes
* Change BruteForceSampler to support the cases where the order of parameters are not retained in the storage.
* Add a test that changes the order of parameters during optimization.

### CODE REVIEW

**Comment by c-bata** [comment]
@not522 @knshnb Could you review this PR if you have time?

**Comment by knshnb** [comment]
I understand the algorithm. Let me take a detailed look next week 🙏

**Comment by not522** [comment]
Sorry for my late response. I'm checking the correctness of the algorithm. I worry that I'm missing edge cases.
The stateless implementation has good points, but I think it's hard to maintain. How about reverting to the queue-based algorithm like the original implementation?

**Comment by contramundum53** [comment]
I don't think the algorithm itself (whose complexity contributes to the difficulty of maintenance) is that more complex than the previous version, and using enqueue_trial to do DFS is also tricky in another way (especially when combined with parallel optimization). How about discussing the concerns offline?

**Comment by contramundum53** [comment]
Would your concern be resolved if I put a comment describing the proof that this algorithm is correct?

**Comment by contramundum53** [comment]
If you think this algorithm is significantly more complex than the previous (without this PR) algorithm, you can also keep it as it is, since we already have #4775 merged.

**Comment by contramundum53** [comment]
After a discussion, we concluded that we can close this PR for now, since #4775 already fixes the critical problem.

**Comment by not522** [comment]
Discussion log:

Considering the shortcomings of the queue-based algorithm, the tree-based algorithm is preferred.

- The queue needs to handle trials other than the one currently being sampled.
- It does not work with other samplers at the same time.

The PR's implementation can build a wrong search tree (even then, the sampling is correct), which makes the algorithm complex. The original issue #4771 is already fixed in the currently implemented storages, then we keep the current code and will come back here when this PR is necessary.

**Pull request closed without merging**
