### PR TITLE
Fix typo in `EMMREvaluator`

### PR DESCRIPTION
**Pull request by not522**
## Motivation

`emmr_improvement_valuator` should be `emmr_improvement_evaluator`.

## Description of the changes

- Fix typo in `EMMREvaluator`

### CODE REVIEW

**Comment by nabenabe0928** [comment]
@kAIto47802 
Could you also review this PR?

**Review by nabenabe0928 — APPROVED** [review]
Thank you for the PR, LGTM!

**Review by kAIto47802 — APPROVED** [review]
Thank you for your PR. LGTM! (I also checked there is no other `_valuator`).

**Comment by not522** [comment]
@eukaryo Could you review this PR?

**Review by eukaryo — APPROVED** [review]
LGTM

**Pull request merged**
