### PR TITLE
Convert comment style type hints

### PR DESCRIPTION
**Pull request by akihironitta**
## Motivation
See #1897.

## Description of the changes
Converts comment style type hints (e.g. `a = 1  # type: int`) using new variable annotation syntax (e.g. `a: int = 1`) with [com2ann](https://github.com/ilevkivskyi/com2ann).

### CODE REVIEW

**Review by hvy — APPROVED** [review]
Thanks you for the quick action, looks solid. LGTM!

**Comment by hvy** [comment]
Purely a side note but you realize how `dict()` is mixed with `{}` and how we sometime use `Dict` for `defaultdict`s while there are some occurrences of `DefaultDict`.

**Comment by hvy** [comment]
@c-bata this should solve the entire tracking issue, do you want to have a look?

**Comment by c-bata** [comment]
OK. I'll review this PR 👍

**Comment by c-bata** [comment]
> Purely a side note but you realize how `dict()` is mixed with `{}` and how we sometime use `Dict` for `defaultdict`s while there are some occurrences of `DefaultDict`. Nits but they could be aligned/corrected.

Agree. We can replace it with `typing.DefaultDict` in following pull requests because we've already dropped Python 3.5.

**Review by c-bata — APPROVED** [review]
LGTM! Thank you for your contribution.

**Comment by hvy** [comment]
Thanks for the quick review!

@akihironitta would you like to continue with the follow up? Otherwise, we could create a separate issue.

**Comment by akihironitta** [comment]
@c-bata Thank you for the review! 
@hvy Sure, I'm happy to submit a follow-up PR!

**Comment by hvy** [comment]
That'd be great! 👍

**Pull request merged**
