### PR TITLE
Remove remaining examples

### PR DESCRIPTION
**Pull request by hvy**
## Motivation

Part of https://github.com/optuna/optuna/issues/2654.

## Description of the changes

Removes remaining examples from this repository. 

The `examples/` directory is kept (although more or less empty) along with its README since several users are still referring to this directory. We can perhaps remove this directory in the future.

### CODE REVIEW

**Comment by hvy** [comment]
@HideakiImamura , @nzw0301 could you take a look at this PR?

**Review by nzw0301 — CHANGES_REQUESTED** [review]
LGTM! Could you replace the links to the examples with the newer links in [`optuna/integration/botorch.py`](https://github.com/optuna/optuna/blob/2fd68d0102a22e76b5a4a142cc87722d92dcf667/optuna/integration/botorch.py#L338-L339) and [`optuna/pruners/_successive_halving.py`](https://github.com/optuna/optuna/blob/2fd68d0102a22e76b5a4a142cc87722d92dcf667/optuna/pruners/_successive_halving.py#L23)?

**Comment by hvy** [comment]
Thanks for the review, I first thought that you approved this PR so I mistakenly created a separate PR #2684 for that. Could we approve this PR as is or do you want to incorporate #2684 here?

**Comment by nzw0301** [comment]
Sorry for confusing you with my unclear review; I should not say LGTM with requesting changes. 

I think it is fine to approve this PR as in and treat #2684 separately.

**Review by nzw0301 — APPROVED** [review]

**Review by HideakiImamura — APPROVED** [review]
LGTM!

**Pull request merged**
