### PR TITLE
Remove "Edit on GitHub" button from readthedocs

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Resolve https://github.com/optuna/optuna/issues/3494 because https://github.com/optuna/optuna/pull/3777 didn't resolve the original issue on the [official docs](https://optuna.readthedocs.io/en/stable/index.html).

## Description of the changes

- Revert the change by https://github.com/optuna/optuna/pull/3777 because this change cannot remove the button on the docs hosted by readthedocs
- Create an HTML file by following the official way recommended by readthedocs https://docs.readthedocs.io/en/stable/guides/remove-edit-buttons.html#remove-links-from-top-right-corner

### CODE REVIEW

**Comment by nzw0301** [comment]
https://output.circle-artifacts.com/output/job/37e86104-efcf-4ae0-9db1-c939d00a47c8/artifacts/0/docs/build/html/index.html
The generated page, which is hosted on `artifact`, not readthedocs, will be as follows: 

Screenshot 2022-09-01 at 18 43 02

I'm not sure how to confirm the page on the readthedocs...

**Comment by nzw0301** [comment]
@toshihikoyanase could you take a look at this PR since you reviewed the related PR #3777 if you have time?

**Comment by HideakiImamura** [comment]
@toshihikoyanase Could you review this PR as @nzw0301 suggested?

**Review by toshihikoyanase — APPROVED** [review]
Ah, I only confirmed the settings in circleci artifact. Thank you.

> I'm not sure how to confirm the page on the readthedocs...

I guess we can create a follow-up PR if the document still has the button.
LGTM.

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by nzw0301** [comment]
Screenshot 2022-09-08 at 12 08 14
We cannnot see the buttons anymore :) 

ref: https://optuna.readthedocs.io/en/latest/reference/cli.html

**Pull request merged**
