### PR TITLE
[WIP] Unify plot pareto front

### PR DESCRIPTION
**Pull request by semiexp**
NOTE: #3128 should be merged before this PR. Once #3128 is merged, I will rebase this feature branch upon `master`

## Motivation
It is desirable to support `constraints_func` in `matplotlib.plot_pareto_front` as in #3128. To avoid repetition of pareto-front computation codes, we would like to factor out the preprocessing in `plot_pareto_front`s for pyplot and matplotlib.

## Description of the changes
Preprocessing of `plot_pareto_front` (for pyplot) is factored out so that it can be used by `matplotlib.plot_pareto_front` as well. At the same time, both 2D and 3D plots are done in a single function as in #3128.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
Note that this is related to #3116 and #2973.

**Comment by HideakiImamura** [comment]
@semiexp Let me kindly ping that #3128 has been merged.

**Comment by HideakiImamura** [comment]
@semiexp A friendly reminder :)

**Comment by semiexp** [comment]
`matplotlib/_pareto_front.py` has significantly changed since I committed this PR. I would like to re-implement this in another PR (#3389).

**Pull request closed without merging**
