### PR TITLE
Add constraint of Sphinx version

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Sphinx v4.0.0 has been released today, but it causes CI errors related to the documents, for example, https://github.com/optuna/optuna/runs/2537658469.

## Description of the changes

Add constraint not to use the latest sphinx.

### CODE REVIEW

**Review by hvy — APPROVED** [review]
LGTM, but do you know what the root cause is or how we can fix the error? Otherwise, we could leave a TODO to come back to the issue later.

**Comment by nzw0301** [comment]
No, I don't. I could not build the document correctly even if I use an older sphinx.  I agree with you; either the issue or TODO comment is necessary to fix this problem.

**Comment by nzw0301** [comment]
We can resolve the issue by waiting for a newer sphinx that will be released in the near future.
https://github.com/sphinx-doc/sphinx/issues/9193

**Review by toshihikoyanase — APPROVED** [review]
LGTM! Thank you for your fix.

**Comment by hvy** [comment]
I see, the local build is likely due to the environment, e.g. installed libraries. Thanks for adding the comment and creating the issue.

**Pull request merged**
