### PR TITLE
Improve test for heartbeat: Add test for the case that trial state should be kept running

### PR DESCRIPTION
**Pull request by cross32768**
## Motivation
Resolve Issue https://github.com/optuna/optuna/issues/4026

## Description of the changes
* Test that `fail_stale_trials` does not change the trial state if the trial is not stale.
* Test that `fail_stale_trials` does not change the trial state if `record_heartbeat` is never called.

### CODE REVIEW

**Comment by cross32768** [comment]
Should I take some action to solve the fail of CircleCI Pipeline?

**Comment by HideakiImamura** [comment]
@toshihikoyanase Could you review this PR?

@cross32768 Thanks for the PR! I have never encountered this problem. We cannot rerun the CI for this problem. Could you try to rebase on the master branch?

**Comment by cross32768** [comment]
I Added a small commit to rerun CircleCI Pipeline, but it looks not working again...

**Comment by cross32768** [comment]
I added some `time.sleep` for test (original code have some `time.sleep()`. I added one more `time.sleep()` sentence, thus it may double the running time of test code).
Could this cause CircleCI to dead?

**Comment by HideakiImamura** [comment]
Oh... Thanks for the try.

I will investigate your change soon. Please wait a minuite.

**Comment by HideakiImamura** [comment]
I checked your code, and I think this is reasonable and has nothing todo with the current error. It may be the problem of the branch based on this PR. Could you create another branch like `improve-heartbeat-test` and re-create the PR? Sorry for inconvenience.

**Pull request closed without merging**
