### PR TITLE
Fix a type casting error when using `CmaEsSampler`.

### PR DESCRIPTION
**Pull request by sile**
This PR fixes the following error that was occurred when I run a `CmaEsSampler` benchmark:
```console
$ kurobako --version
kurobako 0.1.14

$ wget $(kurobako dataset hpobench URL) && tar zxvf fcnet_tabular_benchmarks.tar.gz
$ kurobako problem-suite hpobench fcnet fcnet_tabular_benchmarks/ > problems.json
$ kurobako solver optuna --sampler cma-es > solvers.json

$ kurobako studies --problems (cat problems.json) --solvers (cat solvers.json) | kurobako run -q > result.json
  File "/home/ohta/.local/lib/python3.7/site-packages/kurobako/solver/__init__.py", line 172, in run
    while self._run_once():
  File "/home/ohta/.local/lib/python3.7/site-packages/kurobako/solver/__init__.py", line 186, in _run_once
    self._handle_ask_call(message)
  File "/home/ohta/.local/lib/python3.7/site-packages/kurobako/solver/__init__.py", line 214, in _handle_ask_call
    trial = solver.ask(idg)
  File "/home/ohta/.local/lib/python3.7/site-packages/kurobako/solver/optuna.py", line 86, in ask
    trial = self._create_new_trial()
  File "/home/ohta/.local/lib/python3.7/site-packages/kurobako/solver/optuna.py", line 172, in _create_new_trial
    return optuna.trial.Trial(self._study, trial_id)
  File "/home/ohta/dev/python/optuna/optuna/trial.py", line 409, in __init__
    self._init_relative_params()
  File "/home/ohta/dev/python/optuna/optuna/trial.py", line 420, in _init_relative_params
    self.study, trial, self.relative_search_space
  File "/home/ohta/dev/python/optuna/optuna/samplers/cmaes.py", line 201, in sample_relative
    optimizer.tell(solutions)
  File "/home/ohta/.local/lib/python3.7/site-packages/cmaes/cma.py", line 265, in tell
    self._mean += self._cm * self._sigma * y_w
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

### CODE REVIEW

**Comment by sile** [comment]
@c-bata Could you review this PR?

**Comment by c-bata** [comment]
Thank you for your fixes. I'll check soon.

**Comment by sile** [comment]
FYI, even if the patch is applied, another error occurs as follows. But I think that it's another issue to be addressed by a separate PR.
```
/home/ohta/.local/lib/python3.7/site-packages/cmaes/cma.py:294: RuntimeWarning:

divide by zero encountered in true_divide

/home/ohta/.local/lib/python3.7/site-packages/cmaes/cma.py:303: RuntimeWarning:

invalid value encountered in multiply

Traceback (most recent call last):
  File "/tmp/.tmpPyUgtn", line 89, in <module>
    runner.run()
  File "/home/ohta/.local/lib/python3.7/site-packages/kurobako/solver/__init__.py", line 172, in run
    while self._run_once():
  File "/home/ohta/.local/lib/python3.7/site-packages/kurobako/solver/__init__.py", line 186, in _run_once
    self._handle_ask_call(message)
  File "/home/ohta/.local/lib/python3.7/site-packages/kurobako/solver/__init__.py", line 214, in _handle_ask_call
    trial = solver.ask(idg)
  File "/home/ohta/.local/lib/python3.7/site-packages/kurobako/solver/optuna.py", line 86, in ask
    trial = self._create_new_trial()
  File "/home/ohta/.local/lib/python3.7/site-packages/kurobako/solver/optuna.py", line 172, in _create_new_trial
    return optuna.trial.Trial(self._study, trial_id)
  File "/home/ohta/dev/python/optuna/optuna/trial.py", line 409, in __init__
    self._init_relative_params()
  File "/home/ohta/dev/python/optuna/optuna/trial.py", line 420, in _init_relative_params
    self.study, trial, self.relative_search_space
  File "/home/ohta/dev/python/optuna/optuna/samplers/cmaes.py", line 209, in sample_relative
    params = optimizer.ask()
  File "/home/ohta/.local/lib/python3.7/site-packages/cmaes/cma.py", line 208, in ask
    x = self._sample_solution()
  File "/home/ohta/.local/lib/python3.7/site-packages/cmaes/cma.py", line 218, in _sample_solution
    D2, B = np.linalg.eigh(self._C)
  File "<__array_function__ internals>", line 6, in eigh
  File "/home/ohta/.local/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 1446, in eigh
    w, vt = gufunc(a, signature=signature, extobj=extobj)
  File "/home/ohta/.local/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 103, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
numpy.linalg.LinAlgError: Eigenvalues did not converge
```

**Comment by c-bata** [comment]
I see. Thank you for sharing the problem. May I have your kurobako problem which is able to reproduce your error?

**Comment by sile** [comment]
> May I have your kurobako problem which is able to reproduce your error?

The contents of `problems.json` and `solvers.json` are shown below:
```console
$ wget $(kurobako dataset hpobench URL) && tar zxvf fcnet_tabular_benchmarks.tar.gz
$ kurobako problem-suite hpobench fcnet fcnet_tabular_benchmarks/ > problems.json
{"hpobench":{"dataset":"./fcnet_naval_propulsion_data.hdf5"}}
{"hpobench":{"dataset":"./fcnet_parkinsons_telemonitoring_data.hdf5"}}
{"hpobench":{"dataset":"./fcnet_protein_structure_data.hdf5"}}
{"hpobench":{"dataset":"./fcnet_slice_localization_data.hdf5"}}

$ kurobako solver optuna --sampler cma-es > solvers.json
{"optuna":{"sampler":"cma-es"}}
```

**Comment by sile** [comment]
Sorry. The issue I reported in https://github.com/optuna/optuna/pull/1240#issuecomment-628380163 seems resolved after I updated the `cmaes` version from v0.3.2 to v0.5.0.

**Comment by sile** [comment]
@c-bata Thank you for the quick review! I also added `dtype=float` to other `np.array` calls as you suggested (https://github.com/optuna/optuna/pull/1240/commits/7faa6f765449cd2da389fac58b478454b40e1986).

**Comment by c-bata** [comment]
> Sorry. The issue I reported in #1240 (comment) seems resolved after I updated the cmaes version from v0.3.2 to v0.5.0.

I see. Thank you. It's a known issue of numerical overflow error. And it is fixed at v0.5.0 release.
https://github.com/CyberAgent/cmaes/releases/tag/v0.5.0

**Pull request merged**
