### PR TITLE
Follow up PR #4642 by adding a unit test to confirm `OptunaSearchCV` behavior

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Follow up #4642 by adding a unit test.

## Description of the changes
Add a unit test to confirm if `OptunaSearchCV` keeps optimizing even when some trial fails due to exception.

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
@not522 Could you review this PR, please?
I think we can merge this PR with a single approval since it only changes a unit test.

**Review by not522 — COMMENTED** [review]
Could you add a comment that sklearn raises `ValueError` for `max_depth==0`?

**Comment by Alnusjaponica** [comment]
I added code comments. PTAL.

**Review by not522 — APPROVED** [review]
LGTM!

**Pull request merged**
