### PR TITLE
Add Matplotlib to `setup.py`.

### PR DESCRIPTION
**Pull request by ytknzw**
This PR proposes to add ``matplotlib`` to `setup.py` for the `matplotlib` backends based on PR #1756 .

## Motivation
To provide another visualization option for users, who have only ``plotly`` now.
See issue #1539 and PR #1707 for the original motivation.

## Description of the changes
Add `matplotlib>=3.0.0` to `doctest`, `testing` and `optional` in `setup.py`.

### CODE REVIEW

**Review by crcrpar — COMMENTED** [review]
Nice, but could you update this branch?

**Comment by ytknzw** [comment]
@crcrpar Thanks, I've just updated.

**Review by HideakiImamura — APPROVED** [review]
Good catch! LGTM!

**Review by crcrpar — APPROVED** [review]
Really sorry for bothering you again... could you update the branch?

**Comment by ytknzw** [comment]
No problem, done.

**Pull request merged**
