### PR TITLE
Remove XGBoost Integration

### PR DESCRIPTION
**Pull request by y0z**
# Motivation
- Salvage https://github.com/optuna/optuna/pull/5218.

# Description of the changes
- Cherry-pick commits from #5218

### CODE REVIEW

**Comment by nabenabe0928** [comment]
@y0z Could you remove xgboost from pyproject.toml?

**Review by nabenabe0928 — APPROVED** [review]
LGTM!

**Review by contramundum53 — APPROVED** [review]
LGTM!

**Comment by y0z** [comment]
Done: https://github.com/optuna/optuna/issues/4484

**Pull request merged**
