### PR TITLE
Check everything by blackdoc.

### PR DESCRIPTION
**Pull request by keisuke-umezawa**
## Motivation

Check everything by blackdoc.

## Description of the changes

Update CI and checks.sh to use `blackdoc .`.
Actually, there are no update in the code, due to these lines https://github.com/optuna/optuna/blob/master/pyproject.toml#L16-L17. blackdoc skips docs and tutorials.

### CODE REVIEW

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Review by crcrpar — COMMENTED** [review]
[Question] Is there any file in examples and tests directories that has docstring?

**Comment by keisuke-umezawa** [comment]
@crcrpar 
> [Question] Is there any file in examples and tests directories that has docstring?

Basically, there is nothing in them. But, I would like to run the command with `blackdoc .`.

**Review by hvy — APPROVED** [review]
LGTM!

**Pull request merged**
