### PR TITLE
Remove jquery-extension

### PR DESCRIPTION
**Pull request by Alnusjaponica**
## Motivation
Remove `jquery-extension` used in `conf.py` as https://github.com/readthedocs/sphinx_rtd_theme/issues/1452 is resolved in `sphinx_rtd_theme` v 1.2.1. See this [change log](https://sphinx-rtd-theme.readthedocs.io/en/stable/changelog.html#theme-version).

## Description of the changes
Ditto

### CODE REVIEW

**Review by HideakiImamura — APPROVED** [review]
LGTM. The CIs are stale due to unexpected hanging. Do you have any idea?

**Comment by Alnusjaponica** [comment]
I am not sure why, but this happened the last time I updated the PR as well. Let me re-run the checks again.

**Comment by toshihikoyanase** [comment]
The CI jobs were canceled due to some higher-priority jobs. I'll rerun them.

https://github.com/optuna/optuna/actions/runs/5250259110
> Canceling since a higher priority waiting request for 'Tests-refs/pull/4691/merge' exists

**Review by toshihikoyanase — APPROVED** [review]
I confirmed that the docs were rendered without the jquery extension. LGTM.
I'll merge this PR after the CI jobs pass.

**Comment by toshihikoyanase** [comment]
Let me merge this PR since all the CI jobs passed.

**Pull request merged**
