### PR TITLE
Remove BoTorch integration

### PR DESCRIPTION
**Pull request by y0z**
## Motivation
Progress https://github.com/optuna/optuna/issues/4484.
Remove the BoTorch integration for migration to optuna_integration.

Please merge https://github.com/optuna/optuna-integration/pull/72 before merging this PR.

## Description of the changes
- Remove the BoTorch integration and the related tests from optuna.

### CODE REVIEW

**Review by contramundum53 — APPROVED** [review]
LGTM!

**Comment by contramundum53** [comment]
@nabenabe0928 Could you review this PR?

**Comment by nabenabe0928** [comment]
- [ ] https://github.com/optuna/optuna/blob/master/docs/source/faq.rst?plain=1#L436
- [ ] https://github.com/optuna/optuna/blob/master/docs/source/faq.rst?plain=1#L491
- [ ] https://github.com/optuna/optuna/blob/master/pyproject.toml
- [ ] https://github.com/optuna/optuna/blob/master/benchmarks/bayesmark/optuna_optimizer.py

**Review by nabenabe0928 — CHANGES_REQUESTED** [review]
I created a TODO list.

**Comment by contramundum53** [comment]
@nabenabe0928 We include integrations in benchmarks, like `CmaSampler`

**Comment by nabenabe0928** [comment]
@y0z Sorry, docs include terminator, so we could not remove botorch from the doc section right now...

**Review by nabenabe0928 — APPROVED** [review]
LGTM!

**Pull request merged**
