### PR TITLE
[Dependency Update] PyTorch and AllenNLP

### PR DESCRIPTION
**Pull request by crcrpar**
## Description of the changes

- PyTorch: 1.7.0
- vision: 0.8.1
- audio: 0.7.0 (following pytorch.org)
- Allennlp: 1.2.0

CC: @himkt

### CODE REVIEW

**Review by himkt — APPROVED** [review]
I went through the release notes of `torchaudio` and `allennlp` and didn't find incompatible changes that affect Optuna (`torchaudio` isn't used anywhere). And all checks have passed. LGTM.

===

I also found Dockerfiles in `examples/kubernetes/{simple,mlflow}` (`mlflow/Dockerfile` installs `torch==1.5.1` and `simple/Dockerfile` uses Python3.5) are a little bit obsolete, although it may be out of the scope of this PR.

**Comment by hvy** [comment]
Good catch and thanks for the PR. Do you happen to know if the examples still work after these changes?

**Comment by crcrpar** [comment]
Cound ran pytorch related examples w/o errors. dunno the final scores are valid or not.

**Review by hvy — APPROVED** [review]
LGTM!

I ran the PyTorch/Lightning/Ignite examples at least as well and they seem to be converging.

**Pull request merged**
