### PR TITLE
Add SNS URLs to `README.md`

### PR DESCRIPTION
**Pull request by nabenabe0928**
## Description of the changes

- Add SNS accounts to `README.md`

### CODE REVIEW

**Review by HideakiImamura — COMMENTED** [review]
How about just adding those SNS URLs instead of removing that of examples?

**Comment by HideakiImamura** [comment]
@eukaryo Could you review this PR?

**Comment by nabenabe0928** [comment]
@HideakiImamura I reverted the examples!

**Review by eukaryo — APPROVED** [review]
LGTM.

**Review by HideakiImamura — APPROVED** [review]
Thanks! LGTM!

**Pull request merged**
