### PR TITLE
Simplify annotations in `optuna/pruners/_successive_halving.py` and `optuna/pruners/_threshold.py`

### PR DESCRIPTION
**Pull request by keita-sa**
## Motivation
I've also updated the notation in the .py file of the above title.

To resolve #4508.

## Description of the changes
Added:
`__future__.annotations`

Deleted:
`typing.List`
`typing.Union`
`typing.Optional`

### CODE REVIEW

**Review by nzw0301 — APPROVED** [review]
LGTM. I think `git reset` with some options and `git push` with force option can reset the commit history on github; by using such git features, you will not need to create multiple PRs.

Dear core-dev team, could the other review merge this PR with the squash merge option when merging this PR since the commit history looks a little bit messy?

**Review by eukaryo — APPROVED** [review]
Basically LGTM. Let me merge this PR after the CI passes.

I noticed that the #5341 was closed and this PR was opened following my review comments. While I understand this might have seemed like the best approach, it's generally more efficient to continue working on the same PR, #5341 . This way, the discussion and review comments remain in a single thread, maintaining context and transparency for everyone involved.

In future contributions, I encourage you to make any necessary changes in the same PR.

**Comment by eukaryo** [comment]
I've noticed that changes related to `_threshold.py` have been added to this PR, which was initially focused on `_successive_halving.py` . 
The recent changes also LGTM, and your initiative is commendable; however, for the sake of a streamlined review process, it's crucial that each PR remains focused on a specific task. To manage multiple PRs concurrently, it's helpful to create separate branches in your fork for each PR, or set of changes you wish to propose.

**Comment by keita-sa** [comment]
I knew that each task should be done in its own pull request, but my GitHub skills are not good enough for that. My apologies. I am currently catching up on GitHub commands, and in the future, I will be more careful in opening pull requests and commits.

**Comment by eukaryo** [comment]
I'm here to support and ensure you enjoy contributing. Thanks again for all your efforts, and I look forward to seeing more of your PRs.

**Pull request merged**
