### PR TITLE
Implement nsgaiii elite population selection strategy

### LINKED ISSUE #4937: Implement `NSGAIIIElitePopulationSelectionStrategy`
### Motivation

To simplify the code base by integrating common parts of `NSGAIISampler` and `NSGAIIISampler`.

Previously, `NSGAIISampler` and `NSGAIIISampler` shared the code except for `_select_elite_population()` and the initializer. However, the population selection part of `NSGAIISampler` has been separated as `NSGAIIElitePopulationSelectionStrategy` in https://github.com/optuna/optuna/pull/4821. The same refactoring remains as a follow-up task."

### Suggestion

1. Create directory named `samplers/_nsgaiii`
2. Move `_select_elite_population()` and functions used in it to `samplers/nsgaiii/_elite_population_selection_strategy.py` to implement `NSGAIIIElitePopulationSelectionStrategy` as in https://github.com/optuna/optuna/pull/4821.
3. Move other part of `_nsgaiii.py` to `samplers/_nsgaiii/_sampler.py`
4. Update import path in `samplers/__init__.py` and related tests.

### Additional context (optional)

This is the first step to integrate the common part of the two samplers. How to complete this task is yet to be decided.

### PR DESCRIPTION
**Pull request by g-tamaki**
Resolve #4937

## Motivation

To simplify the code base by integrating common parts of NSGAIISampler and NSGAIIISampler.

Previously, NSGAIISampler and NSGAIIISampler shared the code except for _select_elite_population() and the initializer. However, the population selection part of NSGAIISampler has been separated as NSGAIIElitePopulationSelectionStrategy in https://github.com/optuna/optuna/pull/4821. The same refactoring remains as a follow-up task."

## Description of the changes

1. Create directory named samplers/_nsgaiii
2. Move _select_elite_population() and functions used in it to samplers/_nsgaiii/elite_population_selection_strategy.py to implement NSGAIIIElitePopulationSelectionStrategy as in https://github.com/optuna/optuna/pull/4821.
3. Move other part of _nsgaiii.py to samplers/_nsgaiii/sampler.py
4. Update import path in samplers/__init__.py and related tests.

### CODE REVIEW

**Review by HideakiImamura — APPROVED** [review]
Thanks for the code fix. LGTM.

**Review by Alnusjaponica — CHANGES_REQUESTED** [review]
Thanks for the PR. Could you change the newly added module private, i.e., rename file from `optuna/samplers/_nsgaiii/elite_population_selection_strategy.py` to `optuna/samplers/_nsgaiii/_elite_population_selection_strategy.py`  and from `optuna/samplers/_nsgaiii/sampler.py` to `optuna/samplers/_nsgaiii/_sampler.py`, and fix import paths?

**Comment by Alnusjaponica** [comment]
Almost LGTM. Please remove `optuna/samplers/_nsgaiii.py` to resolve the conflict.

**Review by Alnusjaponica — APPROVED** [review]

**Comment by g-tamaki** [comment]
There is already no `optuna/samplers/_nsgaiii.py`, what should I do? I moved `optuna/samplers/_nsgaiii.py` to `optuna/samplers/_nsgaiii/_elite_population_selection_strategy.py` in the past, which may have been a bad idea. Any advice would be appreciated.

**Comment by Alnusjaponica** [comment]
I apologize for causing a misunderstanding. I now understand the situation.

Is it possible for you to merge the "optuna:master" branch into "g-tamaki:Implement_NSGAIIIElitePopulationSelectionStrategy" locally and then push it? I believe this can likely be done by following this command line instruction.

スクリーンショット 2023-10-05 13 23 48

**Comment by Alnusjaponica** [comment]
I apologize for the delay in my response. I have selected specific commits related to this PR and resubmitted them as a separate PR to maintain the commit history and preserve your contribution. Please review and let me know if there are any issues with the changes made in https://github.com/optuna/optuna/pull/5027.

**Comment by Alnusjaponica** [comment]
I would like to close this PR because the follow-up PR at https://github.com/optuna/optuna/pull/5027 has been merged. We highly appreciate your contribution.

**Pull request closed without merging**
