### PR TITLE
Fix test_with_server.py

### PR DESCRIPTION
**Pull request by contramundum53**
Currently, `test_multiprocess_run_optimize` function copies `RDBStorage` object (and thus its underlying sqlalchemy object) to subprocesses. This causes probabilistic and platform-dependent hangs in CI. We fix this by calling `get_storage` function in each subprocess.

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
@c-bata @gen740 Could you review this PR, please?

**Comment by c-bata** [comment]
In this PR, we need to remove a following line to use SQLAlchemy v2.0. However, the CI will be blocked by the issue that is fixed at https://github.com/optuna/optuna/pull/4386.
https://github.com/optuna/optuna/blob/b61490368feeb237afd957afd2db7eb61b0272e7/.github/workflows/tests-storage.yml#L92

@contramundum53 How about making this PR draft until #4386 is merged.

**Comment by contramundum53** [comment]
Using SQLAlchemy 2.0 is not strictly necessary for this PR to be effective, although the problem won't surface in CI until SQLAlchemy 2.0.

**Comment by contramundum53** [comment]
I suppose this PR can be reviewed in parallel with #4386.

**Review by gen740 — APPROVED** [review]
LGTM!

I think it is clear to merge this commit with
https://github.com/optuna/optuna/blob/b61490368feeb237afd957afd2db7eb61b0272e7/.github/workflows/tests-storage.yml#L92
uncommented after #4386 was merged.

**Comment by c-bata** [comment]
@contramundum53 Thank you for merging #4386 :bow:

Could you rebase on or merge with master branch and remove a version constraint?

**Comment by c-bata** [comment]
@contramundum53 Thank you for the update! I think you can remove the following line.
https://github.com/optuna/optuna/blob/b61490368feeb237afd957afd2db7eb61b0272e7/.github/workflows/tests-storage.yml#L92

**Review by c-bata — APPROVED** [review]
I re-run the `tests-rdbstorage` action 10 times and confirmed that the problem does not occur.
https://github.com/optuna/optuna/actions/runs/4192793456/jobs/7274245707

There may be still room for improvements regarding how to clean up studies, but we can work on it in following pull requests. LGTM!

**Pull request merged**
