### PR TITLE
Fix typos and remove unused argument in QMC

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

By chance, I found a few typos and unused argument in a method in qmc sampler files.

## Description of the changes

The introduced changes are as follows:
Fix typos:
    - catagorical -> categorical
    - asyncronous -> asynchronous
- Remove `search_space` argument in `_find_sample_id` method since it is not used

### CODE REVIEW

**Comment by nzw0301** [comment]
Why does `Checks` look fine without #3832...?

**Comment by himkt** [comment]
`Checks (Integration)` is only kicked on the master branch.
https://github.com/optuna/optuna/blob/0ce7c06f73be324e4878ec2f5882f18d01d9ea43/.github/workflows/checks-integration.yml

**Comment by nzw0301** [comment]
@himkt ah, Indeed. Thank you for letting me know that!

**Comment by HideakiImamura** [comment]
@contramundum53 Could you review this PR?

**Review by contramundum53 — APPROVED** [review]
LGTM!

**Review by HideakiImamura — APPROVED** [review]
LGTM. The name of argument is fixed, so this is a breaking change. But, `QMCSampler` is an experimental, so we can change it without priori notice.

**Pull request merged**
