### PR TITLE
Align the usage of type hints and instantiation of dictionaries

### PR DESCRIPTION
**Pull request by akihironitta**
## Motivation
This is a follow-up PR of #1950. cc: @hvy 

As pointed out in https://github.com/optuna/optuna/pull/1950#issuecomment-714341537, there are inconsistencies in instantiating dictionary and type hints for `defaultdict`s. 
> Purely a side note but you realize how `dict()` is mixed with `{}` and how we sometime use `Dict` for `defaultdict`s while there are some occurrences of DefaultDict. Nits but they could be aligned/corrected.

## Description of the changes
Use the type `DefaultDict` for `defaultdict`s.
Use `{}` to generate an empty instance of `dict`.

### CODE REVIEW

**Comment by akihironitta** [comment]
@hvy Which would you prefer to use to generate `dict` instances, `dict()` or `{}`?

**Comment by hvy** [comment]
Well, this is not a strong opinion but I personally prefer the `{}` literals. I find it more readable, it cannot be shadowed like `dict` which can be reassigned, and I recall it's faster.

**Comment by akihironitta** [comment]
@hvy Thanks for the quick response. I didn't know about that. Sure, then let's use `{}`.

**Comment by akihironitta** [comment]
### List of lines where using `dict()`
```
./optuna/integration/tensorboard.py:37:        self._hp_params: Dict[str, hp.HParam] = dict()
./optuna/integration/tensorboard.py:45:        hparams = dict()
./optuna/storages/_cached_storage.py:24:        self.intermediate_values: Dict[int, float] = dict()
./optuna/storages/_cached_storage.py:25:        self.user_attrs: Dict[str, Any] = dict()
./optuna/storages/_cached_storage.py:26:        self.system_attrs: Dict[str, Any] = dict()
./optuna/storages/_cached_storage.py:27:        self.params: Dict[str, Any] = dict()
./optuna/storages/_cached_storage.py:28:        self.distributions: Dict[str, distributions.BaseDistribution] = dict()
./optuna/storages/_cached_storage.py:39:        self.updates: Dict[int, _TrialUpdate] = dict()
./optuna/storages/_cached_storage.py:60:        self._trial_id_to_study_id_and_number: Dict[int, Tuple[int, int]] = dict()
./optuna/distributions.py:353:        kwargs = ", ".join("{}={}".format(k, v) for k, v in sorted(self._asdict().items()))
./optuna/distributions.py:504:    return json.dumps({"name": dist.__class__.__name__, "attributes": dist._asdict()})
./optuna/trial/_trial.py:752:                "Using these values: {}".format(name, old_distribution._asdict()),
./tests/test_distributions.py:325:def test_uniform_distribution_asdict() -> None:
./tests/test_distributions.py:327:    assert EXAMPLE_DISTRIBUTIONS["u"]._asdict() == {"low": 1.0, "high": 2.0}
./tests/test_distributions.py:330:def test_log_uniform_distribution_asdict() -> None:
./tests/test_distributions.py:332:    assert EXAMPLE_DISTRIBUTIONS["l"]._asdict() == {"low": 0.001, "high": 100}
./tests/test_distributions.py:335:def test_discrete_uniform_distribution_asdict() -> None:
./tests/test_distributions.py:337:    assert EXAMPLE_DISTRIBUTIONS["du"]._asdict() == {"low": 1.0, "high": 9.0, "q": 2.0}
./tests/test_distributions.py:340:def test_int_uniform_distribution_asdict() -> None:
./tests/test_distributions.py:342:    assert EXAMPLE_DISTRIBUTIONS["iu"]._asdict() == {"low": 1, "high": 9, "step": 2}
./tests/test_distributions.py:345:def test_int_log_uniform_distribution_asdict() -> None:
./tests/test_distributions.py:347:    assert EXAMPLE_DISTRIBUTIONS["ilu"]._asdict() == {"low": 2, "high": 12, "step": 2}
```

**Comment by akihironitta** [comment]
### List of lines using `defaultdict`
`grep "defaultdict" . -rn`
```
./optuna/dashboard.py:102:            stream_dict: Dict[str, List[Any]] = collections.defaultdict(list)
./optuna/visualization/_parallel_coordinate.py:1:from collections import defaultdict
./optuna/visualization/_parallel_coordinate.py:101:            vocab: DefaultDict[str, int] = defaultdict(lambda: len(vocab))
./optuna/_dataframe.py:45:    column_agg: Dict[str, Set] = collections.defaultdict(set)
./optuna/multi_objective/samplers/_nsga2.py:1:from collections import defaultdict
./optuna/multi_objective/samplers/_nsga2.py:172:        generation_to_runnings = defaultdict(list)
./optuna/multi_objective/samplers/_nsga2.py:173:        generation_to_population = defaultdict(list)
./optuna/multi_objective/samplers/_nsga2.py:278:    dominated_count: DefaultDict[int, int] = defaultdict(int)
./optuna/multi_objective/samplers/_nsga2.py:279:    dominates_list = defaultdict(list)
./optuna/multi_objective/samplers/_nsga2.py:317:    manhattan_distances = defaultdict(float)
```

**Review by c-bata — APPROVED** [review]
Thank you! LGTM 👍

**Review by hvy — APPROVED** [review]
LGTM!

**Pull request merged**
