### PR TITLE
Use _SearchSpaceTransform in RandomSampler

### PR DESCRIPTION
**Pull request by sfujiwara**
## Motivation

- Use new feature `_SearchSpaceTransform` to make samplers simple

## Description of the changes

- [x] Modify `RandomSampler` to use `_SearchSpaceTransform`
- [x] Check performance using [kurobako](https://github.com/sile/kurobako)

### CODE REVIEW

**Comment by sfujiwara** [comment]
The below is a result of benchmark on kurobako:
sigopt-evalset-ackley-dim-2-628b265e8c7bdd9f7d53f1c86b288cd4defd0fb74a34a945e547c5d8acca895d

This is a part of commands for kurobako:
 
```shell script
# Install modified Optuna and try on new sampler...

PROBLEM=$(kurobako problem sigopt ackley)
SOLVERS=$(kurobako solver --name "new random sampler" optuna --sampler RandomSampler)

kurobako studies \
  --problems "${PROBLEM}" \
  --solvers "${SOLVERS}" \
  --budget 50 \
  --repeats 50 | kurobako run > new-result.json

# Install old Optuna and try same command for old sampler...
# ...
```

Please let me know if we needs other information.

**Comment by keisuke-umezawa** [comment]
@hvy @sile 
If you have time, could you review it?

**Comment by sile** [comment]
🙋‍♂️

**Comment by hvy** [comment]
Thanks a lot for the PR and even the benchmarks. The results seems good given those 50 repetitions. I'm wondering if we could also test the discrete suggest methods like `suggest_int` and `suggest_categorical` (ideally `step` and `log`) to make sure.

**Comment by sile** [comment]
> test the discrete suggest methods like `suggest_int` and `suggest_categorical`

I think that HPOBench is good for that purpose.
You can set up the benchmark problem as follows:
```console
$ wget $(kurobako dataset hpobench url)
$ tar zxvf fcnet_tabular_benchmarks.tar.gz
$ cd fcnet_tabular_benchmarks/
$ PROBLEM=$(kurobako problem hpobench fcnet_protein_structure_data.hdf5)
```

**Comment by sfujiwara** [comment]
Thanks. I tried HPOBench following your advice. The result is below:

hpo-bench-protein-89816c43cbdac640590a36a93d9d2d6565ca366efd8b0c1dfb0d57b174d28989

**Review by sile — APPROVED** [review]
The code and benchmark results seem good, thank you!

**Comment by hvy** [comment]
Thanks for sharing your benchmark result. I'd like to merge this PR but could you just merge or somehow sync with the latest `master` branch? The CI is failing although the cause is irrelevant to your changes. It's been fixed in `master` with https://github.com/optuna/optuna/pull/2418.

**Comment by sfujiwara** [comment]
Sorry for my late response. I tried rebase, but different CI errors on integration tests occurred. Do you know what this is?

**Comment by hvy** [comment]
Thanks! The CI error is not caused by the changes here. It's currently discussed in https://github.com/optuna/optuna/pull/2508. Sorry for the inconvenience but let me come back to this PR once that's fixed.

**Comment by toshihikoyanase** [comment]
@sfujiwara #2508 was merged and the CI jobs should be successful if you sync the feature branch with the master branch.

**Comment by sfujiwara** [comment]
Thanks. I did rebase the branch and all CI jobs succeeded!

**Review by hvy — APPROVED** [review]
Thanks for the updates, LGTM! This change simplifies the code a lot. 👍

**Pull request merged**
